### ISSUE TITLE
Tailscale does NOT autostart on Android when it's seelcted as Always-On VPN

### ISSUE THREAD

**Issue by pshirshov** [tailscale/tailscale#10013]
### What is the issue?

Steps to reproduce on Google Pixel 7 Pro with stock OS:

1. Install Tailscale from Play Store, connect to a network
2. Make sure that Tailscale is set as an Always-On VPN in the system settings
3. Reboot the phone. Tailscale won't autostart and autoconnect. If "Block connections without VPN" checkbox is set (which is the default), the phone will have no connectivity at all.

Related: #510

### OS

Android

### Tailscale version

1.48.2

**Comment by pshirshov** [comment]
Related: https://github.com/tailscale/tailscale/issues/9428

**Comment by rcassel52** [comment]
I have the same issue on two Motorola ppl hones and 2 Samsung tablets.   It was working a few months ago

**Comment by mateon1** [comment]
I have the same issue.
On Pixel 6 Pro, even with "Always On" VPN and "Block connections without VPN", after a device restart Tailscale has the running toggle set to disabled and exit node reset to "None".
Tailscale version: 1.52.0
NOTE: on an older phone (Xiaomi MI 6) I had an outdated version of tailscale (1.44.1) where this problem did not happen. It's likely this is a regression.

**Comment by r01k** [comment]
`Always-on VPN` is enabled for the TC app and under battery settings `Allow background activity` and `Allow auto launch` are enabled. Yet upon reboot the VPN does not activate. When the app is opened manually the VPN toggle is disabled even though it was enabled before rebooting.

This is a deal-breaker in our testing phase for TC as a potential tunnel solution to internal services for roaming users.

**Comment by gravelfreeman** [comment]
I don't understand why but I have the same issue despite it was working fine 1 month ago. I think it stopped working after the latest Android update. This is a root feature to be working for a VPN. Hope this gets fixed soon!

**Comment by SurfingSpider** [comment]
+1 same issue. Just installed it on all the families phones then realised it doesn't work after reboot. If you have preteen kids you know this is a daily recurrence. So it might be a deal-breaker for me.

**Comment by SurfingSpider** [comment]
Is there a fix in sight for this?

**Comment by pshirshov** [comment]
No, there isn't.

**Comment by MrPenguin07** [comment]
Since installing some months ago, I assumed this feature had never existed.

Now I see it's a regression. A very important feature, I hope to see progress on this ?!

**Comment by pshirshov** [comment]
It's being ignored for months, if I were you I won't have my hopes high.

**Comment by Immanuel31** [comment]
The latest seems to be in https://github.com/tailscale/tailscale/issues/9428

**Comment by MrPenguin07** [comment]
This issue is also triggered when updating the app;

The active connection is dropped and requires manually opening tailscale, toggle back to active then re-enable the exit node (if running one as I do).

**Comment by SurfingSpider** [comment]
The solution for tailscale not autostarting on android boot that I have found to work is to use Tasker android app. To turn it on when I leave the home WiFi. There is a profile on Taskernet that will do it for you. You just have to input your WiFi network name. 

https://taskernet.com/shares/?user=AS35m8mw6l1fRiYiFT08BoSg2mZkLHMIM%2FLqDO6Cu6wtD0G6d6P0V2ScVHtXYxjUT0DfjK5lPQd9Fm4%3D&id=Profile%3ATailscale+When+Not+Home

Obviously I would prefer not to have to use this and them to actually fix the app.

**Comment by Immanuel31** [comment]
```
# connect
adb shell am broadcast -n com.tailscale.ipn/.IPNReceiver -a com.tailscale.ipn.CONNECT_VPN
​
# disconnect
adb shell am broadcast -n com.tailscale.ipn/.IPNReceiver -a com.tailscale.ipn.DISCONNECT_VPN
```
The above should do the trick if you can connect to the device via adb (Android Debug Bridge).

**Comment by scientiac** [comment]
Woow @Immanuel31 we were testing the same thing at the same time... But, I used the quick settings toggle to toggle tailscale on and off.

I managed to make it auto start if you're rooted and your Termux auto starts:

Install `su` in termux and termux:boot app to make termux auto start on boot. Then put this in a file in `.termux/boot/`

```bash
# Start the tailscale IPNService.
su -c "am start-foreground-service com.tailscale.ipn/.IPNService"

# Wait for tailscale IPNService to fully start.
sleep 1

# Add the quick settings tile.
su -c "cmd statusbar add-tile com.tailscale.ipn/.QuickToggleService"

# Wait for add-tile to take action.
sleep 0.35

# Click tile, wait for it to react.
su -c "cmd statusbar click-tile com.tailscale.ipn/.QuickToggleService"

# Wait for tile click to take action.
sleep 0.35

# Remove tile from quick settings.
su -c "cmd statusbar remove-tile com.tailscale.ipn/.QuickToggleService"
```

**Comment by scientiac** [comment]
Using @Immanuel31 's method, just put the following line in a file in the `.termux/boot/' directory after setting up termux according to the previous comment.

```bash
su -c "am broadcast -n com.tailscale.ipn/.IPNReceiver -a com.tailscale.ipn.CONNECT_VPN"
```

**Comment by agottardo** [comment]
Just a heads-up that this issue has been fixed in our new Android app. Tailscale will automatically restart upon a system restart when set to always-on. You can try the new version by joining the [beta testing track](https://play.google.com/apps/testing/com.tailscale.ipn) on the Play Store. 

If you're still experiencing this issue, please let us know.

**Comment by MrPenguin07** [comment]
> Just a heads-up that this issue has been fixed in our new Android app. Tailscale will automatically restart upon a system restart when set to always-on.

First I'd like to express my gratitude for working on this.

I've updated to 1.62.0, and can confirm the always on vpn starts up at boot.

However, it does not remember the exit node previously set, which is equally as important to me.

Also would appreciate if these latest builds could be pushed to your f-droid repo, as I suspect there are many of us who are de-googled or prefer not use Google store.

Regards.

**Comment by tsmoneta** [comment]
The Android version with the fixes is 1.65, and it's available in the Play Store, with a beta tester signup.

**Comment by burner1024** [comment]
I'm on 1.72.0, and it still doesn't auto connect on reboot. Only after screen is unlocked, it connects.
Anyone else has this?

**Comment by bdd** [comment]
> I'm on 1.72.0, and it still doesn't auto connect on reboot. Only after screen is unlocked, it connects. Anyone else has this?

This is expected.
Tailscale's app uses Android's [EncryptedSharedPreferences](https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences) API to store device local state which includes machine key, profile, etc. in an encrypted state. The cryptographic abstraction it uses relies on a hardware backed keystore your Android device has. The PIN (or pattern or alphanumeric code) you use to unlock your screen also unlocks the said hardware backed keystore after boot. Without first unlock, Tailscale has no way to decrypt its own encrypted state.

**Comment by burner1024** [comment]
@bdd Thank you for the explanation.

I assume that killswitch doesn't work until first unlock then, yes?

**Comment by ameer1234567890** [comment]
Is there any way we can make it auto run on unlock?

**Comment by bdd** [comment]
> Is there any way we can make it auto run on unlock?

It does that.
Settings -> Network & Internet ->. VPN -> Tailscale -> Always-on VPN: 
Enabled

On my Pixel running the latest available OS to it with Tailscale 1.78.3, it connects as soon as I unlock the phone.

**Comment by christianh104** [comment]
Tailscale does not automatically start on my Pixel 8a despite Always-On VPN being enabled and background battery usage being unrestricted. I believe this is also the case on my OnePlus phone. I'm running 1.86.4. Last I had checked in on this it wasn't fixed yet. Now it's supposed to be fixed but it doesn't work for me. Are there any logs I can check to see what's going on?

**Comment by tomac4t** [comment]
> I believe this is also the case on my OnePlus phone. I'm running 1.86.4. Last I had checked in on this it wasn't fixed yet. Now it's supposed to be fixed but it doesn't work for me. Are there any logs I can check to see what's going on?

I also have this problem, can't auto-restart after the phone reboot.

```
Tailscale for Android 1.90.1
Android 14
OnePlus 8T / ColorOS 14.0
```
