### ISSUE TITLE
Unable to configure nextDNS on a per device basis using ACLs

### ISSUE THREAD

**Issue by anubhavcodes** [tailscale/tailscale#11951]
### What is the issue?

I have nextDNS configured via tailscale using this documentation:

https://tailscale.com/kb/1218/nextdns

In my DNS settings in tailscale I use the nextDNS profile for my global nameservers and I have the option `Override local DNS` checked. 

In my ACLS, I have the following added: 

```
{
  "nodeAttrs": [
    {
      "target": [
        "tag:nextdns"
      ],
      "attr": [
        "nextdns:xxxxxx"
      ]
    }
  ]
}
```

And I have only a few devices tagged with the tag `nextdns`. 

My expectation is I would only like the tagged devices to use nextDNS, and not all devices. But in my nextDNS dashboard, I can still see logs from all of my devices in my tailnet. 

### Steps to reproduce

1. Configure tailscale to use nextDNS nameservers and override local dns. 
2. Create an ACL rule that allows specific devices ( with tags ) to use your nextDNS profile. 
3. Go to nextDNS dashboard -> logs and you still see all the devices using nextDNS. 

### Are there any recent changes that introduced the issue?

No, I was using two profiles for nextDNS with two seperate ACL rules, and that worked perfectly. I decided some devices with one profile just doesn't need to use nextDNS ( and save the dns calls for my account ). 

So I deleted the profile from nextDNS, and deleted the ACL rule with the particular profile, and my expectation was only the devices tagged to use nextDNS will use it, others will default to local DNS. 

### OS

Linux, macOS, Other

### OS version

tvOS 17.4.0, Linux 6.1.0-16-amd64 # devices that are not tagged

### Tailscale version

1.64.0

### Bug report

BUG-7c92a6c4a364150a3d443b60551cbdb6bfd354d8bc589e0b189a81b94caaca02-20240501112422Z-171bda8488ca76f2

**Comment by kelivel** [comment]
Hi @anubhavcodes! DNS configurations are currently applied to all devices that enable Tailscale DNS in the client. NextDNS is unique and can set up different profiles for devices, but all devices that opt in to DNS will still get a DNS configuration sent down from Tailscale. In your case, all your devices will inherit at least one of your NextDNS profiles.

You could disable Tailscale DNS entirely per device using `--accept-dns=false` in CLI or from the app GUI (uncheck "Use Tailscale DNS"), and those devices will use their local resolver instead of NextDNS, but you'll also disable the use of MagicDNS on that device.

I'll go ahead and convert this issue into a feature request.

**Comment by anubhavcodes** [comment]
@kelivel Thank you for your answer. This makes sense, and I was able to configure `--accept-dns=false` on those devices. Now they don't show up on nextDNS. 

Just one question, is this setting also available on the appleTV app? This appleTV is at my family's place and I cannot access it, but my family cannot find the option. 

I appreciate this issue being promoted to a feature request. Thanks a lot.

**Comment by agottardo** [comment]
@anubhavcodes DNS Settings will be landing in the tvOS client with the 1.66 update, later this month (see https://github.com/tailscale/tailscale/issues/11809). If you want them sooner, you can already download the beta version from TestFlight.

**Comment by anubhavcodes** [comment]
Perfect, thank you for the update @agottardo .I will wait for 1.66 gladly. Cheers.

**Comment by anubhavcodes** [comment]
Another issue that I have ran into, after setting `--accept-dns=false` on one of my nodes, is that all my existing running docker containers have suddenly stopped resolving dns queries. 

There are some other docker containers running services like syncthing and tailscale is running on host directly. (installed on debian using apt). 

I have already set `--accept-dns=true`, tried using `dns:` in my `docker-compose.yml` files, added a key `dns` in my `/etc/docker/daemon.json` file. I deleted and recreated my docker networks and docker containers, but nothing helps. 

Can this somehow be related to how I changed my `--accept-dns` settings on my host? Any hints that can point in the direct to debug this will be immensely helpful.

**Comment by anubhavcodes** [comment]
@teroshan Thank you for the hint. I have updated the client to 1.66.4 and will now test out if the issue is persisting again. Appreciated 👍🏽

**Comment by croakerbcts** [comment]
@an00bhav , just wanted to confirm if your issue is now resolved...

**Comment by an00bhav** [comment]
@croakerbcts super late to reply back. I can confirm the issue ( dns inside docker ) is no longer existing. All the containers can reach the internet perfectly fine. 

The original issue about having nextDNS only on certain devices using tags, this is still not implemented, and I have learned to live with it :D 

Hope it helps.
