### ISSUE TITLE
Can't rename a machine to the name of a removed machine

### ISSUE THREAD

**Issue by normanr** [tailscale/tailscale#1200]
**Describe the bug**
Old and deleted machines still have machine names that "occupy" the machine namespace.

**To Reproduce**
1. Install android client and configure it
2. Wipe app data
3. Reconfigure client
4. Try and rename the machine in the admin console to remove the `-2` suffix.

**Expected behavior**
I expect to be able to rename "pixel-3-2" to "pixel-3", but instead `Name "pixel-3" is already taken` is shown. My old pixel 3 device is not visible anywhere (because I removed it when I reset the app data).

**Additional context**
Tailscale acct: my-github-account-name [at] gmaildotcom

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_34p01)

**Comment by normanr** [comment]
Yea, I was thinking one work around would be to rename (add a timestamp suffix?) the old machines before deleting them (but that only fixes future deletions, and it might just be easier to adjust the code that checks for name conflicts to ignore deleted machines)

**Comment by DentonGentry** [comment]
I think something fixed this, I've renamed several nodes recently to be the same name as a deleted node.

**Comment by bradfitz** [comment]
Just tested again. Not fixed. I search for "winmox", get exactly one match ("winmoxa"), but can't rename it back to its old name of just "winmox":

<img width="909" alt="Screen Shot 2021-04-19 at 3 26 27 PM" src="https://user-images.githubusercontent.com/2621/115311024-be166c80-a123-11eb-9d36-5f1c4541b6e8.png">

**Comment by DentonGentry** [comment]
There seems to be something that can happen in the state for a deleted node to make it get stuck, but which doesn't always happen.

I have a large number of container machines to delete: container, container-1, container-2, etc. I deleted "container" and have renamed several others to "container" successfully, before deleting them too.

**Comment by normanr** [comment]
Perhaps it depend on how the machine is deleted. Maybe the "Remove" workflow (from the admin UI) works, but some other workflows (maybe reinstalling the Android app?, or deletions that happened before a fix was deployed) leaves behind a hidden conflict that prevents the later renaming.

**Comment by bradfitz** [comment]
It's just bad data in the database from old bugs. We need to do some cleanup.

**Comment by jjo93sa** [comment]
I'd vote for having a "force name change" option. I find myself frequently spinning up and tearing down nodes as I test, for example, Ansible playbooks. It'd be really useful to be able to rename a node called "name-xy" to just plain old "name" even if there is a conflict.

**Comment by sailorfrag** [comment]
Removing devices freed up the names starting... quite a while ago. Today I finished cleaning up old db entries from before that policy changed, so those old names should be available for reuse again.

**Comment by Syzygies** [comment]
I'm still having this problem. I followed the complete uninstall instructions in [Uninstall Tailscale](https://tailscale.com/kb/1069/uninstall/) for each machine that had anything to do with the name in question, to no avail.

I don't understand why a name that doesn't show in current use can't be reused.

What database, where? I'd love to reset it. I'm willing to wipe out my entire network and start over. I'm not willing to change GitHub accounts, and I fear that may be required to shed this database.

**Comment by DentonGentry** [comment]
If you will send the account name or the Tailscale IP address to support@tailscale.com, we can look into it.

**Comment by lkosewsk** [comment]
This problem very much still exists.  I have an open situation with support@tailscale for this, but in the interest of sharing context, the situation was:
- had an AWS instance with hostname 'A'.
- took an AMI snapshot of A.
- attempted to launch a new AWS instance using the snapshot of 'A', let's call it B, because I hadn't thought the consequences through.
- at this point tailscale went crazy saying two machines were trying to register on my tailnet with the same keys (true!).  That was bad news bears.  'A' disappeared from the machines listing.  A new listing for B appeared.  A is totally gone from the tailnet at this point, nothing can find or ping it by hostname.  I did not attempt to try e.g. tailscale ssh to it by IP at this point, sadly, because I am an engineer and not a scientist.
- I terminated B.
- 'A' came back in the admin machines listing with name 'unknown' and now there's no way to either manually set its tailscale name to A (there is already an instance A, instead I will helpfully call it "" for you because *that* is usable), nor for it to automatically pick up hostname A (no errors, but 'unknown' in the tailscale machines listing and no way to refer to it except by IP).

**Comment by tbela99** [comment]
the problem still exist. 
I rename a host on one computer. when I login on a different computer, I have copies of the host created, but disconnected.
This time I found the same host duplicated seven times.

![image](https://user-images.githubusercontent.com/58517/196568949-e35d11b7-679a-4841-a7df-93badf8552a7.png)

**Comment by sailorfrag** [comment]
Can you run `tailscale bugreport` and provide the resulting code or e-mail support@tailscale.com with the name of your tailnet and a general description of what workflow results in this issue? I suspect that you have something different going on.

**Comment by tbela99** [comment]
done
