### ISSUE TITLE
Recent versions of Tailscale on Android will stop running after some time

### ISSUE THREAD

**Issue by gbraad** [tailscale/tailscale#14070]
### What is the issue?

Unlike older versions, like 1.72.0, I am unable to have version 1.76.x run for longer than a few hours. When it is enabled on a phone overnight, or other device, I mostly will find it disconnected in the morning. The same happens on my tablet that had been used in the afternoon, and by nighttime it is not running tailscale anymore.

The applications 'disappears'; so most likely an OOM or other crash. Have not checked logs yet, but downgrading on devices have helped to prevent this behaviour.

I asked people if they also saw this. It seems this is the case:
https://www.reddit.com/r/Tailscale/comments/1gpedi6/recent_versions_of_tailscale_on_android_will_stop/

### Steps to reproduce

Run tailscale on Android for some time or over night

### Are there any recent changes that introduced the issue?

Recent versions did, as 1.72.x does not see this, but all Android devices on 1.76.x do

### OS

Android

### OS version

Have tried on 11, 12, 13, ATV, Tablet, Phone

### Tailscale version

1.76.x

**Comment by agottardo** [comment]
This should have been fixed in v1.76.6. Please attach a bug report identifier or a crash log otherwise we cannot determine the root cause of the issue.

**Comment by gbraad** [comment]
@agottardo there was not a clear crash reported in the app or from the OS itself. Would the function in that case have helped? Is this update already available from the Google Play store or F-Droid? If so, I can test to confirm if this is resolved.

**Comment by agottardo** [comment]
@gbraad 1.76.6 is already available on the Play Store, but it is currently undergoing a phased rollout. You can download the APK yourself from https://pkgs.tailscale.com/stable/#android if you want to avoid waiting.

**Comment by rgabbo** [comment]
I still experience the bug in 1.76.6. The bug identifier is `BUG-71038def4b7852d31441f6faa35417db72ccbec7c638e1047d99523060b5d622-20241122155814Z-960c97cffe0da640` if can be helpful.

**Comment by gbraad** [comment]
While it does not happen for me anymore with 1.76.6.

**Comment by xaralis** [comment]
I'm seeing exactly the same issue with 1.78.3, Android 14 on Motorola Edge 50 Neo. Tailscale set as permanent VPN in networking, battery optimizations disabled. We have two phones, both are affected by this. Very frustrating as we have our smart home stuff behind VPN.

**Comment by agottardo** [comment]
Closing this stale issue as the original crash was fixed. If you hit crashes, open a separate issue **with a stack trace**.
