### ISSUE TITLE
FR: Add Support for ZimaOS

### ISSUE THREAD

**Issue by mikey2toes** [tailscale/tailscale#14172]
### What are you trying to do?

Trying to install Tailscale on ZimaOS
OS=other-linux
VERSION=
PACKAGETYPE=
UNAME=Linux ZimaCube 6.6.48 #1 SMP PREEMPT_DYNAMIC Wed Oct 23 03:11:22 UTC 2024 x86_64 GNU/Linux

NAME="ZimaOS"
BOARD="ZimaCube"
VERSION="v1.2.5"
ID=zimaos
VERSION_ID=1.2.5
PRETTY_NAME="ZimaOS v1.2.5"
CPE_NAME=cpe:2.3:o:icewhale:zimaos:1.2.5:*:development:*:*:*:zimacube:*
VARIANT="ZimaOS ZimaCube"
VARIANT_ID=zimacube
SUPERVISOR_MACHINE=ZimaCube
SUPERVISOR_ARCH=amd64
BUILD_DATE="2024/10/23 09:57:17 UTC"
MANUFACTURER="IceWhale Technology"
MODEL=ZimaCube

### How should we solve this?

Add support for ZimaOS

### What is the impact of not solving this?

Not being able to use Tailscale

**Comment by shayani** [comment]
Me too

**Comment by landiandrea** [comment]
Hi, has this been addressed?

**Comment by mikey2toes** [comment]
Hi yes this has been solved

**Comment by landiandrea** [comment]
Doesn't work for me on zimaboard 2 so I have added a new one:
https://github.com/tailscale/tailscale/issues/18984

**Comment by Erisa** [comment]
> Hi yes this has been solved

@mikey2toes can you please elaborate? This issue is for tracking Tailscale's `install.sh` script support for ZimaOS, and we have no support for ZimaOS in the script yet. Did you find a workaround to run it without the script?

**Comment by mikey2toes** [comment]
> > Hi yes this has been solved
> 
> @mikey2toes can you please elaborate? This issue is for tracking Tailscale's `install.sh` script support for ZimaOS, and we have no support for ZimaOS in the script yet. Did you find a workaround to run it without the script?

There is a docker app that can be used to install it. ZimaOS is Linux based but stripped down for ZimaOS. It's located in the ZimaOS app store. You will need to make sure its set up correctly and it's set as a host network to function.

**Comment by landiandrea** [comment]
@mikey2toes what you are talking about in the zima app store is the container version of tailscale. But that's different from installing it on the host machine. So the issue is not solved @Erisa

**Comment by landiandrea** [comment]
I am specifically trying to install tailscale on the host machine as with the container version I have issues with ipv6. The tailscale support team itself suggested to look at the script to install it on the zimaboard 2 but I don't think they are aware that the script doesn't work. @Erisa

**Comment by Erisa** [comment]
> The tailscale support team itself suggested to look at the script to install it on the zimaboard 2 

Where was that suggested? This issue is the issue tracking adding support for ZimaOS (which of course includes zimaboard 2) in the install script. This issue is open because support is not yet added.

**Comment by landiandrea** [comment]
> > The tailscale support team itself suggested to look at the script to install it on the zimaboard 2
> 
> Where was that suggested? This issue is the issue tracking adding support for ZimaOS (which of course includes zimaboard 2) in the install script. This issue is open because support is not yet added.

It was suggested to me by tailscale support via email

**Comment by mikey2toes** [comment]
> Erisa

No it's not but this is a workaround for being able to use it.

**Comment by mptorz** [comment]
I am also waiting for ZimaOS support

**Comment by cloud1494** [comment]
+1 for me too.
