### ISSUE TITLE
Windows client show up in device list but not in taildrop menu in android

### ISSUE THREAD

**Issue by skywalker478** [tailscale/tailscale#14288]
My windows(v1.76.6), linux (v1.76.6) and android (v1.76.6) client all show up in my android client's device list. But when I try to use taildrop, only the linux clients show up. I've tried reinstalling the android client to no avail.

These screenshots are taken after reinstalling...
![Screenshot_20241203-105852](https://github.com/user-attachments/assets/cb14ba0f-9c0d-4504-b441-b8709d5d6002)
![Screenshot_20241203-105931](https://github.com/user-attachments/assets/f3392df8-d5da-4bc8-b163-a0132e71510f)

**Comment by skywalker478** [comment]
The issue is resolved post update

**Comment by hippy** [comment]
I am running 1.88.3 on my Win11 machine and have this same issue. Desktop PC is showing Connected but it doesn't appear in the list of devices on my phone nor in the list of devices when I use the Share with Tailscale from within Windows. Uninstall/reinstall didn't fix the issue.
