### ISSUE TITLE
tailscale update reports unsupported hardware on Synology DS416

### ISSUE THREAD

**Issue by arneto** [tailscale/tailscale#14673]
### What is the issue?

My DS416 does not update from 1.58.2-1 for a while now when running a script with "tailscale update --yes". Other Synology devices updated instantly.

Curious, I investigated with ssh executing "sudo tailscale update" and got the following output:

`unsupported Synology CPU architecture "alpine4k" (Go arch "arm"), please report a bug at https://github.com/tailscale/tailscale/issues/new/choose`

Running the same command on another Synology shows (obviously already upgraded):
`already running stable version 1.78.1; no update needed`

I need the upgrade to install the server certificate (which is not supported in 1.58 I think)

### Steps to reproduce

Install tailscale on DSM 7.2.2-72806
Create Scheduled Task with "tailscale update --yes"
Run that Scheduled Task

### Are there any recent changes that introduced the issue?

It was a fresh DSM install + fresh TailScale package install

### OS

Synology

### OS version

7.2.2-72806

### Tailscale version

1.58.2-1

### Bug report

BUG-c6f2991f13d31dd05c0657c4eed55ae2e049628af86fdaba54b6685f13a8739e-20250117101448Z-7a41b660aa4f6630

**Comment by arneto** [comment]
I updated the package manually (tailscale-armv7-1.78.1-700078001-dsm7.spk).
I was then able to generate a server certificate.

From ssh, I checked "sudo tailscale update" but that gave the same result as above.

There seems to be something wrong in the packaging of your .spk

**Comment by soxofaan** [comment]
I just installed Tailscale on my Synology and was trying out the `update` feature, but I'm getting same problem here.

Setup: 
> Synology DS416
> DSM 7.1.1-42962 Update 9
> now running: Tailscale version 1.58.2

```
$ sudo tailscale update
unsupported Synology CPU architecture "alpine4k" (Go arch "arm"), please report a bug at https://github.com/tailscale/tailscale/issues/new/choose
```

**Comment by soxofaan** [comment]
Just like @arneto  I now also managed to manually install/update to version 1.88.1
(based on instructions at https://tailscale.com/kb/1131/synology#install-tailscale-on-dsm-manually)

but update still does not work:
```
$ tailscale version
1.88.1
  tailscale commit: 032962f4bc982fe8b6b58df01c33cf2904d07d67
  long version: 1.88.1-t032962f4b-gc5ad3b22f
  other commit: c5ad3b22fdb5813c46501f20144c6b29b61acf54
  go version: go1.25.1

$ sudo tailscale update
Password:
unsupported Synology CPU architecture "alpine4k" (Go arch "arm"), please report a bug at https://github.com/tailscale/tailscale/issues/new/choose
```
