### ISSUE TITLE
[macos] Tailscale unable to resolve DNS hosts on wake

### ISSUE THREAD

**Issue by nickzelei** [tailscale/tailscale#14867]
### What is the issue?

Hey there,

Lately I've noticed that tailscale seems to be breaking DNS resolution. I'm on a M2 Max Macbook.
When I wake up my computer, I'm connected to my wifi, but am unable to browse the web or ping anything. If I ping anything it reports back saying that it's unable to resolve host.

I guess Tailscale takes DNS precedence on my machine? Kinda strange that my computer isn't doing any fallbacks, but unclear how all of that works.

The fix it I typically disable tailscale, which immediately fixes the problem. Upon re-enabling tailscale, my network also continues to function on my laptop.

I saw in the tailscale settings my mac is configured to use tailscale as a dns server, which I will disable I think because this has become a persistent issue.

### Steps to reproduce

It's intermittent but:

1. leave tailscale enabled on macbook
2. close laptop to go to sleep
3. ??
4. open laptop
5. try to browse internet or ping a website via terminal

### OS

macOS

### OS version

macOS Sequoia 15.1.1

### Tailscale version

1.76.6 Mac Store Variant

### Bug report

BUG-04a65461f836ece559ee358ceaacc8a9909a30f44d298f76966560714066a0f4-20250221165947Z-e374a98028f70bb5

**Comment by nickoneill** [comment]
Can you attempt this same thing with the latest 1.80 version? Also please provide a bug report, it's available in the menu under Settings > About

**Comment by bslatyer** [comment]
I would also update your macOS from 15.1.1 to 15.3.1.

**Comment by nickzelei** [comment]
I added a bug report. However I've since updated to 1.80.2 and am on the latest maccos 15.3.1 and haven't experienced this issue since. I'm assuming it is now fixed.

**Comment by nickzelei** [comment]
BUG-04a65461f836ece559ee358ceaacc8a9909a30f44d298f76966560714066a0f4-20250221181223Z-20504761619c0495

[tailscale-mac-diagnostics-42E63C0A-E06F-4003-AB8F-CE5A0D20BC58.tar.gz](https://github.com/user-attachments/files/18913596/tailscale-mac-diagnostics-42E63C0A-E06F-4003-AB8F-CE5A0D20BC58.tar.gz)

**Comment by nickzelei** [comment]
Okay, had my laptop asleep for about an hour. Came back and was unable to connect to the internet until I disabled tailscale.

Here is the bug id during that time before I disabled tailscale: BUG-04a65461f836ece559ee358ceaacc8a9909a30f44d298f76966560714066a0f4-20250221181223Z-20504761619c0495

Attached are the extended logs:
[tailscale-mac-diagnostics-95587654-5390-4902-8B10-C149707F371F.tar.gz](https://github.com/user-attachments/files/18915776/tailscale-mac-diagnostics-95587654-5390-4902-8B10-C149707F371F.tar.gz)

**Comment by colinator19** [comment]
I am having a similar issue when waking the Mac however connectivity seems to start working after about 10/15 seconds.
I have the same issue on my iPhone as well so it is probably Apple related somehow.

In my case, I tested that I can ping devices in my Tailscale network directly after waking the device meaning the network connectivity of Tailscale appears to be working, including pinging 100.100.100.100.
However when I try to do a DNS lookup by pinging google.com -or- perform a "dig google.com", the terminal seems to hang for a moment (about 10 seconds) and then either it times out or I eventually do get the correct results.
While I can ping 100.100.100.100 immediately after waking, DNS requests seems to take a while before it starts working after waking up.

As long as the device remains awake, the issue does not return until it has gone to standby/sleep again and wakes.

**Comment by jimmybrancaccio** [comment]
A customer in TSS-54115 has also reported this issue. Included in that are bug reports and a macOS configuration report.

**Comment by barnstar** [comment]
We've pushed a potential fix for this to macOS, iOS and tvOS unstable v1.81.135.

**Comment by colinator19** [comment]
> We've pushed a potential fix for this to macOS, iOS and tvOS unstable v1.81.135.

I have tested this release on macOS and it seems my issues are resolved. I will keep monitoring it but for now it looks good :-)

Any idea when this release is expected to go main?
I take we cannot do any testing on iOS yet?

**Comment by barnstar** [comment]
This should be resolved as of 1.82.0

**Comment by jaredneedell** [comment]
This is still happening on 1.84.0

**Comment by sakirma** [comment]
Still is also happening for me on 1.84.1

**Comment by nickoneill** [comment]
Can folks who are still experiencing this on the latest versions post a bug report after experiencing this issue so we can take a closer look.

**Comment by luckman212** [comment]
I am on 1.84.1 and still experiencing it. What sort of debug info do you need to help track it down?

**Comment by nickoneill** [comment]
@luckman212 a bug report string, from Settings > About > Report an issue... Please do this after you see the issue occur.

**Comment by luckman212** [comment]
@nickoneill Happening now...

```
BUG-4cc4b63936081243f62efb277eb4d9d9fc653bde44fde34b5b7fb652de4ff643-20250609235825Z-cdbf6a6dcc5e52cd
```

![Image](https://github.com/user-attachments/assets/cc5ad2af-3d34-4e53-930a-0704ad6c8a68)

I also collected an "extended" Configuration Report and have it ready to share if you provide me a way to do so securely...

**Comment by luckman212** [comment]
Another BUG ID:

```
BUG-4cc4b63936081243f62efb277eb4d9d9fc653bde44fde34b5b7fb652de4ff643-20250612004957Z-f843c7ce821e0bc4
```
I collected another extended report. I have 2 now. Let me know where to send them please @nickoneill - thanks 🙏

**Comment by nickoneill** [comment]
here is good, we will take a look. Thanks @luckman212

**Comment by luckman212** [comment]
@nickoneill But the screen says those diags contain sensitive information. Is there a way to send it privately?

**Comment by nickoneill** [comment]
I see, you're talking about the sysdiagnose files. Don't worry about that for now, we'll look into this based on the bug report id for the moment.

**Comment by luckman212** [comment]
Today I was in a hotel on their public WiFi and experienced this again, so here's another bug ID in case it's any different vs the previous reports due to the topology

```
BUG-4cc4b63936081243f62efb277eb4d9d9fc653bde44fde34b5b7fb652de4ff643-20250615184503Z-c638eacd8e80d281
```
I collected another extended sysdiagnose as well (which I have been saving in case they are requested) bringing the count to 3.

**Comment by luckman212** [comment]
Until this issue is tracked down, is there any way to trigger the same thing that toggling the menubar switch off and back on does, using the commandline?

<img width=439 src=https://github.com/user-attachments/assets/4cf90720-f121-4b69-9462-2dba283045fa>

**Comment by luckman212** [comment]
I monkeyed around a bit, and believe I came up with a way to roughly approximate toggling that GUI knob via shell on macOS (call `_ts_bounce` after sourcing the file below or adding the functions to your profile):

```bash
#!/usr/bin/env bash

_ts_get_vpn_guid() {
  local guid
  guid=$(scutil --nc list | awk '/io.tailscale.ipn.mac/ && $3 ~ /[A-F0-9]{8}/ { print $3 }')
  if [[ -n $guid ]]; then
    export TS_GUID=$guid
    return 0
  fi
  return 1
}

_ts_stop() {
  local cnt STATUS
  _ts_get_vpn_guid || return 1
  cnt=5
  while (( cnt-- )); do
    scutil --nc stop "$TS_GUID"
    read -r STATUS < <(scutil --nc status "$TS_GUID")
    if [[ $STATUS == "Disconnected" ]]; then
      break
    fi
    sleep 1
  done
  [[ $STATUS == "Disconnected" ]]
}

_ts_start() {
  local STATUS
  _ts_get_vpn_guid || return 1
  tailscale up
  read -r STATUS < <(scutil --nc status "$TS_GUID")
  [[ $STATUS == "Connected" ]]
}

_ts_bounce() {
  _ts_stop
  sleep 2
  _ts_start
}
```

@nickoneill I just posted a large amount of DNS-related debug info over at https://github.com/tailscale/tailscale/issues/15389#issuecomment-3042830515 if you wouldn't mind taking a look there when you can.

**Comment by agent0022** [comment]
I'm experiencing the same issue on the latest version of Tailscale (1.88.3) and macOS. Almost every time I put my MacBook to sleep while Tailscale is active, the connection breaks upon waking. In some cases, even quitting the app doesn’t resolve it and I have to restart the entire laptop.

**Comment by timball** [comment]
This just started happening to me as well. boucing tailscale on/off from the apple network settings is the only way to temporarily solve symptoms

**Comment by luckman212** [comment]
**_What specific DNS lookups or tests are being performed by Tailscale in order to determine when to show the healthcheck warning?_** I've asked this several times here on GH issues as well as via private communications, and never received an answer. If we can at least know this then I can do some more troubleshooting as to why those lookups might be failing. It seems to be something quite rare but very persistent about our network configuration.

https://github.com/tailscale/tailscale/blob/d68513b0dbe352ca03165be35ebc5edd626ac83e/net/dns/resolver/forwarder.go#L964-L969

**Comment by mmenanno** [comment]
For the past few days this happens every single time I come back to my computer. For some reason toggling the enable switch didn't work for me, to fix it I have to fully quit the tailscale app and restart it and everything goes back to normal. 

I'm guessing based on the clustering of reports here that something in a recent version made things worse. Is there anything we can try to help debug and get this fixed?

I tried used `tailscale` from the terminal while it was happening and `tailscale status`, `tailscale dns status`, `tailscale bugreport`, and `tailscale down` all hung indefinitely until I restart the app.

After the app restart `tailscale status` fell back to:
`2025/10/30 19:54:04 failed to connect to local Tailscale service; is Tailscale running?`

`tailscale dns status` fell back to:
`2025/10/30 19:54:04 Get "http://local-tailscaled.sock/localapi/v0/status": EOF`

`tailscale bugreport` fell back to:
`2025/10/30 19:54:04 Post "http://local-tailscaled.sock/localapi/v0/bugreport?": EOF`

and `tailscale down` fell back to:
`2025/10/30 19:54:04 error fetching current status: Get "http://local-tailscaled.sock/localapi/v0/status": EOF`

Not sure if any of that is helpful. Let me know if there is anything else I can debug next time it happens, cause I'm having it happen multiple times a day so I have plenty of opportunities.

**Comment by tylerburleigh** [comment]
I'm also experiencing this issue with the current version of Tailscale. 

Restarting tailscale did not solve the issue.

Removing the VPN configuration only partially restored my network access. 

I had to reboot my Mac to get things working again.

**Comment by timball** [comment]
Since last week when I reported the issue Tailscale has done two rounds of updates. Since the upgrade to 1.90.6 i have yet to experience the DNS issue. 🤞 🤞 🤞

**Comment by luckman212** [comment]
@timball I'm glad to hear that, now hopefully #15389 will get some attention...

**Comment by tylerburleigh** [comment]
I discovered today that (at least in my case) it occurs not only when the system wakes from sleep, but when the WiFi / network connection is toggled off and back on.

I will give 1.90.6 a shot.

**Comment by tylerburleigh** [comment]
Same issue with 1.90.6, but I was able to fix the issue as it happens.

[EDIT]

This is what worked for me on MacOS:

- Install the standalone variant
- In Tailscale settings enable the CLI integration
- When the issue occurs, `sudo tailscale down` then `sudo tailscale up`

For some reason, the off/on switch on the Tailscale GUI **_does not_** work for me (I cannot toggle Tailscale off using that switch), so the CLI `up`/`down` command was really key.

**Comment by switz** [comment]
this happens to me quite often. `sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder` fixes it temporarily

**Comment by danielefranceschi** [comment]
I don't know if relates, but my Mac cannot resolve machines on my ts.net domain, while the linux machines do resolve the Mac.

`scutil --dns` correctly lists the TS resolver at the second place with the correct ts.net domain.

Restarting, rebooting, flushing DNS cache, nothing works.

**Comment by nickoneill** [comment]
Hi @danielefranceschi, please reach out to support, this doesn't seem like the same bug described in this issue.
