### ISSUE TITLE
Android app showing duplicate node key after recent update

### ISSUE THREAD

**Issue by cgcomer** [tailscale/tailscale#16366]
### What is the issue?

Admin Console shows Duplicate Node key on Phone device. 
Suspected issue with unused FireTV device. Removed. No Change.
Removed Android phone (Pixel 7 Pro) from tailnet. Uninstalled app. Reinstalled. Connected to tailnet. Connects fine, about 5 seconds later Admin Console shows "Duplicate Node key" again.
Repeated Uninstall, reinstall. Same results.

No other Android based devices on Tailnet.

No other device on tailnet shows same error.

### Steps to reproduce

Install most recent version with Taildrop support on Android 15 device. Error should appear within 10 seconds.

### Are there any recent changes that introduced the issue?

This is the update that added Taildrop to Android and prompts to select a folder for Taildrop at install.

### OS

Android

### OS version

15

### Tailscale version

1.84.1

### Other software

Proton VPN is installed, but not running while Tailscale is.

**Comment by vadviktor** [comment]
I can confirm. I've a phone and a tablet now. Here's my timeline:

1. Installed TS on phone when it was still Android 14.
2. Upgraded phone to Android 15.
3. No issues.
4. Got a new tablet and cloned the phone settings. ❗ 
5. Installed TS on tablet with Android 15.
6. I get "Duplicate node key" on admin panel. Most likely because of the cloned settings, keys.
7. Reinstalled TS on BOTH devices as per [the documentation troubleshooting](https://tailscale.com/kb/1023/troubleshooting?q=%22Duplicate+node+key%22#multiple-devices-have-the-same-100x-ip-address).
8. Now I get "Duplicate node key" on both of them.

Looking at the "Node key" attribute for both devices, they are not the same.

Could it be that the cloning of the phone's key messed things up? 🤔

**Comment by cgcomer** [comment]
In my case I have never cloned my device or its settings. So I don't know what is going on.  It doesn't seem to affect functionality as far as I can tell.  
Up until the recent update the app had issues with communicating with the coordination server.  It would randomly lose connection with coordination server about once every 4-8 hours (seat of the pants estimate, I haven't actually measured it).  And it was almost guaranteed to do so when navigating a transition between a cellular and Wi-Fi signal.

In fact I just checked and the app is now showing "Health warnings: Out of sync: Unable to connect to the Tailscale coordination server to synchronize the state of your tailnet.  Peer reachability might degrade over time." (Currently on work Wi-Fi) This has been a common error as well. But it still shows as connected in the Admin Console. I can usually temporarily fix that particular error by disconnecting, closing the app, then reopening and connecting again.  This time I am getting a new error upon reconnect "DNS unavailable: Tailscale can't reach the configured DNS servers. Internet connectivity may be affected."

Okay. I might have inadvertently fixed the "Duplicate Node Key" issue while trying to fix the most recent app error. I did the following:

Turned off wifi.
Disconnected.
Closed app.
Phone was still showing an active VPN in top right, so I went to VPN setting in the phone and pressed forget VPN.
Reopened app.
Connected again.  Phone asked if I wanted to add a VPN as if I had just installed the Tailscale app. Pressed yes (or add whichever it was).
Phone reconnected with no errors.
Admin console now, no longer show the Duplicate Node Key.
This condition has now persisted for at least the last 5-7 minutes.

If everything holds as is for a couple of hours, I'll notify.

**Comment by Sammy-T** [comment]
> Okay. I might have inadvertently fixed the "Duplicate Node Key" issue while trying to fix the most recent app error. I did the following:
> 
> Turned off wifi. 
> Disconnected.
> Closed app.
> Phone was still showing an active VPN in top right, so I went to VPN setting in the phone and pressed forget VPN. 
> Reopened app. 
> Connected again.
> Phone asked if I wanted to add a VPN as if I had just installed the Tailscale app. Pressed yes (or add whichever it was).
> Phone reconnected with no errors. Admin console now, no longer show the Duplicate Node Key. This condition has now persisted for at least the last 5-7 minutes.

I gave this a try but it didn't work for me. Also on Android 15.

**Comment by ronaldvg99** [comment]
I am also getting two android devices n the admin console saying they have duplicate node keys. 

Both of them were installed with the new tailscale client that asks for the drop location (this was new for me). Deleting and reinstalling does not do anything, the warning about the duplicate node keeps coming back, but I see no problem in the functionality of the devices.

**Comment by s-gregorini003** [comment]
> In my case I have never cloned my device or its settings. So I don't know what is going on.  It doesn't seem to affect functionality as far as I can tell.  
> Up until the recent update the app had issues with communicating with the coordination server.  It would randomly lose connection with coordination server about once every 4-8 hours (seat of the pants estimate, I haven't actually measured it).  And it was almost guaranteed to do so when navigating a transition between a cellular and Wi-Fi signal.
> 
> In fact I just checked and the app is now showing "Health warnings: Out of sync: Unable to connect to the Tailscale coordination server to synchronize the state of your tailnet.  Peer reachability might degrade over time." (Currently on work Wi-Fi) This has been a common error as well. But it still shows as connected in the Admin Console. I can usually temporarily fix that particular error by disconnecting, closing the app, then reopening and connecting again.  This time I am getting a new error upon reconnect "DNS unavailable: Tailscale can't reach the configured DNS servers. Internet connectivity may be affected."
> 
> Okay. I might have inadvertently fixed the "Duplicate Node Key" issue while trying to fix the most recent app error. I did the following:
> 
> Turned off wifi.
> Disconnected.
> Closed app.
> Phone was still showing an active VPN in top right, so I went to VPN setting in the phone and pressed forget VPN.
> Reopened app.
> Connected again.  Phone asked if I wanted to add a VPN as if I had just installed the Tailscale app. Pressed yes (or add whichever it was).
> Phone reconnected with no errors.
> Admin console now, no longer show the Duplicate Node Key.
> This condition has now persisted for at least the last 5-7 minutes.
> 
> If everything holds as is for a couple of hours, I'll notify.

This seems to have fixed the issue for me. Same situation: never cloned my Google Pixel 7, installed the TS update yesterday and today I had the duplicate key error. Following these steps made it go away.

**Comment by vadviktor** [comment]
My devices having this issues are on v1.84.1, and the ones still do not are on v1.82.4.

I tried recreating the VPN from scratch, but does not make the issue go away.

**Comment by vadviktor** [comment]
I can confirm that the issue lies in the versions above the v1.82.4. I've downloaded the 1.82.4 APK from the original releases (https://github.com/tailscale/tailscale-android/releases) and that version still has no such issues.

**Comment by Paul-Reed** [comment]
I'm on v1.84.1 using Android 15, I have the same issue.
Followed the guide by removing my phone from the tailnet, completely uninstalling the Tailscale app, rebooted & re installed Tailscale again.
The warning appeared again 5 minutes later.
Never duplicated my phone.

**Comment by wischi-chr** [comment]
Today I tried tailscale for the first time so I first thought I did something wrong. Hit the exact same issue, reinstalled but it didn't fix it. Windows and Linux work fine, I can even ping the Android phone (Android 14, Pixel 5, Tailscale 1.84.1)

**Comment by jancyril** [comment]
> In my case I have never cloned my device or its settings. So I don't know what is going on. It doesn't seem to affect functionality as far as I can tell. Up until the recent update the app had issues with communicating with the coordination server. It would randomly lose connection with coordination server about once every 4-8 hours (seat of the pants estimate, I haven't actually measured it). And it was almost guaranteed to do so when navigating a transition between a cellular and Wi-Fi signal.
> 
> In fact I just checked and the app is now showing "Health warnings: Out of sync: Unable to connect to the Tailscale coordination server to synchronize the state of your tailnet. Peer reachability might degrade over time." (Currently on work Wi-Fi) This has been a common error as well. But it still shows as connected in the Admin Console. I can usually temporarily fix that particular error by disconnecting, closing the app, then reopening and connecting again. This time I am getting a new error upon reconnect "DNS unavailable: Tailscale can't reach the configured DNS servers. Internet connectivity may be affected."
> 
> Okay. I might have inadvertently fixed the "Duplicate Node Key" issue while trying to fix the most recent app error. I did the following:
> 
> Turned off wifi. Disconnected. Closed app. Phone was still showing an active VPN in top right, so I went to VPN setting in the phone and pressed forget VPN. Reopened app. Connected again. Phone asked if I wanted to add a VPN as if I had just installed the Tailscale app. Pressed yes (or add whichever it was). Phone reconnected with no errors. Admin console now, no longer show the Duplicate Node Key. This condition has now persisted for at least the last 5-7 minutes.
> 
> If everything holds as is for a couple of hours, I'll notify.

Had the same problem, I tried to uninstall and install it again for like 3x but same thing happens, found this comment and tried it and it worked for me.

**Comment by cgcomer** [comment]
So the Duplicate Node Key issue has not reappeared in over 20 hours. So I'll consider that issue fixed. Why it happened in the first place is a mystery.  Best I can tell after the update the app attempted to reprovision the node key, resulting in the coordination server interpreting it as two devices attempting to use the same key.  A developer will need to look into this.

The other issues regarding degrading connection with the coordination server over time is more of an annoyance than anything. I'm curious if it has something to do with the way that Pixel phones on Google Fi (which is my carrier) constantly look for and transition to the strongest signal regardless of network carrier.  Around here Google Fi can use T-Mobile and US Cellular.  Add in trying to maintain a VPN connection, and transition between Wi-Fi and cellular signals results in a lost connection. Again a developer will better insight here.

**Comment by cgcomer** [comment]
For those that reinstalling didn't work: Check to make sure that the VPN connection is closed.  
That was the issue I ran into. Even after closing the app the VPN connection to the tailnet was still in place. I had to go into the VPN settings, Press the Gear icon, then select Forget VPN. Only then did the Duplicate Node Key warning close.

**Comment by vadviktor** [comment]
In my case, only going back to the previous release helped. There must be something unique to my case 🤔 

I wish the devs would look into this. I'm happy to share logs or whatever they'd need to fix this. 🙏

**Comment by ronaldvg99** [comment]
> In my case, only going back to the previous release helped. There must be something unique to my case 🤔
> 
> I wish the devs would look into this. I'm happy to share logs or whatever they'd need to fix this. 🙏

Not really unique to you. I had a phone and a tablet with the Duplicate node. Phone is solved, but whatever I do with the tablet, the message keeps returning. 

When I delete the app and the VPN from the device, the message goes away. Then I delete the device from the admin console and reinstall the app on the tablet and the message is back.

**Comment by tofalck** [comment]
Same problem 👍

**Comment by kevin201** [comment]
After updating to 1.84.1 I noticed the "Duplicate" message in the admin console. Disconnecting/reconnecting from the tailnet on the Android (12) device removed it.

**Comment by ronaldvg99** [comment]
> After updating to 1.84.1 I noticed the "Duplicate" message in the admin console. Disconnecting/reconnecting from the tailnet on the Android (12) device removed it.

For me this action removed it for about 1 minute. Again, the android phone was solved immediately after reinstall/vpn delete, the tablet not which I find strange. I also never clone hardware or put settings back from an old phone/tablet.

**Comment by vadviktor** [comment]
As I mentioned, I've downloaded the previous version of the app on both phone and tablet and they worked fine. Now, the auto-update arrived, back to the new version and both devices show the Duplicate node key message in the dashboard. I hope they will still be able to communicate over the network 🤞 😥

**Comment by pablojrl123** [comment]
Same here, Android phone and tablet both on Tailscale 1.84.1.
But I believe this may be simply an error in the admin panel. If you actually click the device on the dashboard, and scroll down to "Machine Details" you'll see that the node keys listed are indeed different.

**Comment by tofalck** [comment]
@pablojrl123 You could be right here. 

The error is gone on my account. 

On the phone with the error, I did disconnect, removed VPN, removed phone from account, reconnected but it didn't resolve it immediately. 

But it's possible that this may have caused account changes to propagate in the backend some time during the last couple of days that has resolved the issue. 

Hard to tell... 

Eventually consistent systems are tough cookies to bake 😅

**Comment by vadviktor** [comment]
I've got an update here: after a day or so my tablet does not show this issue, but my phone still does.

I've tested the connectivity with `ping`. The major issue with the phone having this "DNK" issue results in being not visible to the other devices 🤯 (_does not respond to ping_), BUT it can see (_ping_) any other devices. I used the TS IP addresses to ping one another.

_Thankfully I do not have a particular need ATM to access anything on my phone from another device._ 😅

**Comment by leonstroschein** [comment]
Same issue with a new install on android. No other devices have the same node key. I've tried both Auth key and normal google login, same result.

**Comment by ageisen2000** [comment]
new install for me, im brand new to tailscale. No keys are duplicated but im getting this error.

**Comment by abrah-ml** [comment]
> new install for me, im brand new to tailscale. No keys are duplicated but im getting this error.

same thing for me

**Comment by Skittishly** [comment]
I get this error on Android 15 too, but only after I've set the taildrop directory. (1.84.1)

**Comment by ageisen2000** [comment]
yes, mine showed up fine until i added taildrop directory, then the messagebox prompt shows up again right afterwards and then the admin page starts showing duplicate key

**Comment by whitsunday888** [comment]
I had the same issue today. Android 14 phone showing duplicate key on admin screen. Reinstall/disconnect/clean didn't work. Turning off the phone's Proton VPN didn't work but restarting the phone and not starting the VPN seems to have solved it for the moment. Thanks to whomever suggested this! --- This problem arose immediately after TS requested I pick a new Taildrop folder on the Android 14 phone. This is a great idea but perhaps the feature needs a bit of debugging???

**Comment by chrislongros** [comment]
Had the same problem but inactivating and activating the device removed the duplicate node key warning.

**Comment by vadviktor** [comment]
Interesting 🤔 I also restarted all the Android devices after the newest version was installed (and they got this error message on the TS dashboard). Funny enough, none has this message anymore. Weird.

**Comment by vem1965** [comment]
Does appear to be connected to choosing a directory for me. I uninstalled and didn't choose a directory after re-installing (just hit back arrow until I got to main screen).  No warning on admin screen.  However, if I do a refresh on the admin screen (using Chrome on Windows 10),  I see the warning flicker for a split second before going a way.

**Comment by exlumine** [comment]
I installed Tailscale on Android 14 and Home Assistant, and had the same issue.

After uninstalling TS  from Android, deleting the machine from TS, and reinstalling it on Android without providing a Taildrop folder, the error is gone.

**Comment by InnerSphere** [comment]
> Okay. I might have inadvertently fixed the "Duplicate Node Key" issue while trying to fix the most recent app error. I did the following:
> 
> Turned off wifi. Disconnected. Closed app. Phone was still showing an active VPN in top right, so I went to VPN setting in the phone and pressed forget VPN. Reopened app. Connected again. Phone asked if I wanted to add a VPN as if I had just installed the Tailscale app. Pressed yes (or add whichever it was). Phone reconnected with no errors. Admin console now, no longer show the Duplicate Node Key. This condition has now persisted for at least the last 5-7 minutes.

worked for me in android 15 Samsung. never cloned my phone but happened after I logged back into the app.

settings > connections > more connection settings > VPN > delete tailscale vpn

**Comment by exlumine** [comment]
> I installed Tailscale on Android 14 and Home Assistant, and had the same issue.
> 
> After uninstalling TS from Android, deleting the machine from TS, and reinstalling it on Android without providing a Taildrop folder, the error is gone.

... however, not choosing a folder resulted in TS app not connecting any longer from Android 14. That is, the app slider would switch to off automatically if no folder was chosen.

**Comment by cowwoc** [comment]
The Android implementation is definitely buggy. I have repeatedly got into a bad state where the Android notification says that I am connected (and the key/vpn icon is present at the top) but when I run the Tailscale app it says I am disconnected and refuses to connect.

On the flip side, I have also run into a situation where Tailscale says I am disconnected but the key/vpn icon in the top-right corner is present and I needed to go into Connections -> More connection settings -> VPN  and manually disconnect the VPN.

These issues are intermittent and I have not been able to figure out repro steps for them.

I suspect that once they fix those bugs, the duplicate node key issue will go away.

**Comment by reelfunky** [comment]
> > Okay. I might have inadvertently fixed the "Duplicate Node Key" issue while trying to fix the most recent app error. I did the following:
> > Turned off wifi.
> > Disconnected.
> > Closed app.
> > Phone was still showing an active VPN in top right, so I went to VPN setting in the phone and pressed forget VPN.
> > Reopened app.
> > Connected again.
> > Phone asked if I wanted to add a VPN as if I had just installed the Tailscale app. Pressed yes (or add whichever it was).
> > Phone reconnected with no errors. Admin console now, no longer show the Duplicate Node Key. This condition has now persisted for at least the last 5-7 minutes.
> 
> I gave this a try but it didn't work for me. Also on Android 15.

Well, it worked for me, not sure why this works but it did

**Comment by RalphAardenburg** [comment]
Same issue here on fairphone 5 with android 14.
i can ping my synology nas from the phone but cannot ping the phone from the nas.
tried uninstalling, forget vpn, remove app data and cache, rebooting the phone, the error keeps coming back.

**Comment by DaHronos** [comment]
Hi, I have the same problem on 2 of my 3 Android devices.  All three of them are running TS 1.84.1.
The one that doesn't present the problem is running Android 16.  The other two, one running Android 15 and the other Android 13, both exhibit the issue.
On the Android 13 device, the error appeared after the TS Client asked me to pick a folder for TailDrop and I choose one.

**Comment by 0-a-9-5-6** [comment]
It's probably an ignoreable message, because the TS IPs are completely different, so the "duplicate" is not even accurate.
But it is a bug that should be fixed.

**Comment by Dirty-Racoon** [comment]
> In my case I have never cloned my device or its settings. So I don't know what is going on. It doesn't seem to affect functionality as far as I can tell. Up until the recent update the app had issues with communicating with the coordination server. It would randomly lose connection with coordination server about once every 4-8 hours (seat of the pants estimate, I haven't actually measured it). And it was almost guaranteed to do so when navigating a transition between a cellular and Wi-Fi signal.
> 
> In fact I just checked and the app is now showing "Health warnings: Out of sync: Unable to connect to the Tailscale coordination server to synchronize the state of your tailnet. Peer reachability might degrade over time." (Currently on work Wi-Fi) This has been a common error as well. But it still shows as connected in the Admin Console. I can usually temporarily fix that particular error by disconnecting, closing the app, then reopening and connecting again. This time I am getting a new error upon reconnect "DNS unavailable: Tailscale can't reach the configured DNS servers. Internet connectivity may be affected."
> 
> Okay. I might have inadvertently fixed the "Duplicate Node Key" issue while trying to fix the most recent app error. I did the following:
> 
> Turned off wifi. Disconnected. Closed app. Phone was still showing an active VPN in top right, so I went to VPN setting in the phone and pressed forget VPN. Reopened app. Connected again. Phone asked if I wanted to add a VPN as if I had just installed the Tailscale app. Pressed yes (or add whichever it was). Phone reconnected with no errors. Admin console now, no longer show the Duplicate Node Key. This condition has now persisted for at least the last 5-7 minutes.
> 
> If everything holds as is for a couple of hours, I'll notify.

I appreciate you taking the time to post that. I can confirm your solution worked. It was the vpn profile that needed to be deleted and honestly, i wasnt even close to thinking of that.

**Comment by DaHronos** [comment]
As a follow up, the error just disappeared from both devices, without any intervention on my part... so IDK xD

**Comment by tiesmaster** [comment]
I've also tried reinstalling a couple of times, but to no avail. However, **not** setting the taildrop dir prevents the issue from happening 🤷‍♂️ 

Hat tip to this linkback [reddit thread](https://www.reddit.com/r/Tailscale/comments/1lo3s1d/comment/n1bi1of/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

**Comment by Sharkou-net** [comment]
Same problem here. Last version of tailscale for android installed from the Play Store (1.84.1).
If I choose a Tailscale directory, I get the Duplicate node error.
If I don't pick a directory by going back when asked, it work as intended.

**Comment by adrydale** [comment]
> Same problem here. Last version of tailscale for android installed from the Play Store (1.84.1). If I choose a Tailscale directory, I get the Duplicate node error. If I don't pick a directory by going back when asked, it work as intended.

This worked for me (v1.84.1). I just reinstalled then cancelled/backed out of the directory selection for Taildrop and the node doesn't have a duplicate key error anymore. On app open it does continue to prompt to select a directory but you can still back out. A little annoying so would be nice to have a fix.

**Comment by Piore92** [comment]
> I installed Tailscale on Android 14 and Home Assistant, and had the same issue.
> 
> After uninstalling TS from Android, deleting the machine from TS, and reinstalling it on Android without providing a Taildrop folder, the error is gone.

I confirm. I had to find directory, approve it and then decline approval. (Android 13)

**Comment by markandrewj** [comment]
I am observing this same issue currently in Android 15.

**Comment by philzulli** [comment]
I love Tailscale on my PC and laptop, but what is the status of the Android duplicate key issue being resolved so it works as intended without the folder workaround? Can we look forward to an answer soon?

**Comment by Dirty-Racoon** [comment]
> I love Tailscale on my PC and laptop, but what is the status of the Android duplicate key issue being resolved so it works as intended without the folder workaround? Can we look forward to an answer soon?

It seems if you delete your VPN profile in Android it resolves it. It did for me and a few others anyway. It's still just an odd work around or bandaid but small price to pay for such great software

**Comment by nickoneill** [comment]
Hi all, this was due to a taildrop directory picker change we made in 1.84. It will be resolved with the new behavior in 1.86 which no longer asks you to pick a taildrop directory until you need to receive a file with taildrop.

**Comment by Generator** [comment]
> Hi all, this was due to a taildrop directory picker change we made in 1.84. It will be resolved with the new behavior in 1.86 which no longer asks you to pick a taildrop directory until you need to receive a file with taildrop.

right, today i open the app keep asking for a taildrop directory, after setting the directory short after started having this issue.   
Is connected using relay and duplicated node key.

Followed the steps from @cgcomer and looks to be working fine for now

**Comment by philzulli** [comment]
Thanks, I have been able to use it on Android with the workaround so many suggested; thanks to all.
Tailscale is the solution I searched for, it's awesome. Looking forward to v.1.86! Is there an anticipated time frame for that?

**Comment by paddylandau** [comment]
Adding my voice to this.

It happened to me on both of my Android phones. The one phone (Pixel 2XL) was quickly fixed by the [above solution](https://github.com/tailscale/tailscale/issues/16366#issuecomment-3001507589) from @cgcomer 

Unfortunately, with my second phone (XGODY X32), when I get to the step "Connected again", the Tailscale app freezes. I've tried several attempts including force-stop, clearing the data, removing the connection from the Machines Admin, etc., but without managing to eliminate the "Duplicate node" message.

I'll just leave the "Duplicate message" there for now.

Let's hope that the promised version 1.86 will solve this.

**Comment by pietricello** [comment]
I installed just yesterday TS and  i have the same issue: The web admin console shows the device with a “duplicate node key” error after about 1 minutes after connection. I noticed this happens when i simply try to browse internet.
Steps already tried (none worked):

1. **App-level reset:**  
   - Logged out from Tailscale app.
   - Cleared app data & cache from Android settings.
   - Uninstalled the app completely.

2. **Admin-side cleanup:**  
   - Removed the device from Tailscale web admin (waited several minutes before re-login).
   - Refreshed and ensured the device no longer appears (even grayed out).

3. **Full “clean” reinstall attempt:**  
   - Rebooted the phone.
   - Reinstalled Tailscale from Google Play Store.
   - Logged in from scratch (no password manager, no autofill, no browser history).

4. **Network tests:**  
   - Tried on both WiFi and mobile data
   - Used default system DNS (no NextDNS/AdGuard/other custom DNS).

What i noticed also: sometimes despite the error in admin consolle (web gui) phone is able to connect LAN but no dns is availabe. Forcing using phone dns it seems to work (at least in 1/2 tests).

Every time, device appears for a few seconds in Tailscale admin, then “duplicate node key” pops up and device goes offline.
No “key clone” or device image has ever been made.

My test started with an updated Android 15 Samsung Flip 6 never used with Tailscale before. 

On top of this i also tried with a brand new Pixel 9, Android  never used with Tailscale before and issue is exactly the same.

I also tried same process on an iPhone (iOS 18.5) — works instantly, never gets “duplicate node key”.
Same as for Windows 11 24H2  and Mac OSX 15.5 

At this point, It appears to be a serious bug in the Android app (or backend), not related to user error, device clone or restore.

I gave up for now, on my Android devices.

**Comment by Misza13** [comment]
> Hi all, this was due to a taildrop directory picker change we made in 1.84. It will be resolved with the new behavior in 1.86 which no longer asks you to pick a taildrop directory until you need to receive a file with taildrop.

Yeah, the directory picker interrupting my usage of the app (I kept refusing to pick a directory) was annoying since who needs Taildrop if there's Syncthing. It seems that once I caved in, the problem appeared. Completely clearing app data and even reinstalling didn't help.

The error is additionally confusing since there is no other device on the network with the same error, so it's a duplicate of what, exactly?

**Comment by paddylandau** [comment]
> It seems that once I caved in, the problem appeared.

Thank you, because this solved my problem — resetting, and then refusing to pick a directory.

Of course, that does introduce a new irritation every time I open the app and again when I close it, but I'll live with it until 1.86.

**Comment by gbraad** [comment]
Have the same issue on two Samsung devices, both running different versions of Android/models. Never seen this happen before. Used the current latest Play store version of Tailscale: 1.84.1...

**Comment by NovaViper** [comment]
I factory retested my Motorola 5G Stylus 2024 and reinstalled TS and the issue occurs for me aswell

**Comment by WaldiDyll** [comment]
> Hi all, this was due to a taildrop directory picker change we made in 1.84. It will be resolved with the new behavior in 1.86 which no longer asks you to pick a taildrop directory until you need to receive a file with taildrop.

This still happens in version 1.86.2, did the fix get postponed?

**Comment by nickoneill** [comment]
This is scheduled for 1.86.3 which should be out this week.

**Comment by philzulli** [comment]
Looking forward to 1.86.3. Thank you.

**Comment by paddylandau** [comment]
My three Android devices have updated to 1.86.2, and the problem has been solved for me.

So, it seems that I don't need 1.86.3.

Thank you for your work, devs.

**Comment by nickoneill** [comment]
This has been fixed in 1.86.4, it will be available on the play store when approved or available immediately at https://pkgs.tailscale.com/stable/
