### ISSUE TITLE
Upgrade via Tailscale machine page is seen as threat in Sophos

### ISSUE THREAD

**Issue by ASRTichy** [tailscale/tailscale#17632]
### What is the issue?

When trying to upgrade clients from the 'machine' page in the admin portal, the .TMP file is being flagged as malware.
Downloading the MSI directly doesn't flag as malware.

This is what the user see's:
<img width="497" height="448" alt="Image" src="https://github.com/user-attachments/assets/af00ec27-a64f-45d1-9804-01be3d1ca8f8" />

This is the log in Sophos Central.
<img width="716" height="358" alt="Image" src="https://github.com/user-attachments/assets/294b5f9e-c0f4-4466-9d69-3bffb253edc2" />

### OS

Windows

### OS version

Desktop and Server versions

### Tailscale version

1.88.4 --> 1.90.1

### Other software

Sophos Endpoint Protection

**Comment by iceph03nix** [comment]
Running into this as well, It appears to be part of their Machine Learning detections.  Not sure it's a Tailscale problem so much as a Sophos problem, but can't find a good way to flag it for Sophos to ignore since it's detecting it in the MSIEXEC

**Comment by ASRTichy** [comment]
MSI still being stopped by Sophos.  This is happening with 1.90.1, 1.90.2, 1.90.3 and now 1.90.4.
It never happened with earlier versions and so am limited to v1.88.4.

**Comment by tpavRapt** [comment]
As of today, Tailscale is being erased as a PUA by Sophos Endpoint Agent. The change was not in tailscale, it was in SOPHOS!

**Comment by ASRTichy** [comment]
Version 1.90.6 still flagging in Sophos.  Running update through the Tailscale admin console or manually running the .MSI file.

<img width="623" height="487" alt="Image" src="https://github.com/user-attachments/assets/262dafa7-0d75-48c8-b249-a43788bd6533" />

<img width="497" height="187" alt="Image" src="https://github.com/user-attachments/assets/aa83903d-872e-446d-a3ac-cbcf9d1953d1" />

**Comment by llavegrifa** [comment]
I met the same problem. Thank goodness the system reverted to the previous version. 
Now stuck in 1.88.4

**Comment by zarcha** [comment]
Today a few of my devs ran into this issue, we were able to revert back to 1.90.4 to get around it. We have sent SOPHOS an email but unsure if its fully on them or Tailscale.

**Comment by faqall** [comment]
Noticing the same: 

<img width="1573" height="376" alt="Image" src="https://github.com/user-attachments/assets/cc3700b9-3005-40f1-9c1a-6237e0551075" />

<img width="556" height="320" alt="Image" src="https://github.com/user-attachments/assets/a527da84-db19-48ec-b0ce-f279037d86db" />

Whitlisted SHAs for now

**Comment by mforrest-tmu** [comment]
It's some component of the INSTALL process that's being blocked.  After disabling Sophos, installing 1.90.6, enabling Sophos - nothing is detected and Tailscale works fine.

I've opened a case with Sophos about the installer and have whitelisted the Tailscale certificate.


My concern is that this 'bricks' tailnet access to affected devices. I don't know that there's a reasonable workaround on the Tailscale side other than maybe disabling automatic updates of Tailscale.

For example, with automatic updates:
auto-uninstall old version
auto-start install new version
installer get blocked by Sophos/other
 - machine is now inaccessible via tailnet

**Comment by awly** [comment]
It's rather hard to find a false positive submission form for Sophos, but I think it's https://support.sophos.com/support/s/filesubmission. Feel free to submit a false positive report to them, and we will do the same from Tailscale end.

@mforrest-tmu can you share a [bugreport](https://tailscale.com/kb/1227/bug-report?tab=windows) for the bricked node? A failed update should not make the node completely inaccessible, that might be a bug on our end.

**Comment by mforrest-tmu** [comment]
@awly 
A bugreport is not possible in the failed state.  After detection & cleanup by Sophos, the directory Tailscale was installed into was empty:

C:\Program Files\Tailscale>dir
 Volume in drive C is Windows
 Volume Serial Number is 5A0A-7888

 Directory of C:\Program Files\Tailscale

11/04/2025  06:49 AM    <DIR>          .
11/03/2025  02:32 PM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  586,493,861,888 bytes free


Here's a bugreport after manually reinstalling (everything's working fine)
BUG-49660a30defad066da69df03badcc7a337f955f48cdfd707ea86ab9538d38add-20251104212513Z-14c3db701310abb7


If you can isolate the .tmp install file I'll submit it to Sophos. That may speed things up.

**Comment by rustdeskremote-sudo** [comment]
Hi everyone,

Thank you all for posting the error messages, it convinced Sophos to try and fix the issue.

From Sophos:

"Sharing with you SophosLabs response and update from the information you provided:
We have marked the file as clean and set its reputation accordingly.
This should resolve the issue and will get reflected soon. If issue persist kindly revert to labs with latest screenshots."

I have now installed the latest version of Tailscale 1.90.6 without issue where it previously failed and borked my existing 1.8x install.

Hope that helps :)

**Comment by llavegrifa** [comment]
Ys, it helped.
Thanks

**Comment by Niels-LNS-Research** [comment]
I still see the issue. Tailscale 1.92.3 cannot be upgraded. Running winget.

**Comment by zaphod777** [comment]
I am still having the same issue on the latest version.

**Comment by ASRTichy** [comment]
I've got an on-going case open with Sophos Support regarding this.
They don't see anything wrong with it, but it's still being flagged as PUA ML.
Something that Tailscale brought in between version 1.88.x and 1.90.x is causing the issue.
It flags either running CLI (tailscale update --yes), MSI installer or running the update from the console (machines page).

**Comment by faqall** [comment]
Same thing here again
Tailscale 1.92.3
Windows 11 25H2
Detection name: Generic ML PUA

<img width="1240" height="370" alt="Image" src="https://github.com/user-attachments/assets/5848171a-559a-40fc-b3fe-fdce658616b4" />

**Comment by Niels-LNS-Research** [comment]
I am using winget from PowerShell.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
