### ISSUE TITLE
re-authentication on relaunch/restart

### ISSUE THREAD

**Issue by yyxi** [tailscale/tailscale#17645]
### What is the issue?

This issue appears in v1.90.2 when installing the macOS standalone .pkg; v1.88.4 (both standalone and App Store) does not exhibit the problem.

- After installing the macOS standalone .pkg v1.90.2, Tailscale requires re-authentication on reboot and when the Tailscale app is relaunched (same behavior described in the referenced issue).
- v1.88.4 (standalone and App Store) does not require re-authentication.

Reference: https://github.com/tailscale/tailscale/issues/8780

### Steps to reproduce

1. Install the macOS standalone .pkg for Tailscale v1.90.2.
2. Reboot the Mac or quit and relaunch the Tailscale app.
3. Observe that Tailscale requires re-authentication (login and approval).

### OS

macOS

### OS version

Ventura 13.7.8

### Tailscale version

1.90.2

**Comment by scientificworld** [comment]
Encountered the same problem just now. Version 1.90.1

**Comment by ElioDiNino** [comment]
Also experienced the same issue, but want to note not only did it require re-authentication, it would show up as a new device every time (which is especially annoying since my MacBook is a signing node). I tried many fixes (e.g. a complete reinstall) and the only thing that worked was downgrading to 1.88.4.

I am on macOS 13.7.8 for reference.

**Comment by nickoneill** [comment]
Thanks for the reports, are you on ventura as well @scientificworld?

**Comment by InSanniti** [comment]
Same issue here on 1.90.3 on macOS 13.7.8

**Comment by nibsuk** [comment]
Same issue here 1.90.3 on macOS 12.7.6

Relaunch or restart requires re-login to enable client and creates a new device every time

I am running the Standalone variant of the application directly from Tailscale's package server

**Comment by scientificworld** [comment]
> Thanks for the reports, are you on ventura as well [@scientificworld](https://github.com/scientificworld)?

Nope, I'm on Monterey (12.7.6)

**Comment by ikushev** [comment]
Hello!,
Good morning to everyone! Same issue, MacOs, running Tailscale 1.90.4. Gets de-auth after every reboot, sometimes after switching tailscale off and, when needed trying to turn it on prompts Tailscale's auth.

Have a good day.

**Comment by bartslinger** [comment]
Same issue here, even when disabling and re-enabling tailscale in the top bar.
Running 1.90.6 on MacOS Ventura 13.7.8 (22H730)

**Comment by bartslinger** [comment]
I've had enough of this. Besides this re-authentication issue, the connection through my exit node was SUPER slow (1-2Mbps). Now I'm back to 1.88.4 and connection through exit node is fast again. And no longer issues with re-authentication.

For people who also want to revert, first do a complete uninstall according to these instructions:
https://tailscale.com/kb/1069/uninstall?tab=macos+%28standalone%29

Then download the old version here:
https://pkgs.tailscale.com/stable/Tailscale-1.88.4-macos.pkg

**Comment by ikushev** [comment]
Hello again!,
Thanks for the info!

**Comment by nibsuk** [comment]
Anyone else seeing their accounts pane looking like this on macOS 12.7.6 Monterey?

I'm running Tailscale 1.88.4

Clicking the Add Account button has no effect

I can access all my other devices from this node though, and Mullvad exit nodes work

![Image](https://github.com/user-attachments/assets/b9448bb1-0e76-4ff4-a8b3-20076279328b)

**Comment by ElioDiNino** [comment]
> Anyone else seeing their accounts pane looking like this on macOS 12.7.6 Monterey?
> 
> I'm running Tailscale 1.88.4
> 
> Clicking the Add Account button has no effect
> 
> I can access all my other devices from this node though, and Mullvad exit nodes work

Yeah it's the same for me with v1.88.4 on macOS 13.7.8

**Comment by 7cf148fd** [comment]
Hi
Thanks @bartslinger 
Not only this fixed the reboot problem but my node also recovered its original tailscale identity and IP address!

**Comment by 7cf148fd** [comment]
Hi
To anyone reading this thread: I talked with support. They indicated that TS has identified the issue as "_likely due to a bug with Tailscale [trying to store] the node’s state in the TPM secure storage rather than directly on the filesystem, on older macOS versions._" and they are "_working on this, but don’t have an immediate timeline to share on the fix_".

Apple doesn't have TPM so I guess they are talking about the _enclave_, which indeed only exists on Apple Silicon macs.

Recommendation is to stick to v1.88.4 until further notice.

**Comment by calwalker1** [comment]
Hi just weighing in that I am experiencing the same issue on Ventura 13.3.1 (a) on a Mac mini M2. Tailscale 1.90.6.

Unfortunately this computer is used in a live event installation so upgrading it is challenging.

**Comment by wjae** [comment]
Same issue here on Monterey (Intel) with Tailscale 1.90.9 (and the prior version). Each time Tailscale restarts, it shows up as a new device and requires approval again, including after restarting macOS.

**Comment by RJinTX** [comment]
I was having the same problem on a Macbook Pro 2015 with Monterrey.  It was an existing installation that updated to 1.90.x back in October and then the problem started happening.

However, I recently upgraded to a Mac Mini M4 (Apple Silicon) and just did a restore from Time Machine (not a clean install of any apps or Tailscale). The problem does not exist on that Mac Mini.

**Comment by ldir-EDB0** [comment]
+1 for this frustrating behaviour.

**Comment by nickoneill** [comment]
This should be fixed for older macOS versions in 1.92.x

**Comment by RJinTX** [comment]
Just wanted to report that version 1.92.2 that was released a while back fixes the issue! I don't have to reauthenticate anymore.

**Comment by ElioDiNino** [comment]
Also confirming that the issue is now fixed for me (after updating to 1.92.x). Thank you for being on top of it @nickoneill!

**Comment by smilingpeanut** [comment]
Still having this issue with Tailscale 1.94.1 (standalone) and macOS 13.7.8.

**Comment by SynthStream** [comment]
> Still having this issue with Tailscale 1.94.1 (standalone) and macOS 13.7.8.

I too am having the issue on MacOS 12.7.6

**Comment by wjae** [comment]
This ticket should be reopened. The issue also occurs on macOS 26.3 (M4).
I’ve already tried reinstalling, but the problem persists.

**Comment by nickoneill** [comment]
If you're still hitting this issue with 1.94.x, please post a bug report code here as close to reproducing the issue as possible.

**Comment by jmyching** [comment]
> If you're still hitting this issue with 1.94.x, please post a bug report code here as close to reproducing the issue as possible.

Still having the same issue on v1.94.2 on MacOS Ventura 13.7.8. Each time I quit the Tailscale app from menu, and restart it again, it asks me to login and creates a new device node with a different name and IP.

**Comment by ElioDiNino** [comment]
I have a strange variation of [the issue I had before](https://github.com/tailscale/tailscale/issues/17645#issuecomment-3448727673). Since the "fix" in 1.92.x my main account has been rock solid and never kicked me out. However, I started having to switch between another tailnet for a project (with a different email address), and that one requires re-logging in every time. The control plane seems to remember the device each time since after logging in it gets mapped to the same device name and IP address (and doesn't send a new device notification webhook), but it does lose the tags I previously had assigned. Interestingly, when I switch back to my main tailnet/account, it works seamlessly every time.

I am on macOS 13.7.8 for reference.

**Comment by alexanderwebber** [comment]
Also having this issue on Ventura / TS 194.2

**Comment by reggroux** [comment]
This should be reopened unless older versions of macos are no longer supported. I'm on 13in 2017 Macbook Pro - Ventura 13.7.8

Version: 1.96.x: I'm experiencing the same problem. Every application restart requires a reauth.

I see some mentions of 1.92.x fixing the issue but that wasn't the case for me. I tried all 1.92.x versions and still had the same problem. 

Only 1.88.4 worked for me. I also experienced the [same issue](https://github.com/tailscale/tailscale/issues/17645#issuecomment-3487557302) as @nibsuk 

To resolve that I was able to get the login prompt to work by using the menu bar icon. (had to click it a lot for some reason)

**Comment by reggroux** [comment]
@nickoneill 

Here is my bug report: BUG-7525a68614b7822abe9a96a2a4c519bc928a748b9f1fff4cb12c7ddc40575364-20260330160944Z-62169cb3a5453bfd

Steps to reproduce. 

1. Install latest version 1.96.2 via .pkg
2. Sign in after initial launch.
3. Quit tailscale and reopen. 
4. Prompted to reauth again creating a new machine.

**Comment by ORMT03** [comment]
BUG-1980fad38f94f1614aeaa2f195aa35228a39d231437e44f373423075587aa011-20260330180631Z-7cfccffb2897a5ff

I tried Uninstalling via the home-brew command, and installing 1.92.2 to see if that might fix it, but it was also happening there. 
I had the problem a while back with my Mac mini also running macOS ventura, but it got fixed, now with my "new" MacBook running macOS Ventura, I'm getting this problem. every time I reopen tailscale, it makes me reauthenticate, and creates a new machine.

**Comment by LeonHTM** [comment]
Got the same Issue running Version 1.96.5 (standalone variant downloaded from the page) on macOS Monterey 12.7.6. Every time I restart it asks me to sign in again and creates new device. A fix would be appreciated. 


Edit 1: Downgraded to 1.92.2 Issue persisted
Edit 2: Downgraded to 1.88.4 Issue was solved

I used the method described by bartslinger above:

For people who also want to revert, first do a complete uninstall according to these instructions:
https://tailscale.com/kb/1069/uninstall?tab=macos+%28standalone%29

Then download the old version here:
https://pkgs.tailscale.com/stable/Tailscale-1.88.4-macos.pkg

Thanks man you saved my project.

(I only copied your message because maybe someone could miss your message)

**Comment by bradwbradw** [comment]
This bug persists. Can the issue be reopened?
```
Mac OS 12.7.6
BUG-c7c5cbf5e9427310b77157f81ab2497a2ccb369a561f4b0076bc7894ec208c42-20260512133636Z-27c4bc117001ecec

tailscale --version
1.96.5
  tailscale commit: 4ee448d3a47df7cbb5696e671bb317d0bb99fffc
  long version: 1.96.5-t4ee448d3a-g74ffbefc2
  other commit: 74ffbefc2c4897afdb84dbce2271792ebcdb13d5
  go version: go1.26.1
```

How to reproduce: 1) install tailscale. 2) log in 3) reboot.

**Comment by nibsuk** [comment]
I'm also still seeing this in the current unstable version 1.99.14

Automatically Check For Updates also keeps un-checking itself

MacOS Monterey 12.7.6

**Comment by janosdios** [comment]
Have the same issue with 1.98.2 on Ventura 13.7.8.

**Comment by JasperH8g** [comment]
Still an issue on TS 1.98.5 on MacOS 12.7.6 on an Intel-based Mac. Kind of defeats the purpose of Tailscale altogether, hope it can be fixed 🤞

**Comment by dcman** [comment]
same issue for me on Ventura.

**Comment by patricksthannon** [comment]
> Anyone else seeing their accounts pane looking like this on macOS 12.7.6 Monterey?
> 
> I'm running Tailscale 1.88.4
> 
> Clicking the Add Account button has no effect
> 
> I can access all my other devices from this node though, and Mullvad exit nodes work
> 
> ![Image](https://github.com/user-attachments/assets/b9448bb1-0e76-4ff4-a8b3-20076279328b)

Yes same issue.

**Comment by evokateur** [comment]
I'm running 13.7.8 on an old MacBook/Tank and seemed to have the same issue with 1.98.8. I needed to re-authenticate every time I started Tailscale, causing redundant entries for the machine to pile up (very disregulating).

Downgrading to 1.88.4 (as noted above) made that problem go away.

Since this was closed as solved, I wonder if there was a regression. I'll see if I can find the release that immediately followed and try it when I get a chance..

PS, I do have example.com + foo@bar.net displaying in the settings Accounts tab as well (as one does, apparently, when running 1.88.4)

**Comment by bradwbradw** [comment]
Yes, it would be helpful to indicate the version that is expected to have
this resolved. It's unclear if the fix has been actually been shipped or
not.

**Comment by benknoble** [comment]
I experienced this on 1.98.8 (macOS 12.7.6, 2015 Intel MBP): each time I disconnect and reconnect, I have to "add this device" to my tailnet. It gets a new name and IP (`<hostname>-<n>`).

There also seems to be a problem where sometimes opening preferences or other windows from the menu bar opens an application on the dock, and quitting that application icon kills the menu bar icon. But just starting Tailscale.app only opens the menu bar (no dock icon), so it doesn't seem like that's intentional.

After following the [previously posted instructions](https://github.com/tailscale/tailscale/issues/17645#issuecomment-4180502136) to uninstall, purge remaining files, and install 1.88.4 (including checking the checksum 😄): I removed the old devices from the tailnet, connected the device, unchecked "automatically install updates" in preferences.

- I see the [same account screen bug as others](https://github.com/tailscale/tailscale/issues/17645#issuecomment-4793192951)
- The admin console shows me connected, but the menu bar says "Tailscale is starting"
- `/…/Tailscale status` says I'm connected, too
- Connections to other devices work
- Reconnecting worked (no IP change, no new device) and solved the "Tailscale is starting" status (now the menu bar shows connected).

🤷 I would not say this is fixed for older macOS yet; [sounds like they are still having issues with handling the Intel silicon](https://github.com/tailscale/tailscale/issues/17645#issuecomment-3530299699).

**Comment by nickoneill** [comment]
Sorry for the confusion here, the indication that this is closed / fixed means the change has been committed. It will be included in the next major release, 1.98.8 is a point release with only the changes indicated in the changelog for that version.

**Comment by TcDrozd** [comment]
Since the fix is committed but won’t land until the next major release, here’s a workaround for anyone stuck on 1.98.x in the meantime. It avoids downgrading to 1.88.4 and may also be useful for verifying the fix once it ships.

### **Workaround (no downgrade)**

Opt out of keychain-backed state storage via the `EncryptState` policy:

```bash
sudo defaults write /Library/Preferences/io.tailscale.ipn.macsys.plist EncryptState -bool false
```

Then quit and relaunch Tailscale.

State returns to /Library/Tailscale/tailscaled.state, and both login state and serve config now survive quit/relaunch and full reboots on this machine.

### **Environment**

- MacBook Pro (2017, Intel i7)
- macOS Ventura 13.7.5 (22H527)
- Tailscale 1.98.8 standalone

This also affects `tailscale serve`: the CLI reports Serve as started, but `tailscale serve status` immediately reports no configuration because the Serve configuration is stored in the same state backend.

### **What I observed**

Every attempt to persist state to the keychain fails.

The extension first attempts `SecItemUpdate` (which fails because the item does not exist), falls back to `SecItemAdd`, and then fails while attempting to write into `/Library/Keychains/`:

```text
io.tailscale.ipn.macsys.network-extension: [general] - SecureStorage.saveData: update tailscale-machinekey in keychain: no such item
io.tailscale.ipn.macsys.network-extension: (Security) SecItemAdd
io.tailscale.ipn.macsys.network-extension: (Security) [com.apple.securityd:atomicfile] create /Library/Keychains/System.keychain.sb-06b3bec7-Zsq1mj: Operation not permitted
io.tailscale.ipn.macsys.network-extension: [general] - SecureStorage.saveData: add tailscale-machinekey: failed to add item (72 bytes) to keychain: 100001: UNIX[Operation not permitted]
io.tailscale.ipn.macsys.network-extension: [general] - prefs_save failed: err("add tailscale-machinekey: failed to add item (72 bytes) to keychain: 100001: UNIX[Operation not permitted]")
```

The same sequence repeats for:

- `tailscale-machinekey`
- `tailscale-profiles`
- `tailscale-id-profile-*`
- `tailscale-current-profile`
- `tailscale-logdata`

As a result, no persistent state is ever saved. The node functions normally while running, but after every restart it registers as a new device (`hostname-1`, `hostname-2`, etc.), and `tailscale serve` configuration is likewise lost.

The kernel log shows the underlying denial:

```text
kernel: (Sandbox) Sandbox: io.tailscale.ipn.macsys.network(4287) deny(1) file-write-create /Library/Keychains/System.keychain.sb-520fea41-ieQ7HY
kernel: (Sandbox) Sandbox: io.tailscale.ipn.macsys.network(4287) deny(1) file-write-create /Library/Keychains/System.keychain.sb-520fea41-ZfR6jw
```

### **Possible explanation**

One log line from the GUI may be relevant:

```text
Tailscale: (Security) [com.apple.securityd:keychain] System Keychain Always Supported set via feature flag to disabled
```

My interpretation is that, on Ventura, keychain-backed state storage is attempting a code path that ultimately requires creating temporary files under `/Library/Keychains/`. Those writes are denied by the Network Extension sandbox, so every persistence attempt fails.

I can’t say with certainty whether that’s the root cause, but it matches the observed behavior and the kernel sandbox denials.

The failure is also effectively silent: `prefs_save failed` is logged, but the client otherwise continues operating normally, so nothing appears wrong until the next restart.

Happy to re-enable EncryptState and verify keychain writes succeed on this Ventura/Intel machine once the next major release is out, if that's useful.

Bug report:

`BUG-85ce54dbf0592c47550bd36bd1a66bc4e8f54e6a62cc332431969a2e8c0e1c77-20260706184225Z-3421bafeb9495182`

**Comment by benknoble** [comment]
@nickoneill is this one fixed in 1.102.1/2? I can't tell from the [changelog](https://tailscale.com/changelog), but a similar issue was [related as fixed](https://github.com/tailscale/tailscale/issues/17760#issuecomment-5144056448).

**Comment by nickoneill** [comment]
It's fixed. Please give it a shot.
