### ISSUE TITLE
Tailscale often breaks all internet on Android

### ISSUE THREAD

**Issue by michaelkolber** [tailscale/tailscale#17886]
### What is the issue?

Every so often, Tailscale breaks the Internet on my phone. Turning off Tailscale fixes it. While it's on, I get SSL configuration errors in Chrome for any website.

### Steps to reproduce

Unsure. [This Reddit thread](https://www.reddit.com/r/Tailscale/comments/1or92it/tailscale_blocking_internet/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) says it happens when they switch between networks, but I haven't had that happen reliably.

### OS

Android

### OS version

Android 16

### Tailscale version

1.90.4

### Other software

N/A

### Bug report

BUG-56717149e208c661627c62b487f1733859f512ae45106b5121dfb541c89f628e-20251114005845Z-e5d8b06192d129ec

**Comment by michaelkolber** [comment]
May be related to #17747 but I'm not running Graphene, just stock Pixel Android.

**Comment by drteevee** [comment]
Same issue on stock Pixel 9

**Comment by fruitwerks** [comment]
Same here. Android 16 -pixel 10 pro xl/stock. Tailscale 1.90.4

Nothing going out works. I did get some select inbound notifications. 

I played around, I got it to break similarly on wifi with unreproducible frequency, but 100% on mobile data when using always on VPN. Doubt it's carrier specific, but T-Mobile/eSIM.

edit - fix typo+add use case

I use use tailscale to reach individual hosts while out of the house. I do not use MagicDNS, exit nodes, or have any additional routing, just basic point-to-point style config.

**Comment by IamPotat0o** [comment]
I am having the same issue. I am on a Samsung Galaxy Z Fold 5 running One UI 8 and Android 16. Out of nowhere, several apps lose access to the internet. When I disable Tailscale everything starts working again, and I also receive a bunch of notifications from apps that were not able to connect to the network in background.

**Comment by fruitwerks** [comment]
** Possible Root Cause ** 

After looking at the reddit thread I did some basic testing to get some insight. I've concluded TS does not notice the network state changes - thus holds the internal routing/connection state with the last known state info. So even if you you got it going on mobile data, if you reassociated via roaming/prioritization, you are "offline" again because your old state is no longer valid. If you toggle the VPN on and off, this refreshes the internal TS routing and you are good until it changes again. 

I highly suspect this has something to do with the new Android Auto HFP mess. Not specifically HFP, but whatever they did under the hood within the last week that requires those who preferred wired only connections with phone calls disabled to enable Bluetooth anyway. I think this is a lower level bug in the core network stack. 1.90.4 was running fine for two weeks, I have narrowed down the bad actor to [this](https://support.google.com/product-documentation/answer/14343500?hl=en) - specifically the "Stability Fixes" if my theory is correct. If I had a rooted phone or a dev emulator already running I would test this right now but I don't have time.

**Comment by Pikey18** [comment]
Seeing the same issue on a Samsung S21 running Android 15. Downgraded to 1.88.3 from the official repo and that seems better.

**Comment by fruitwerks** [comment]
@Pikey18 Can I bug you for you Google Play Services version?

Settings > apps (all apps - maybe even show system apps) > Google Play services, scroll to the very bottom (usually). 

Thanks!

**Comment by Pikey18** [comment]
> [@Pikey18](https://github.com/Pikey18) Can I bug you for you Google Play Services version?

Version 25.44.35 (260400-831510661)

**Comment by fruitwerks** [comment]
> > [@Pikey18](https://github.com/Pikey18) Can I bug you for you Google Play Services version?
> 
> Version 25.44.35 (260400-831510661)

Thank you. If you - or anyone else that finds this is in the position to roll back to Google Play services v25.42 (2025-10-27) and test against TailScale 1.90.4 - we will have a clear(er) path to a fix. I wholeheartedly believe the issue was introduced after this TS build dropped. 

Goodnight, good luck - I'm off to bed!

**Comment by Pikey18** [comment]
@fruitwerks Don't want to try that when downgrading Tailscale fixes the issue. Hopefully whatever the issue is gets fixed with updates.

**Comment by DaithiW** [comment]
Noticed this issue since yesterday. Samsung Galaxy S25. 1.90.4

**Comment by zackify** [comment]
Happens to me as well. If I turn off tailscale DNS then I can change networks again. Otherwise I must manually turn tailscale off when wifi disconnects

**Comment by terribilus79** [comment]
Same issue Z Fold7

**Comment by dazzag24** [comment]
Pixel 9a. Same issue. Turn off tailscale and back on again resolves it.

**Comment by bukkaroo** [comment]
Having the same issue on my Samsung Fold 5 with Android 16 (Nov 1 2025 patch) & One UI 8. Tailscale needs to be manually toggled to regain connectivity.

**Comment by darren-c** [comment]
For me it is fairly easy to reproduce on my Pixel 9. I'm using Tailscale Android app 1.90.4 and any time I am changing networks on my phone (from Wi-Fi to cellular data or vice versa), only the traffic to my Tailscale network is working, while all other traffic (i.e. the internet) ceases. I can disconnect and reconnect to Tailscale and things become normal again. I have MagicDNS enabled and an AI chatbot suggested turning off Private DNS in Google settings but this did not help.

**Comment by Meas** [comment]
Same here. I can reproduce it easily by turning WIFI on and off. Only started noticing this bug about a week ago. It is really annoying leaving the house and then remembering "oh yeah I have to turn my tailscale off and on if I intend to receive any notifications".

I am using Oneplus 9 btw.

**Comment by Fungrim** [comment]
Same. Pixel 7 Pro. Android 16. Tailscale 1.90.4 with DNS and exit node. Play services 25.45.34.

**Comment by ScuttleDrive77User** [comment]
I am having similar issues on T Mobile Galaxy S24+ running tailscale App Version: v1.90.8. Issue can be replicated simply by turning wifi off, attaching to 5G, and then turning WIFI on again. Or, it can also be replicated by moving out of range of a wifi network and having android automatically switch to 5G. To fix the issue, you can disconnect from tailscale and then reconnect.

**Comment by drtiwarir** [comment]
It is giving a lot of problem. Once connected, none of the streaming apps work (including YouTube), just dark screen. My Nvidia Shield stopped connecting to internet (both wifi & ethernet, using ASUS router). I deleted Tailscale, but the problem persisted, eventually did factory reset, but nothing worked again. Had an old android tv box, installed Tailscale app and tried, same situation.

**Comment by NewFangled1** [comment]
Noticing the same issue here with a Samsung S23 Ultra and my father has the issue with his Samsung A55. He noticed the problem last week, but I have only turned on Tailscale on my phone again yesterday and didn't notice the issue until I was out of range of my home wifi today.

Edit to say that like others I can replicate easily by having my phone connected to wifi and Tailscale and then turning wifi off. If I then open a browser and do a search, it won't find an internet connection even though the phone is connected to cellular data. If I turn Tailscale off, the internet works fine. If I turn Tailscale back on, the internet works fine still.

**Comment by ExoGeologist** [comment]
Same issue with oppo find X3 neo and my sister's Z flip 4.... Need to connect and disconnect tailscale to get back access to internet... very annoying... Can we expect a fix at some point or roll back is the only viable option ?

**Comment by jessielw** [comment]
Same issue here on several android devices I use. 

I just swapped back to pure wireguard until this is fixed. It isn't as convenient but super stable. I'll keep an eye on this thread until it's fixed.

**Comment by ccrepin** [comment]
Same here with 2 Phones S25 and Oppo find x3 neo
Rollback to 1.88.3 fixed for the moment.

**Comment by sfllaw** [comment]
Fixed by tailscale/tailscale-android#717 and released as [version 1.90.9](https://tailscale.com/changelog#2025-11-25).

**Comment by drtiwarir** [comment]
Hi Simon,
How to get this latest version on Android TV ?
It is not available on play store

Thanks

**Comment by sfllaw** [comment]
@drtiwarir, the Google Play Store gradually rolls out updates so it may take a while before you see it.

Since the bug is triggered when your devices switches networks, and most Android TV devices tend to stay connected to a single network, I am wondering if you are encountering another problem?

**Comment by drtiwarir** [comment]
Maybe you’re correct
My android tv is connected with ethernet.
I have no issues with TS on MacBook/iPhone and iPad. But these devices are
connected over WiFi.
Let me check your latest version of the app and see how it works.

Regards

**Comment by quietCoder500** [comment]
Sorry all, but I am still having this issue on tailscale android 1.90.9. Internet only works if TS DNS is off and even then I can't access local ips.

**Comment by quietCoder500** [comment]
Update: problem still not solved as of 1.92.1

**Comment by Prodeguerriero** [comment]
Long standing issue for me as well. Still happening as of one hour ago.

- Android 15 on Fairphone 4
- 1.90.9
- Google Play services 25.47.30

Tailscale is in our shortlist at work for a new VPN solution, but this issue is a blocker, as we mostly use Fairphone devices (you can guess why 😁).

Cheers

**Comment by higheraims** [comment]
I'm having this issue on build 1.92.3 and GrapheneOS

**Comment by davemunneke** [comment]
1.92.3 on Samsung S20 (Android 13) same problem. 1.88.3 works fine.

**Comment by quietCoder500** [comment]
The title is no longer relevant to the issue I think most commenters have. We may need a new issue for those whose Tailscale install simply won't work on their Android device.
(or i'm out of touch...)

**Comment by higheraims** [comment]
> The title is no longer relevant to the issue I think most commenters have. We may need a new issue for those whose Tailscale install simply won't work on their Android device. (or i'm out of touch...)

Actually maybe we all need a new thread - this one is closed anyway. And the one it's a duplicate of is also closed.

**Comment by IbrahimOezhan** [comment]
Same issue
