### ISSUE TITLE
Mac OS needing constant re authentication

### ISSUE THREAD

**Issue by Deeppy1** [tailscale/tailscale#18097]
### What is the issue?

Recently with my 2 macs both Mac OS 12 Monterey When ever i disconnect and reconnect it requires re authentication each tim

### Steps to reproduce

Login turn on turn off need to login again

### OS

macOS

### OS version

Mac OS 12 Monterey 

### Tailscale version

1.90.6

### Bug report

BUG-81ebc59b93703dcf005f28105f30007b508b3263b5b60ae47236c51ccb0de162-20251130111936Z-43a79ac9769f24b4

**Comment by Erisa** [comment]
Please try the latest version, 1.90.9

**Comment by Deeppy1** [comment]
All updated to latest version no change 1.90.9 is installed

**Comment by barnstar** [comment]
This should be fixed in 1.92.0 (available now in our Release Candidate track).   1.90 added support for encrypting local state which isn't properly supported on Monterey and Ventura which would cause the loss of the machine keys.

**Comment by Deeppy1** [comment]
Hey I've updated to the latest unstable version this morning and it seems to work I'll let you know if anything crops up
Thanks

**Comment by KumaCool** [comment]
> This should be fixed in 1.92.0 (available now in our Release Candidate track). 1.90 added support for encrypting local state which isn't properly supported on Monterey and Ventura which would cause the loss of the machine keys.

My current version is 1.94.2.
I'm encountering the same issue. It seems that every time I log in via a link, it's recognized as a new device: macbook, macbook-1, macbook-2...
Even though I've configured [Expiry disabled] in the console, it doesn't work.

**Comment by j3r3miah** [comment]
Still experiencing this on 1.94.2, macOS Monterey (12.x), standalone .pkg install.

Same behavior as described above: every reboot or app relaunch requires re-authentication and creates a new device entry (macbook, macbook-1, macbook-2, etc.). Key expiry is disabled in the admin console but it makes no difference.

Even just quitting and reopening the app (no reboot) triggers re-auth and a new device. The node state is not persisting between launches.

My newer machines seem fine.

**Comment by Chitou1** [comment]
still experiencing the same issue on Ventura 13.7.8, with Tailscale 1.97.184, same symptoms as above.

**Comment by ooTruffle** [comment]
Tailscale 1.96.5 on macos monterey has the same issue.

**Comment by Chitou1** [comment]
For me switching to the App Store version fixed the issue.

**Comment by Deeppy1** [comment]
What version is it on the App Store as it was fixed for a while

**Comment by mmccarr** [comment]
Tailscale 1.98.5 on macOS 12.7.6 still shows this issue. The workaround for me is to disable state encryption with 
defaults write ~/Library/Preferences/io.tailscale.ipn.macsys.plist EncryptState -bool false
