### ISSUE TITLE
Package installer states "update failed" but was successful

### ISSUE THREAD

**Issue by davidsbond** [tailscale/tailscale#2214]
**Description**
This is a pretty minor one, but might confuse people. When I upgrade to newer versions via the spk files provided. I find that it reports "upgrade failed" when it does in fact work. The version changes appropriately and the Tailscale daemon remains running, since I can still access everything. It's also at the latest version when I look in the Tailscale UI at my machines. I've noticed this the last two or three times I've upgraded.

This might be fixed by moving to an official synology package anyway as discussed in tailscale/tailscale#2207, so probably isn't a big deal.

**Steps to reproduce**
Upgrade to a newer version via the provided spk file
On finish, see a "upgrade failed" message, but version has changed and tailscale is working fine

**Expected behavior**
Some sort of success message instead.

**Synology NAS model**
DS115j

**Comment by jucor** [comment]
I am happy to report that this error is solved with the latest 1.10.0 release for Synology \o/ 🥳

**Comment by jucor** [comment]
@DentonGentry I'm sorry to report this error is back with the latest 1.16.0 release for Synology :'(

**Comment by DentonGentry** [comment]
1.22 is in the Synology Package Center now.

**Comment by DentonGentry** [comment]
1.30 is in the Synology Package Center now. I think I've seen the "upgrade fail" message once recently, when the package update did succeed.

**Comment by Dae657** [comment]
It's still happening when updating manually. I was going from 1.38.4 to 1.46

**Comment by JazoBurbs** [comment]
This is still happening (v 1.80). There hasn't seemed to be any cause for alarm or broken functionality. But it definitely is confusing every time I upgrade.

**Comment by ilya-yarets** [comment]
Reproduced on 2026-08-22 with current releases:

- Synology DS220+ (x86_64)
- DSM 7.4.1-90080
- Upgrade through Package Center → Manual Install
- From Tailscale 1.58.2-700058002 (Synology Package Center)
- To the official stable `tailscale-x86_64-1.102.3-700102003-dsm7.spk` from pkgs.tailscale.com
- The SPK SHA-256 matched the published checksum

DSM displayed “Failed to update Tailscale” after the update dialog completed. However:

- Package Center immediately showed installed version 1.102.3-700102003
- Package status was Running
- HTTPS access to DSM over Tailscale remained available
- Connectivity checks had 0% packet loss
- Package Center’s “latest online version” still showed 1.58.2-700058002, reflecting the older Synology repository version

No retry, uninstall, or reinstall was needed. This confirms that the false failure message still occurs on DSM 7.4.1 with Tailscale 1.102.3.
