### ISSUE TITLE
Android RCS/Jibe cannot send if Tailscale is active

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2322]
(user report)
When tailscale is enabled Google's Jibe relay for Rich Communication Services breaks and you no longer receive text messages if they try to send via RCS.

User notes that RCS/Jibe is itself in beta.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3c3o1)

**Comment by DentonGentry** [comment]
It looks like I use the Messages app to send RCS messages? So far I can only get it to offer to send SMS, I think it may need to know that the recipient can receive RCS.

One thing comes to mind when talking about carrier messaging protocols: is the carrier using CGNAT with 100.x.y.z addresses?
You can find this in Settings > About phone, there is an "IP address" listing near the end. If Tailscale is connected you'll see the Tailscale address there, 100.x.y.z. If Tailscale is disconnected, do you see a different 100.x.y.z address?

**Comment by StraightfaceStudios** [comment]
Looks like my carrier IP is 10.76.106.38

tracepath to google
1)172.x
2) 12.x
3) sffca22crs.ip.att.net

Looks like there might a low level wireguard problem. 
https://www.reddit.com/r/WireGuard/comments/etckm7/wireguard_and_rcs/

**Comment by StraightfaceStudios** [comment]
To see if you're connected to Google's Jibe server you go to:

1) Messages
2) Menu ... 
3) Chat Features
4) Status: {"Connecting", "Connected"}

**Comment by DentonGentry** [comment]
With Android 12 and going to Messages > Settings > Chat features, it says Status:Connected.

However even with Tailscale disconnected, typing in a chat message only offers to send it via SMS.
I haven't figured out how to get the option to send via RCS.

**Comment by dakotawhitevalley** [comment]
In response to https://github.com/tailscale/tailscale/issues/2322#issuecomment-874776577 ...

I run a Galaxy S21 Ultra from Verizon with Android 12 and am having the same issue as @StraightfaceStudios. With Tailscale connected and while on an exit node, or not, Google Messages RCS immediately disconnects and shows the following in the debug menu, and in Chat Features, continuously says Connecting...

![Screenshot_20211228-012520_Messages](https://user-images.githubusercontent.com/4442088/147535187-b0d46853-a6e3-4410-b425-406594b675a7.png)


Also would like to note, this same behavior happens while on cell or wifi, it does not matter. Though when connected through an ethernet adapter **without** Tailscale turned on, RCS will also drop out with the same error, so not quite sure if this is actually an MTU issue..?

**Comment by dcowan-london** [comment]
Same issue with Android 11 and Google Messages app.

RCS works with mobile data disabled on Wifi (so I doubt this is an IP conflict issue), but when Tailscale is connected, the Messages app just shows "Connecting..." under Chat Features (without exit node enabled).

**Comment by Death916** [comment]
> 

My issue was solved by reenabling the volte and rcs features through a cell code options menu. Tailscale still seemed to be involved though because i could toggle Chat in google messages when tailscale was turned off before the change. Now it works with tailscale on or off.

**Comment by DentonGentry** [comment]
RCS/Jibe messaging is believed to be resolved in the 1.29.0 unstable build available on the Open Testing track in the Play Store.
Join via web: https://play.google.com/apps/testing/com.tailscale.ipn
Join via Play Store app: https://play.google.com/store/apps/details?id=com.tailscale.ipn

**Comment by DentonGentry** [comment]
We have confirmation from a user who had experienced this problem that the Open Testing build does resolve it.

**Comment by jeryd** [comment]
Can this be reopened? I'm still having issues. tailscale / RCS not working together.

**Comment by bradfitz** [comment]
> Can this be reopened? I'm still having issues. tailscale / RCS not working together.

You're welcome to open a new issue with full details and reference this issue if you'd like.

**Comment by e-t-l** [comment]
> My issue was solved by reenabling the volte and rcs features through a cell code options menu

@Death916 do you remember what the cell codes were?
