### ISSUE TITLE
High battery usage on mobile platforms

### ISSUE THREAD

**Issue by gillescoolen** [tailscale/tailscale#2442]
When running the Android 12 beta on a Pixel 5, I am getting a noticeable decrease in battery life when using Tailscale.

![Screenshot_20210716-213255.png](https://user-images.githubusercontent.com/31668393/125999895-49d8f902-e6f2-48dc-8956-7aa67f6ae011.png)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3f6a9)

**Comment by DentonGentry** [comment]
For Tailscale to accumulate 22 hours of runtime, it is either stuck in a loop or there is a pretty constant stream of traffic going over the VPN.

Could you send either the email address associated with the account or the Tailscale IP address of this phone to support@tailscale.com, so we can look into those?

For comparison, this is what Android 12 on a Pixel 3a is showing:
![Screenshot_20210716-123743](https://user-images.githubusercontent.com/1140756/126000448-7b69f88a-1e04-4561-a15b-e641fc7fc314.png)

**Comment by gillescoolen** [comment]
Will do!

**Comment by DentonGentry** [comment]
There is a subnet router on your account which the Android phone is communicating with often enough that it keeps trying to establish a direct connection but never manages to so. It is able to communicate using the DERP relay, but I think the main part of the power consumption is in waking the radio up so often trying to make a direct connection.

You can likely see this on the subnet router system in `journalctl -u tailscaled`, grep for "magicsock: disco:"
The output of `tailscale status` on the subnet router will likely show something like:

$ tailscale status
...
100.x.y.z  phone        user@   android active; relay "lhr", tx 1108 rx 188

As for what to do about it, the most straightforward thing would be to get them able to make a direct connection so they'll stop having to try so hard. This could include:
- whatever the firewall is from your ISP that the subnet router is sitting behind, if you can enable NAT-PMP on it then the subnet router will have one more tool it can use.
- with the 1.12 release in a couple weeks we'll add UPnP as well, so if that firewall does not have NAT-PMP but does have UPnP that could help.
- open UDP port 41641 in the ISP firewall, allowing UDP port 41641 packets in to at least the subnet router.

**Comment by gillescoolen** [comment]
I see, I'll move the subnet router to another host which has the port open. Thanks for taking your time to figure it out!

**Comment by buxel** [comment]
I have a similar issue on a galaxy s20, nut running on android 11. I also do have a relay node in my network. 

![Screenshot_20210728-195317_Device care](https://user-images.githubusercontent.com/331779/127372471-a66acb25-fa42-447c-97ba-06f38046b95b.jpg)

@DentonGentry  Should i also send a support mail with my details, so you can have a look?  Also, where can i read more about the ports and local setup requirements for optimal connectivity?

**Comment by DentonGentry** [comment]
You can send either your email address or the Tailscale IP address of the Android device to support@tailscale.com, sure.

Things you could look at if you want to dig into it yourself will mostly be from the subnet router, the Android UI is very minimal and lacks most of these tools.

----

`tailscale status` will show whether nodes are able to make a direct connection:
```
$ tailscale status
100.99.98.97  node1     dgentry@       linux   active; relay "fra"
100.99.98.96  node2     dgentry@       linux   active; direct 10.1.10.23:39651
```

As will `tailscale ping`:
```
$ tailscale ping node1
pong from node1(100.99.98.97) via DERP(fra) in 483ms
```

----

`journalctl -u tailscaled --since="10 minutes ago"` is also useful in seeing what logs are being reported. For example, this is one of my devices trying to contact another device, by sending pings on every potential path:

```
2021-07-28 12:29:23.936634268 +0000 UTC: 8.6M/85.9M magicsock: disco: d:24f3616e79f4671a<-d:90e39f8824f52dae ([gihol], derp-2)  got call-me-maybe, 4 endpoints
2021-07-28 12:29:23.937721039 +0000 UTC: 8.6M/85.9M magicsock: disco: d:24f3616e79f4671a->d:90e39f8824f52dae ([gihol], 1.2.3.4:34725) sent ping tx=1c5dc5d9ec56
2021-07-28 12:29:23.938140726 +0000 UTC: 8.6M/85.9M magicsock: disco: d:24f3616e79f4671a->d:90e39f8824f52dae ([gihol], [2602:1:2:3:4:5:6:7]:42408) sent ping tx=b20f42bcad43
2021-07-28 12:29:23.938221768 +0000 UTC: 8.6M/85.9M magicsock: disco: d:24f3616e79f4671a->d:90e39f8824f52dae ([gihol], 10.1.10.15:42408) sent ping tx=5b11db551fb0
2021-07-28 12:29:23.938367237 +0000 UTC: 8.6M/85.9M magicsock: disco: d:24f3616e79f4671a->d:90e39f8824f52dae ([gihol], [2602:1:2:3:4:5:6:7]:42778) sent ping tx=cded28dbc4a1
```

This means it got a response ("pong") and has made a direct connection:
```
2021-07-28 12:29:23.93984432 +0000 UTC: 8.6M/85.9M magicsock: disco: d:24f3616e79f4671a<-d:90e39f8824f52dae ([gihol], [2602:1:2:3:4:5:6:7]:42778)  got pong tx=cded28dbc4a1 latency=3ms pong.src=[2602:1:2:3:4:5:6:7]:40875
```

If you don't see any successful pongs and it is just getting timeouts, then it will keep using DERP relays:
```
2021-07-28 12:29:19.395077097 +0000 UTC: 7.8M/85.9M magicsock: disco: timeout waiting for pong e9036ccfd484 from 10.255.1.12:42584 ([z/yU4], d:923ea5bc79828552)
```

If the Android device is actively communicating with another node but having to use DERP, we believe the activity of turning the radio on and off continually probing for a direct connection leads to higher battery consumption.

**Comment by buxel** [comment]
Thanks for the quick reply. I had a look at the logs and found not "pong" anywhere on the relay node via
`journalctl -u tailscaled | grep pong`. 

One thing i forgot to mention is that the relay node is a RPi, which also servers pi-hole as DNS server for all tailscale devices. This could explain the frequent connection attempts.

I also contacted you via e-mail with my details.

**Comment by gillescoolen** [comment]
I also use a RPi running pi-hole as a DNS. The battery consumption issues were resolved when I stopped using it from my home network.

**Comment by buxel** [comment]
Following the advice i got in the email,  i
- port forwarded UDP/41641 to my raspberry 
- enabled upnp, just to make sure 

This is the result after a work day away from home with mobile internet only. 
@gillescoolen do you manually stop tailscale, when at home? 

![Screenshot_20210729-185704_Device care](https://user-images.githubusercontent.com/331779/127534125-b86e2a06-a514-49b7-bded-397c9dd1ee1f.jpg)

...i had a cozy warm pocket all day 😄

**Comment by gillescoolen** [comment]
Oh no, I meant I removed the RPi from my home network and now host pi-hole on an external server which I route the traffic through. Haven't had the extremely high battery usage since!

**Comment by gillescoolen** [comment]
@buxel did you manage to fix your battery issue? If so, we can close this issue.

**Comment by buxel** [comment]
No, the issue still remains. For now, i disabled tailscale on my android device and only enable it on demand. 
Having it on all the time would allow me to use pi-hole for DNS when on the go, which would be sweet.

**Comment by cncb-gh** [comment]
I have noticed similar issues with Android 11 on my Pixel 3.  My test is to charge it completely and put it in "Do Not Disturb" mode overnight.  Only cellular is active (WiFi disabled).  I get the following consistent results:

1) Tailscale Stopped: battery level drops to 96%
2) Tailscale Active: battery level drops to 74%

**Comment by buxel** [comment]
If there is any more input required from my side, please let me know. It is currently not feasible for me to use tailscale when i'm on the go since battery drains so fast.

**Comment by krimpenrik** [comment]
I am also getting some battery drain from tailscale, I am using a phone tracker that is pushing coordinates to my nextcloud server at home. 

`root@nas:~# tailscale ping rr-pixel3
pong from rr-pixel3 (100.73.71.55) via 192.168.2.8:40016 in 291ms
root@nas:~# tailscale ping rr-pixel3
timeout waiting for ping reply
timeout waiting for ping reply
timeout waiting for ping reply
timeout waiting for ping reply
timeout waiting for ping reply
timeout waiting for ping reply
timeout waiting for ping reply
timeout waiting for ping reply
timeout waiting for ping reply
`

first ping is when my phone is on my home wifi, second is when I am on mobile internet. Does this means I have to port forwarded UDP/41641 from my ISP router to my nextcloud install?

**Comment by DentonGentry** [comment]
Tailscale 1.16 made a number of changes to wake the radio less often and not consume so much battery on mobile devices. I think we've reached the point where an overall tracking bug like this, particularly with so much history already, is no longer useful and we'd be better off with specific bugs for specific things we might do.

Barring further comment, we'll expect to close this during the next bug scrub.

**Comment by juev** [comment]
Tailscale 1.16.1
iOS 15.1

![image](https://user-images.githubusercontent.com/114635/141220333-4b6ae82a-a464-4b49-96ac-ec0aa15a50e2.jpeg)

**Comment by juev** [comment]
After updating to test version (1.17.68) looks good:

![IMG_2983](https://user-images.githubusercontent.com/114635/141425455-a2ce674c-7629-4d62-9e9d-5886233ffa85.PNG)

**Comment by gillescoolen** [comment]
Great work!

**Comment by bradfitz** [comment]
To be clear, we're not done with battery fixes yet. There are still quite a few things we plan on improving.

**Comment by bradfitz** [comment]
(This bug continues in #3363)
