### ISSUE TITLE
Android app doesn't allow to change hostname and defaults to localhost.

### ISSUE THREAD

**Issue by JayDoubleu** [tailscale/tailscale#409]
**Is your feature request related to a problem? Please describe.**

When using android app it registers itself as "localhost" and there is no way to change it from the app itself nor from the admin console.

**Describe the solution you'd like**

Add settings menu which would allow to tweak settings. Hostname would be one of them.

**Comment by apenwarr** [comment]
I don't know much about android, but if all devices really think their hostname is "localhost" we might want to at least invent some better user-visible identifier. Making it user-configurable from the app wouldn't match with what we do in our other apps though.

**Comment by JayDoubleu** [comment]
Well technically the phone is reporting a properly generated hostname when establishing DHCP session on Wifi however adb shell returns localhost.
Maybe there is a way to retrieve the ID from wherever DHCP is getting it from also.

**Comment by eliasnaur** [comment]
FWIW, I believe the iOS registers itself as just "iPhone". I wouldn't be surprised if the hostname was off-limits for app, in which case I could change the name to "Android".

**Comment by JayDoubleu** [comment]
```shell
OnePlus8Pro:/ $ getprop net.hostname
OnePlus8Pro
OnePlus8Pro:/ $ hostname
localhost
OnePlus8Pro:/ $ 
```

Surprisingly, the getprop returns an actual hostname while hostname command returns localhost

**Comment by bradfitz** [comment]
> FWIW, I believe the iOS registers itself as just "iPhone".

That doesn't seem to be the case. My iPhone sends "brad11p" to the control server as its hostname (which is my phone's name).

**Comment by bradfitz** [comment]
@eliasnaur, I just pushed https://github.com/tailscale/tailscale/commit/afb9c6a6abc9fa5a26200cc36d1ffc947b8b9e89 but didn't test it. I'll let you verify that does the trick.

@JayDoubleu, thanks for the `getprop` reminder! (That rung a bell, but I've been away for Android development for ages.)

**Comment by JayDoubleu** [comment]
Hmm. Do I need to do anything on the tailscale-android branch to get the update properly ?
(I'm not that 'go' savvy ) It didn't work after removing all stuff from my GOAPTH and I also changed the go.mod to point to master but I an still see the localhost within the app itself.

**Comment by bradfitz** [comment]
We're not using GOPATH mode. Just modules. `go get tailscale.com@master` in the tailscale-android directory should do it. I see that it worked for me (updates go.mod and go.sum:

```
[bradfitz@lintile tailscale-android]$ go get tailscale.com@master
go: tailscale.com master => v0.98.1-0.20200527195041-afb9c6a6abc9
go: downloading tailscale.com v0.98.1-0.20200527195041-afb9c6a6abc9
[bradfitz@lintile tailscale-android]$ git di
diff --git a/go.mod b/go.mod
index 392cd3c..f3b11fe 100644
--- a/go.mod
+++ b/go.mod
@@ -8,5 +8,5 @@ require (
        github.com/tailscale/wireguard-go v0.0.0-20200515231107-62868271d710
        golang.org/x/exp v0.0.0-20191002040644-a1355ae1e2c3
        golang.org/x/sys v0.0.0-20200501052902-10377860bb8e
-       tailscale.com v0.98.1-0.20200524053159-e6b84f2159ba
+       tailscale.com v0.98.1-0.20200527195041-afb9c6a6abc9
 )
diff --git a/go.sum b/go.sum
index c0a6f3b..1b253dd 100644
--- a/go.sum
+++ b/go.sum
@@ -185,3 +185,5 @@ tailscale.com v0.96.2-0.20200501140524-7b901fdbbc51 h1:JlkWBx63N3Su6NnEu0+hlNzud
 tailscale.com v0.96.2-0.20200501140524-7b901fdbbc51/go.mod h1:lSEmuWEgZd+EAwk+m6d4Zmk7I5UsEBUGyBBzpf90XV8=
 tailscale.com v0.98.1-0.20200524053159-e6b84f2159ba h1:P+BSN4UNWBuehhB9s17WDynwjVxgQqV+asPThTiMOwg=
 tailscale.com v0.98.1-0.20200524053159-e6b84f2159ba/go.mod h1:qhqIOURjwBji/8sD4E3HmTou3eyp/2HfFuPLdjs7ge8=
+tailscale.com v0.98.1-0.20200527195041-afb9c6a6abc9 h1:p97Y0zpypXP3nHuZ17J9QoFbWoq9v5kxT11ofxOXQa0=
+tailscale.com v0.98.1-0.20200527195041-afb9c6a6abc9/go.mod h1:qhqIOURjwBji/8sD4E3HmTou3eyp/2HfFuPLdjs7ge8=
```

**Comment by JayDoubleu** [comment]
Hmm. In this case it still reports as localhost.
re-cloned everything from scratch and got the same diff
removed the apk just in case
reinstalled with adb. 
It still reports as localhost

**Comment by bradfitz** [comment]
Like I said, I never tested my change. :) Perhaps getprop's not in $PATH.

I'm setting up my Android device for testing.

**Comment by JayDoubleu** [comment]
I see. Changing it to ```/system/bin/getprop``` did the trick and I can now see the proper hostname in the app as well as in admin console.

**Comment by eliasnaur** [comment]
On my android API level 28 and 29, running `/system/bin/getprop` from an app results in a `SIGSYS`:

`signal 31 (SIGSYS), code 1 (SYS_SECCOMP), fault addr --------`

I didn't try the `__system_property_get` NDK equivalent, because it was removed from API level 21,
according to https://stackoverflow.com/questions/26722040/replacement-for-system-property-get-in-android-l-ndk.

Any other good ideas?

**Comment by JayDoubleu** [comment]
So in your adb shell, if you run ```which getprop``` what path does it return ?

**Comment by eliasnaur** [comment]
```
generic_x86_64:/ $ which getprop
/system/bin/getprop

**Comment by JayDoubleu** [comment]
And if you run ```getprop net.hostname``` from adb shell, does it work ?
I'm not sure how this is going to behave on emulators tbh.

**Comment by eliasnaur** [comment]
It does work, but result in an empty hostname:

```
generic_x86_64:/ $ getprop net.hostname 

generic_x86_64:/ $
```

Perhaps there is a chance the SIGSYS is not caused by `getprop` but by the Go runtime using a blocked syscall:

```05-28 11:48:37.974  6231  6231 F DEBUG   : Cause: seccomp prevented call to disallowed x86_64 system call 33```

 I'll dig into it.

**Comment by JayDoubleu** [comment]
So the ```signal 31``` would be triggered by the null value ultimately yeah ? 

Now assuming something like os.getenv to make it resilient to changes.
I can still see how this can get messy in the admin portal. I can already see hundreds of iPhones and Androids in there without anyway to uniquely identify them.

Something partially mentioned here https://github.com/tailscale/tailscale/issues/324

**Comment by eliasnaur** [comment]
https://go-review.googlesource.com/c/go/+/235537 avoids the SIGSYS, but still leaves the hostname empty on my emulators as well as on a Pixel running Android 10.

**Comment by bradfitz** [comment]
What a clusterfun: https://medium.com/capital-one-tech/how-to-get-an-android-device-nickname-d5eab12f4ced

**Comment by JayDoubleu** [comment]
How about combining some of these ?
```shell
OnePlus8Pro:/ $ getprop vendor.boot.serialno
2x91cf81

OnePlus8Pro:/ $ getprop vendor.product.device
OP_PHONE

OnePlus8Pro:/ $ getprop|grep -i oneplus                                                                                                                                                                           
[ro.build.product]: [OnePlus8Pro]
[ro.com.google.clientidbase]: [android-oneplus]
[ro.common.soft]: [OnePlus8Pro]
[ro.display.series]: [OnePlus 8 Pro]
[ro.product.brand]: [OnePlus]
[ro.product.device]: [OnePlus8Pro]
[ro.product.manufacturer]: [OnePlus]
[ro.product.name]: [OnePlus8Pro_EEA]
[ro.product.odm.brand]: [OnePlus]
[ro.product.odm.device]: [OnePlus8Pro]
[ro.product.odm.manufacturer]: [OnePlus]
[ro.product.odm.name]: [OnePlus8Pro_EEA]
[ro.product.product.brand]: [OnePlus]
[ro.product.product.device]: [OnePlus8Pro]
[ro.product.product.manufacturer]: [OnePlus]
[ro.product.product.name]: [OnePlus8Pro_EEA]
[ro.product.system.brand]: [OnePlus]
[ro.product.system.device]: [OnePlus8Pro]
[ro.product.system.manufacturer]: [OnePlus]
[ro.product.system.name]: [OnePlus8Pro_EEA]
[ro.product.vendor.brand]: [OnePlus]
[ro.product.vendor.device]: [OnePlus8Pro]
[ro.product.vendor.manufacturer]: [OnePlus]
[ro.product.vendor.name]: [OnePlus8Pro_EEA]
```

**Comment by eliasnaur** [comment]
I'm not a big fan of querying big databases or hacking around with `getprop`. A simple solution for right now seems to me to be using some of the fields from [android.os.Build](https://developer.android.com/reference/android/os/Build.html) to contruct a reasonable device-specific name.

**Comment by JayDoubleu** [comment]
I like the idea. Still for all of the devices I would like to see either an ability to tag/alias at registration level or at least somehow uniquely identify all of my devices and group them.
