### ISSUE TITLE
Blank black or white screen on Android devices using OpenGL ES2 or similar

### ISSUE THREAD

**Issue by ohhai-kthxbai** [tailscale/tailscale#4332]
### What is the issue?

App shows a white screen on launch and is unresponsive.

### Steps to reproduce

Start the app!

### Are there any recent changes that introduced the issue?

No. Has been broken for a while (posts here from last year)

### OS

Android

### OS version

8.2.3

### Tailscale version

Version 1.22.0

**Comment by DentonGentry** [comment]
The app doesn't claim to support TV devices and the Play Store won't show it as available for a TV device.
Did you sideload it?

We expect to support TV devices in the future, possibly the near future, but 1.22.0 definitely does not.

**Comment by DentonGentry** [comment]
The 1.23.152 build currently in the Open Testing track adds Android TV support, and it is expected to be in the 1.24 general release. To get early access you'll need to join the [open testing track](https://play.google.com/apps/testing/com.tailscale.ipn).

For me at least, even being part of the Open Testing track still didn't show the app as available when searching for "tailscale" on my Google TV device. However in the Play Store app on my phone after installing 1.23.152, it said the app was available for some of my other devices and showed the Google TV in that list. It included an Install button, and a few minutes later the Google TV installed the app.

**Comment by ohhai-kthxbai** [comment]
Thank you for this Denton.

I've just tried the 1.23.152 build on my android TV (Nvidia Shield) and the same issue persists (white screen on launch, unresponsive). Happy to help with logs etc. if you can tell me how.

**Comment by ohhai-kthxbai** [comment]
Sorry, I didn't hit the 'reopen' button.

**Comment by DentonGentry** [comment]
I imagine we'll release 1.24 with Android TV support as it is now, and try to come back to NVidia Shield.

**Comment by baron0668** [comment]
I tried the beta version, 1.23.152, and also have the same issue.

```04-17 06:55:11.424  2676  3286 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LEANBACK_LAUNCHER] flg=0x10000000 pkg=com.tailscale.ipn cmp=com.tailscale.ipn/.IPNActivity} from uid 1000
04-17 06:55:11.425  3360  4455 D MonitorActivityController: ** Activity starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LEANBACK_LAUNCHER] pkg=com.tailscale.ipn cmp=com.tailscale.ipn/.IPNActivity } : com.tailscale.ipn
04-17 06:55:11.608  2676  2745 I ActivityManager: Start proc 7737:com.tailscale.ipn/u0a72 for activity com.tailscale.ipn/.IPNActivity
04-17 06:55:11.650  7737  7737 E m.tailscale.ip: Not starting debugger since process cannot load the jdwp agent.
04-17 06:55:11.869  7737  7737 W m.tailscale.ip: JIT profile information will not be recorded: profile file does not exits.
04-17 06:55:11.870  7737  7737 I chatty  : uid=10072(com.tailscale.ipn) identical 1 line
04-17 06:55:11.870  7737  7737 W m.tailscale.ip: JIT profile information will not be recorded: profile file does not exits.
04-17 06:55:12.646  7737  7752 I com.tailscale.ipn: logtail started
04-17 06:55:12.647  7737  7752 I com.tailscale.ipn: goSetupLogs: success
04-17 06:55:12.665  7737  7737 W m.tailscale.ipn: type=1400 audit(0.0:1011): avc: denied { search } for name="/" dev="tmpfs" ino=9572 scontext=u:r:untrusted_app:s0:c72,c256,c512,c768 tcontext=u:object_r:mt_tmp:s0 tclass=dir permissive=0
04-17 06:55:12.682  2613  2613 D MTK_KL  : 36,235238,31321606064,-;type=1400 audit(1650149712.665:1011): avc: denied { search } for pid=7737 comm="m.tailscale.ipn" name="/" dev="tmpfs" ino=9572 scontext=u:r:untrusted_app:s0:c72,c256,c512,c768 tcontext=u:object_r:mt_tmp:s0 tclass=dir permissive=0
04-17 06:55:12.783  7737  7754 I com.tailscale.ipn: 4.3M/78.5M dns: using *router.CallbackRouter
04-17 06:55:12.784  7737  7754 I com.tailscale.ipn: 4.3M/78.5M link state: interfaces.State{defaultRoute=wlan0 ifs={wlan0:[192.168.50.198/24 2001:b011:1004:1cd0:b6c9:b9ff:fe2a:cb78/64 2001:b011:1004:1cd0:fd34:3adc:96a2:4227/64]} v4=true v6=true}
04-17 06:55:12.790  7737  7754 I com.tailscale.ipn: 4.3M/78.5M magicsock: disco key = d:36148c8e07984fa9
04-17 06:55:12.790  7737  7754 I com.tailscale.ipn: 4.3M/78.5M Creating wireguard device...
04-17 06:55:12.800  7737  7754 I com.tailscale.ipn: 4.4M/79.0M Bringing wireguard device up...
04-17 06:55:12.806  7737  7760 I com.tailscale.ipn: 4.4M/79.0M Bringing router up...
04-17 06:55:12.806  7737  7760 I com.tailscale.ipn: 4.4M/79.0M Clearing router settings...
04-17 06:55:12.808  7737  7760 I com.tailscale.ipn: 4.4M/79.0M Starting link monitor...
04-17 06:55:12.810  7737  7760 I com.tailscale.ipn: 4.4M/79.0M Engine created.
04-17 06:55:12.833  7737  7737 W m.tailscale.ipn: type=1400 audit(0.0:1012): avc: denied { search } for name="821" dev="proc" ino=750741 scontext=u:r:untrusted_app:s0:c72,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c69,c256,c512,c768 tclass=dir permissive=0
04-17 06:55:12.845  2613  2613 D MTK_KL  : 36,235239,31321765513,-;type=1400 audit(1650149712.665:1011): avc: denied { search } for pid=7737 comm="m.tailscale.ipn" name="/" dev="tmpfs" ino=9572 scontext=u:r:untrusted_app:s0:c72,c256,c512,c768 tcontext=u:object_r:mt_tmp:s0 tclass=dir permissive=0
04-17 06:55:12.845  2613  2613 D MTK_KL  : 36,235240,31321765545,-;type=1400 audit(1650149712.833:1012): avc: denied { search } for pid=7737 comm="m.tailscale.ipn" name="821" dev="proc" ino=750741 scontext=u:r:untrusted_app:s0:c72,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c69,c256,c512,c768 tclass=dir permissive=0
04-17 06:55:12.877  7737  7737 W m.tailscale.ipn: type=1400 audit(0.0:1013): avc: denied { search } for name="3291" dev="proc" ino=848044 scontext=u:r:untrusted_app:s0:c72,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c63,c256,c512,c768 tclass=dir permissive=0
04-17 06:55:12.882  2613  2613 D MTK_KL  : 36,235241,31321809073,-;type=1400 audit(1650149712.833:1012): avc: denied { search } for pid=7737 comm="m.tailscale.ipn" name="821" dev="proc" ino=750741 scontext=u:r:untrusted_app:s0:c72,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c69,c256,c512,c768 tclass=dir permissive=0
04-17 06:55:12.882  2613  2613 D MTK_KL  : 36,235242,31321809099,-;type=1400 audit(1650149712.877:1013): avc: denied { search } for pid=7737 comm="m.tailscale.ipn" name="3291" dev="proc" ino=848044 scontext=u:r:untrusted_app:s0:c72,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c63,c256,c512,c768 tclass=dir permissive=0
04-17 06:55:12.882  2613  2613 D MTK_KL  : 36,235243,31321809320,-;type=1400 audit(1650149712.877:1013): avc: denied { search } for pid=7737 comm="m.tailscale.ipn" name="3291" dev="proc" ino=848044 scontext=u:r:untrusted_app:s0:c72,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c63,c256,c512,c768 tclass=dir permissive=0
04-17 06:55:12.877  7737  7737 W m.tailscale.ipn: type=1400 audit(0.0:1014): avc: denied { search } for name="3702" dev="proc" ino=848049 scontext=u:r:untrusted_app:s0:c72,c256,c512,c768 tcontext=u:r:secure_element:s0:c44,c260,c512,c768 tclass=dir permissive=0
04-17 06:55:12.895  7737  7767 I com.tailscale.ipn: 4.1M/81.4M Start
04-17 06:55:12.877  7737  7737 W m.tailscale.ipn: type=1400 audit(0.0:1015): avc: denied { search } for name="5419" dev="proc" ino=37812 scontext=u:r:untrusted_app:s0:c72,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c60,c256,c512,c768 tclass=dir permissive=0
04-17 06:55:12.898  2613  2613 D MTK_KL  : 36,235246,31321822054,-;type=1400 audit(1650149712.877:1014): avc: denied { search } for pid=7737 comm="m.tailscale.ipn" name="3702" dev="proc" ino=848049 scontext=u:r:untrusted_app:s0:c72,c256,c512,c768 tcontext=u:r:secure_element:s0:c44,c260,c512,c768 tclass=dir permissive=0
04-17 06:55:12.906  2613  2613 D MTK_KL  : 36,235247,31321831581,-;type=1400 audit(1650149712.877:1014): avc: denied { search } for pid=7737 comm="m.tailscale.ipn" name="3702" dev="proc" ino=848049 scontext=u:r:untrusted_app:s0:c72,c256,c512,c768 tcontext=u:r:secure_element:s0:c44,c260,c512,c768 tclass=dir permissive=0
04-17 06:55:12.906  2613  2613 D MTK_KL  : 36,235248,31321831608,-;type=1400 audit(1650149712.877:1015): avc: denied { search } for pid=7737 comm="m.tailscale.ipn" name="5419" dev="proc" ino=37812 scontext=u:r:untrusted_app:s0:c72,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c60,c256,c512,c768 tclass=dir permissive=0
04-17 06:55:12.983  7737  7747 I m.tailscale.ip: Background concurrent copying GC freed 8539(456KB) AllocSpace objects, 0(0B) LOS objects, 27% free, 1325KB/1837KB, paused 151us total 139.623ms
04-17 06:55:13.106  7737  7767 I com.tailscale.ipn: 4.1M/84.4M using backend prefs for "ipn-android": Prefs{ra=true dns=true want=false host="阿北" Persist=nil}
04-17 06:55:13.112  7737  7752 I com.tailscale.ipn: 4.2M/84.4M Backend: logs: be:5d941e25aef6376d2f30bfd8b23e67f2702fcd5f16e1af0e7ce1116a6414fde0 fe:
04-17 06:55:13.114  7737  7760 I com.tailscale.ipn: 4.2M/84.5M Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
04-17 06:55:13.116  7737  7755 I com.tailscale.ipn: 4.2M/84.5M blockEngineUpdates(true)
04-17 06:55:13.117  7737  7760 I com.tailscale.ipn: 4.2M/84.5M health("overall"): error: state=NeedsLogin, wantRunning=false
04-17 06:55:13.117  7737  7755 I com.tailscale.ipn: 4.2M/84.5M wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
04-17 06:55:13.118  7737  7755 I com.tailscale.ipn: 4.2M/84.5M wgengine: Reconfig: configuring router
04-17 06:55:13.154  7737  7752 I com.tailscale.ipn: 4.2M/85.4M wgengine: Reconfig: configuring DNS
04-17 06:55:13.155  7737  7760 I com.tailscale.ipn: fatal error: glGetError: 0x501
04-17 06:55:13.159  7737  7752 I com.tailscale.ipn: 4.2M/85.4M dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
04-17 06:55:13.161  7737  7752 I com.tailscale.ipn: 4.2M/85.4M dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
04-17 06:55:13.162  7737  7752 I com.tailscale.ipn: 4.2M/85.4M dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
04-17 06:55:13.271  2676  2742 I ActivityManager: Displayed com.tailscale.ipn/.IPNActivity: +1s804ms
04-17 06:55:13.382  7737  7767 I com.tailscale.ipn: 4.4M/86.9M SetPrefs: Prefs{ra=true dns=true want=false host="阿北" Persist=nil}
04-17 06:55:13.421  2450  2501 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.tailscale.ipn#0
04-17 06:55:13.422  2450  2501 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.tailscale.ipn#0```

**Comment by DentonGentry** [comment]
I imagine this is the root cause: `04-17 06:55:13.155  7737  7760 I com.tailscale.ipn: fatal error: glGetError: 0x501`

**Comment by salimhb** [comment]
I'm experiencing the same error `fatal error: glGetError: 0x501` on a HUAWEI P8 lite with Android 6.0 and version `1.24.0-tf0e71f4a2-g772e6ae6f06` from PlayStore

**Comment by RubenNL** [comment]
Experiencing the same error with a [ALCATEL 1T 10 WIFI](https://www.gsmarena.com/alcatel_1t_10-9093.php) tablet, Android 8.1.0, with Tailscale app version ["1.25.91-tfc5839864-g1845f173179"](https://github.com/tailscale/tailscale-android/commits/1.25.91-tfc5839864-g1845f173179).

**Comment by DentonGentry** [comment]
@RubenNL By "same error" do you mean you saw a log message of `fatal error: glGetError: 0x501` in `adb logcat`?
Or do you mean you saw a blank white screen?

**Comment by pentago** [comment]
Just wanted to check if anything goes on fo this issue?

**Comment by DentonGentry** [comment]
We will update the bug when there is progress. Right now we do not have a device which can produce the issue, which makes it difficult to make progress on.

**Comment by ohhai-kthxbai** [comment]
Maybe you could test on an older Fire TV Stick (the 4K and 4K Max version are on newer android versions and it works fine on them).

**Comment by kpcenti** [comment]
Black screen occurs on Xiomi MiBox 3 running Android Version 9

**Comment by kkkkkbruce** [comment]
Blank screen occurs on my Onn 2K TV Stick, Android TV Version 9 with both the Play Store and F-Droid version of the Tailscale app. It starts out grey/white and then goes black.

**Comment by eladbs** [comment]
Hey Devs!
I have a Xiaomi Mi Box 3 as well and I get a black screen also when I run the (play store) app.
Any way I can help investigate the issue to get things goin' 😊 ?

**Comment by axelov2** [comment]
Hi, same for me, have a Xiaomi MI BOX 3 and get a black screen.
ciao

**Comment by E-sinister07** [comment]
I´m having the same issue with a mi box s using Android 8.1

**Comment by ohhai-kthxbai** [comment]
8 months now, looks like this isn't getting fixed.
It's a shame as it would open up a lot of devices for tailscale use, inc. older fire sticks.

**Comment by DentonGentry** [comment]
We do not work simultaneously on every issue. For this issue we purchased a Samsung Galaxy S7 SM-G930F, one of the devices reported to experience the issue, but the version sold in the US apparently differs from versions sold in other regions and did not have any issue.

Developing on TV devices is more painful than for phones/tablets, we'd like to find a phone/tablet device where the issue can be produced. We currently have a lead on a Zenfone ZD552KL from elsewhere in the world which can be brought back to work on.

**Comment by ohhai-kthxbai** [comment]
I'll see if I can find an old phone or tablet that has the issue.

**Comment by agrieco** [comment]
> We do not work simultaneously on every issue. For this issue we purchased a Samsung Galaxy S7 SM-G930F, one of the devices reported to experience the issue, but the version sold in the US apparently differs from versions sold in other regions and did not have any issue.
> 
> Developing on TV devices is more painful than for phones/tablets, we'd like to find a phone/tablet device where the issue can be produced. We currently have a lead on a Zenfone ZD552KL from elsewhere in the world which can be brought back to work on.

I've got an older Amazon Fire stick that I'd happily donate to the cause if it will help.  It has this issue (glGetError: 0x501).  I've got a newer, Fire TV 4K works fine.

**Comment by happy1234567** [comment]
I have this issue on FireCube.. FireStick.. and my Mi Box.
 fatal error: glGetError: 0x501
I will there was a way around this??

**Comment by Shreyas-Dongre** [comment]
Hey everyone,
 I have Samsung Galaxy Tab 3 V SM-T116 NY (1GB ram & 8 GB Rom | chip: SC8830) model and gpu can support only till OpenGL ES 2.0 . I have custom lineage os 17 with android 7. I tried almost all versions of the app. I get the same black screen at startup and that's it.  I tried installing and checking all old versions and checked the logcat,  for the older versions  (i.e v1.22 (build 90) and lower versions [the ones with vulkan turned off] ) I get  the error _fatal error: no support for OpenGL ES 3 nor EXT_sRGB_ (i tried enabling srgb in developer mode, no change) but in the later newer builds (v1.23 higher | vulkan enabled) I get error _fatal error: glGetError: 0x501_  I really hope devs can make the app work with these type of old devices running opengl es 2.0. A lot of old devices would then be actually usable for this purpose.  I have included logcat of both versions below (before vulkan was disabled and after the vulkan was disabled)   

P.S: The os version and device name is different in logcat because of edited build.prop file.

v 1.35.8 (newer)
`--------- beginning of system
--------- beginning of crash
--------- beginning of main
12-31 23:17:03.132 29174 29193 I com.tailscale.ipn: logtail started
12-31 23:17:03.132 29174 29193 I com.tailscale.ipn: goSetupLogs: success
12-31 23:17:03.258 29174 29192 I com.tailscale.ipn: 5.1M/45.1M dns: using *router.CallbackRouter
12-31 23:17:03.260 29174 29192 I com.tailscale.ipn: 5.1M/45.1M link state: interfaces.State{defaultRoute=wlan0 ifs={wlan0:[192.168.1.19/24]} v4=true v6=false}
12-31 23:17:03.270 29174 29196 I com.tailscale.ipn: 4.1M/46.4M magicsock: disco key = d:dcd31d03cae65dc8
12-31 23:17:03.270 29174 29196 I com.tailscale.ipn: 4.1M/46.4M Creating wireguard device...
12-31 23:17:03.274 29174 29192 I com.tailscale.ipn: 4.2M/46.5M Bringing wireguard device up...
12-31 23:17:03.283 29174 29190 I com.tailscale.ipn: 4.3M/46.8M Bringing router up...
12-31 23:17:03.283 29174 29190 I com.tailscale.ipn: 4.3M/46.8M Clearing router settings...
12-31 23:17:03.289 29174 29190 I com.tailscale.ipn: 4.3M/46.8M Starting link monitor...
12-31 23:17:03.292 29174 29190 I com.tailscale.ipn: 4.3M/46.8M Engine created.
12-31 23:17:03.315 29174 29190 I com.tailscale.ipn: 4.3M/47.3M netmap packet filter: (not ready yet)
12-31 23:17:03.320 29174 29197 I com.tailscale.ipn: fatal error: glGetError: 0x501
12-31 23:17:03.326 29174 29197 I com.tailscale.ipn: 4.4M/47.6M Start
12-31 23:17:03.327 29174 29197 I com.tailscale.ipn: 4.4M/47.6M using backend prefs
12-31 23:17:03.526 29174 29197 I com.tailscale.ipn: 4.6M/49.2M backend prefs for "ipn-android": Prefs{ra=true dns=true want=false host="SM-T113NU" Persist=nil}
12-31 23:17:03.527 29174 29196 I com.tailscale.ipn: 4.6M/49.2M got initial portlist info in 0s
12-31 23:17:03.530 29174 29196 I com.tailscale.ipn: 4.6M/49.2M control: HostInfo: {"IPNVersion":"1.18.2-tb04815c9c-g08e1f97a38e","BackendLogID":"6b73cdfb632a7483916fd1dde49f163a3c6e2924f732f7a0c96a247e40160090","OS":"android","OSVersion":"10.1.2","DeviceModel":"samsung SM-T113NU","Hostname":"SM-T113NU","GoArch":"arm","Services":[{"Proto":"tcp","Port":16666}]}
12-31 23:17:03.531 29174 29196 I com.tailscale.ipn: 4.6M/49.2M Backend: logs: be:6b73cdfb632a7483916fd1dde49f163a3c6e2924f732f7a0c96a247e40160090 fe:
12-31 23:17:03.541 29174 29209 I com.tailscale.ipn: 4.6M/49.2M control: authRoutine: state:new; goal=nil paused=false
12-31 23:17:03.542 29174 29190 I com.tailscale.ipn: 4.6M/49.2M control: mapRoutine: state:new
12-31 23:17:03.543 29174 29190 I com.tailscale.ipn: 4.6M/49.2M Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
12-31 23:17:03.544 29174 29190 I com.tailscale.ipn: 4.6M/49.2M blockEngineUpdates(true)
12-31 23:17:03.546 29174 29190 I com.tailscale.ipn: 4.6M/49.2M wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
12-31 23:17:03.547 29174 29210 I com.tailscale.ipn: 4.6M/49.2M health("overall"): error: state=NeedsLogin, wantRunning=false
12-31 23:17:03.548 29174 29190 I com.tailscale.ipn: 4.6M/49.2M wgengine: Reconfig: configuring router
12-31 23:17:03.570 29174 29209 I com.tailscale.ipn: 4.7M/49.4M netmap packet filter: (not ready yet)
12-31 23:17:03.673 29174 29190 I com.tailscale.ipn: 4.7M/49.7M SetPrefs: Prefs{ra=true dns=true want=false host="SM-T113NU" Persist=nil}
12-31 23:17:03.675 29174 29190 I com.tailscale.ipn: 4.7M/49.7M authReconfig: blocked, skipping.
12-31 23:37:25.758 29174 29209 I com.tailscale.ipn: 2.8M/52.1M monitor: time jumped (probably wake from sleep); synthesizing major change event
12-31 23:37:25.759 29174 29198 I com.tailscale.ipn: 2.8M/52.1M LinkChange: major, rebinding. New state: interfaces.State{defaultRoute=wlan0 ifs={wlan0:[192.168.1.19/24 2402:e280:3d1d:49a:212:36ff:fe8f:d119/64 2402:e280:3d1d:49a:3130:6da5:ed15:1e2c/64]} v4=true v6=true}
12-31 23:37:25.847 29174 29210 I com.tailscale.ipn: 2.9M/52.1M control: HostInfo: {"IPNVersion":"1.18.2-tb04815c9c-g08e1f97a38e","BackendLogID":"6b73cdfb632a7483916fd1dde49f163a3c6e2924f732f7a0c96a247e40160090","OS":"android","OSVersion":"10.1.2","DeviceModel":"samsung SM-T113NU","Hostname":"SM-T113NU","GoArch":"arm"}
12-31 23:37:25.880 29174 29210 I com.tailscale.ipn: 2.9M/52.1M control: mapRoutine: new map needed while idle.
12-31 23:37:25.881 29174 29210 I com.tailscale.ipn: 2.9M/52.1M control: mapRoutine: state:new
12-31 23:39:08.991 30639 30658 I com.tailscale.ipn: logtail started
12-31 23:39:08.991 30639 30658 I com.tailscale.ipn: goSetupLogs: success
12-31 23:39:09.070 30639 30659 I com.tailscale.ipn: 4.1M/43.3M dns: using *router.CallbackRouter
12-31 23:39:09.072 30639 30659 I com.tailscale.ipn: 4.1M/43.3M link state: interfaces.State{defaultRoute=wlan0 ifs={wlan0:[192.168.1.19/24 2402:e280:3d1d:49a:212:36ff:fe8f:d119/64 2402:e280:3d1d:49a:3130:6da5:ed15:1e2c/64]} v4=true v6=true}
12-31 23:39:09.094 30639 30659 I com.tailscale.ipn: 4.1M/44.0M magicsock: disco key = d:e6017d1e4f50cdca
12-31 23:39:09.095 30639 30659 I com.tailscale.ipn: 4.1M/44.0M Creating wireguard device...
12-31 23:39:09.099 30639 30659 I com.tailscale.ipn: 4.2M/44.0M Bringing wireguard device up...
12-31 23:39:09.114 30639 30669 I com.tailscale.ipn: 4.3M/44.2M Bringing router up...
12-31 23:39:09.114 30639 30669 I com.tailscale.ipn: 4.3M/44.2M Clearing router settings...
12-31 23:39:09.115 30639 30669 I com.tailscale.ipn: 4.3M/44.2M Starting link monitor...
12-31 23:39:09.116 30639 30669 I com.tailscale.ipn: 4.3M/44.2M Engine created.
12-31 23:39:09.151 30639 30669 I com.tailscale.ipn: 4.3M/45.0M netmap packet filter: (not ready yet)
12-31 23:39:09.162 30639 30658 I com.tailscale.ipn: 4.5M/45.4M Start
12-31 23:39:09.169 30639 30658 I com.tailscale.ipn: 4.5M/45.7M using backend prefs
12-31 23:39:09.260 30639 30658 I com.tailscale.ipn: 4.0M/47.8M backend prefs for "ipn-android": Prefs{ra=true dns=true want=false host="SM-T113NU" Persist=nil}
12-31 23:39:09.263 30639 30658 I com.tailscale.ipn: 4.0M/48.0M got initial portlist info in 0s
12-31 23:39:09.266 30639 30658 I com.tailscale.ipn: 4.0M/48.3M control: HostInfo: {"IPNVersion":"1.18.2-tb04815c9c-g08e1f97a38e","BackendLogID":"6b73cdfb632a7483916fd1dde49f163a3c6e2924f732f7a0c96a247e40160090","OS":"android","OSVersion":"10.1.2","DeviceModel":"samsung SM-T113NU","Hostname":"SM-T113NU","GoArch":"arm","Services":[{"Proto":"tcp","Port":16666}]}
12-31 23:39:09.267 30639 30658 I com.tailscale.ipn: 4.0M/48.3M Backend: logs: be:6b73cdfb632a7483916fd1dde49f163a3c6e2924f732f7a0c96a247e40160090 fe:
12-31 23:39:09.269 30639 30674 I com.tailscale.ipn: 4.0M/48.3M control: authRoutine: state:new; goal=nil paused=false
12-31 23:39:09.272 30639 30674 I com.tailscale.ipn: 4.0M/48.3M control: mapRoutine: state:new
12-31 23:39:09.274 30639 30674 I com.tailscale.ipn: 4.0M/48.3M Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
12-31 23:39:09.276 30639 30674 I com.tailscale.ipn: 4.0M/48.3M blockEngineUpdates(true)
12-31 23:39:09.281 30639 30674 I com.tailscale.ipn: 4.0M/48.5M wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
12-31 23:39:09.282 30639 30657 I com.tailscale.ipn: 4.0M/48.7M health("overall"): error: state=NeedsLogin, wantRunning=false
12-31 23:39:09.283 30639 30657 I com.tailscale.ipn: fatal error: glGetError: 0x501
12-31 23:39:09.283 30639 30663 I com.tailscale.ipn: 4.0M/48.8M wgengine: Reconfig: configuring router
12-31 23:39:09.290 30639 30669 I com.tailscale.ipn: 4.0M/48.9M wgengine: Reconfig: configuring DNS
12-31 23:39:09.292 30639 30669 I com.tailscale.ipn: 4.0M/48.9M dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
12-31 23:39:09.293 30639 30669 I com.tailscale.ipn: 4.0M/49.2M dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
12-31 23:39:09.295 30639 30669 I com.tailscale.ipn: 4.0M/49.2M dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
12-31 23:39:09.323 30639 30659 I com.tailscale.ipn: 4.0M/49.4M netmap packet filter: (not ready yet)
12-31 23:39:09.438 30639 30658 I com.tailscale.ipn: 4.1M/49.7M SetPrefs: Prefs{ra=true dns=true want=false host="SM-T113NU" Persist=nil}
12-31 23:39:09.440 30639 30658 I com.tailscale.ipn: 4.1M/49.7M authReconfig: blocked, skipping.
12-31 23:40:19.269 30639 30669 I com.tailscale.ipn: 3.3M/50.7M control: HostInfo: {"IPNVersion":"1.18.2-tb04815c9c-g08e1f97a38e","BackendLogID":"6b73cdfb632a7483916fd1dde49f163a3c6e2924f732f7a0c96a247e40160090","OS":"android","OSVersion":"10.1.2","DeviceModel":"samsung SM-T113NU","Hostname":"SM-T113NU","GoArch":"arm"}
12-31 23:40:19.271 30639 30658 I com.tailscale.ipn: 3.3M/50.7M control: mapRoutine: new map needed while idle.
12-31 23:40:19.271 30639 30658 I com.tailscale.ipn: 3.3M/50.7M control: mapRoutine: state:new


 
`


v  1.2.2 (older)  

`
--------- beginning of system
--------- beginning of crash
--------- beginning of main
01-01 00:35:57.894  3247  3267 I com.tailscale.ipn: logtail started
01-01 00:35:57.895  3247  3267 I com.tailscale.ipn: goSetupLogs: success
01-01 00:35:57.948  3247  3263 I com.tailscale.ipn: 4.3M/44.0M link state: interfaces.State{defaultRoute=wlan0 ifs={p2p0:[] wlan0:[192.168.1.19 2402:e280:3d1d:49a:3130:6da5:ed15:1e2c 2402:e280:3d1d:49a:212:36ff:fe8f:d119]} v4=true v6global=true}
01-01 00:35:58.060  3247  3263 I com.tailscale.ipn: fatal error: no support for OpenGL ES 3 nor EXT_sRGB
01-01 00:35:58.082  3247  3267 I com.tailscale.ipn: 4.6M/45.3M Creating wireguard device...
01-01 00:35:58.197  3247  3263 I com.tailscale.ipn: 10.9M/48.1M Routine: event worker - started
01-01 00:35:58.202  3247  3263 I com.tailscale.ipn: 10.9M/48.1M Creating router...
01-01 00:35:58.203  3247  3263 I com.tailscale.ipn: 10.8M/48.1M Bringing wireguard device up...
01-01 00:35:58.205  3247  3267 I com.tailscale.ipn: 10.8M/48.1M UDP bind has been updated
01-01 00:35:58.205  3247  3267 I com.tailscale.ipn: 10.8M/48.1M Bringing router up...
01-01 00:35:58.206  3247  3267 I com.tailscale.ipn: 10.8M/48.1M Clearing router settings...
01-01 00:35:58.206  3247  3267 I com.tailscale.ipn: 10.8M/48.1M Starting link monitor...
01-01 00:35:58.207  3247  3267 I com.tailscale.ipn: 10.8M/48.1M Starting magicsock...
01-01 00:35:58.212  3247  3267 I com.tailscale.ipn: 10.8M/48.3M Starting resolver...
01-01 00:35:58.215  3247  3269 I com.tailscale.ipn: 10.9M/48.3M magicsock: starting endpoint update (initial)
01-01 00:35:58.217  3247  3267 I com.tailscale.ipn: 11.0M/48.3M Engine created.
01-01 00:35:58.238  3247  3269 I com.tailscale.ipn: 11.1M/48.6M Start
01-01 00:35:58.240  3247  3267 I com.tailscale.ipn: 11.1M/48.6M magicsock: ignoring pre-DERP map, STUN-less endpoint update: [192.168.1.19:46389]
01-01 00:35:58.241  3247  3267 I com.tailscale.ipn: 11.2M/48.6M using backend prefs
01-01 00:35:58.320  3247  3266 I com.tailscale.ipn: 11.2M/49.1M LinkChange: minor
01-01 00:35:58.322  3247  3266 I com.tailscale.ipn: 11.2M/49.1M magicsock: starting endpoint update (link-change-minor)
01-01 00:35:58.328  3247  3266 I com.tailscale.ipn: 11.3M/49.1M magicsock: ignoring pre-DERP map, STUN-less endpoint update: [192.168.1.19:46389]
01-01 00:35:58.342  3247  3267 I com.tailscale.ipn: 11.3M/49.1M created empty state for "ipn-android": Prefs{ra=true dns=true want=true Persist=nil}
01-01 00:35:58.422  3247  3267 I com.tailscale.ipn: 11.3M/49.3M generating new machine key
01-01 00:35:58.494  3247  3267 I com.tailscale.ipn: 11.3M/49.3M machine key written to store
01-01 00:35:58.495  3247  3267 I com.tailscale.ipn: 11.3M/49.3M netmap packet filter: (not ready yet)
01-01 00:35:58.497  3247  3267 I com.tailscale.ipn: 11.3M/49.3M got initial portlist info in 1ms
01-01 00:35:58.503  3247  3267 I com.tailscale.ipn: 11.3M/49.3M magicsock: disco key = d:0a4c48a396fcce0d
01-01 00:35:58.505  3247  3267 I com.tailscale.ipn: 11.3M/49.5M control: HostInfo: {"IPNVersion":"1.2.2-t76c2982d8-g97a826d11","BackendLogID":"44aecd5778e14b867dfa43915074cf0d291b97bafb59e4b2ebae6c329d545922","OS":"android","Hostname":"localhost","GoArch":"arm","Services":[{"Proto":"tcp","Port":16666}]}
01-01 00:35:58.506  3247  3267 I com.tailscale.ipn: 11.3M/49.5M Backend: logs: be:44aecd5778e14b867dfa43915074cf0d291b97bafb59e4b2ebae6c329d545922 fe:
01-01 00:35:58.507  3247  3263 I com.tailscale.ipn: 11.3M/49.5M control: authRoutine: state:new
01-01 00:35:58.508  3247  3267 I com.tailscale.ipn: 11.3M/49.5M control: client.Login(false, 0)
01-01 00:35:58.508  3247  3267 I com.tailscale.ipn: 11.3M/49.5M control: mapRoutine: state:new
01-01 00:35:58.510  3247  3267 I com.tailscale.ipn: 11.3M/49.5M control: authRoutine: context done.
01-01 00:35:58.510  3247  3267 I com.tailscale.ipn: 11.3M/49.5M control: authRoutine: state:new
01-01 00:35:58.511  3247  3267 I com.tailscale.ipn: 11.3M/49.5M control: direct.TryLogin(token=false, flags=0)
01-01 00:35:58.511  3247  3267 I com.tailscale.ipn: 11.3M/49.5M control: doLogin(regen=false, hasUrl=false)
01-01 00:35:58.615  3247  3288 I com.tailscale.ipn: 11.5M/52.3M SetPrefs: Prefs{ra=true dns=true want=true Persist=nil}
01-01 00:35:58.616  3247  3288 I com.tailscale.ipn: 11.5M/52.3M control: HostInfo: {"IPNVersion":"1.2.2-t76c2982d8-g97a826d11","BackendLogID":"44aecd5778e14b867dfa43915074cf0d291b97bafb59e4b2ebae6c329d545922","OS":"android","OSVersion":"10.1.2","DeviceModel":"samsung SM-T113NU","Hostname":"SM-T113NU","GoArch":"arm","Services":[{"Proto":"tcp","Port":16666}]}
01-01 00:35:58.616  3247  3288 I com.tailscale.ipn: 11.5M/52.3M control: Hostinfo: &{1.2.2-t76c2982d8-g97a826d11  44aecd5778e14b867dfa43915074cf0d291b97bafb59e4b2ebae6c329d545922 android 10.1.2 samsung SM-T113NU SM-T113NU arm [] [] [{[] tcp 16666 }] NetInfo(nil)}
01-01 00:35:58.617  3247  3288 I com.tailscale.ipn: 11.5M/52.3M control: cancelMapSafely: synced=false
01-01 00:35:58.617  3247  3288 I com.tailscale.ipn: 11.5M/52.3M control: cancelMapSafely: wrote to channel
01-01 00:35:58.618  3247  3263 I com.tailscale.ipn: 11.5M/52.3M control: mapRoutine: new map needed while idle.
01-01 00:35:58.619  3247  3288 I com.tailscale.ipn: 11.5M/52.3M netmap packet filter: (not ready yet)
01-01 00:35:58.620  3247  3263 I com.tailscale.ipn: 11.5M/52.3M control: mapRoutine: state:authenticating
01-01 00:35:58.620  3247  3263 I com.tailscale.ipn: 11.5M/52.3M authReconfig: netmap not yet valid. Skipping.
01-01 00:35:59.596  3247  3266 I com.tailscale.ipn: 13.9M/55.8M control: Generating a new nodekey.
01-01 00:35:59.602  3247  3266 I com.tailscale.ipn: 13.9M/55.8M control: RegisterReq: onode=[AAAAA] node=[C1fm8] fup=false
01-01 00:35:59.759  3247  3270 I com.tailscale.ipn: 14.4M/55.8M control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=false; authURL=true
01-01 00:35:59.760  3247  3270 I com.tailscale.ipn: 14.4M/55.8M control: AuthURL is https://login.tailscale.com/a/64517d5968a4
01-01 00:35:59.760  3247  3270 I com.tailscale.ipn: 14.4M/55.8M control: sendStatus: authRoutine-url: state:url-visit-required
01-01 00:35:59.760  3247  3270 I com.tailscale.ipn: 14.4M/55.8M Received auth URL: https://login.tailsc...
01-01 00:35:59.761  3247  3270 I com.tailscale.ipn: 14.4M/55.8M Switching ipn state NoState -> NeedsLogin (WantRunning=true)
01-01 00:35:59.762  3247  3270 I com.tailscale.ipn: 14.4M/55.8M blockEngineUpdates(true)
01-01 00:35:59.763  3247  3270 I com.tailscale.ipn: 14.4M/55.8M wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
01-01 00:35:59.763  3247  3270 I com.tailscale.ipn: 14.4M/55.8M UDP bind update skipped
01-01 00:35:59.764  3247  3270 I com.tailscale.ipn: 14.4M/55.8M wgengine: Reconfig: configuring router
01-01 00:35:59.765  3247  3270 I com.tailscale.ipn: 14.4M/55.8M wgengine: Reconfig done
01-01 00:35:59.765  3247  3270 I com.tailscale.ipn: 14.4M/55.8M authReconfig: blocked, skipping.
01-01 00:35:59.765  3247  3270 I com.tailscale.ipn: 14.4M/55.8M control: authRoutine: state:url-visit-required
01-01 00:35:59.766  3247  3270 I com.tailscale.ipn: 14.4M/55.8M control: direct.WaitLoginURL
01-01 00:35:59.766  3247  3270 I com.tailscale.ipn: 14.4M/55.8M control: doLogin(regen=false, hasUrl=true)
01-01 00:35:59.771  3247  3270 I com.tailscale.ipn: 14.4M/55.8M control: RegisterReq: onode=[AAAAA] node=[C1fm8] fup=true
01-01 00:37:08.788  3356  3378 I com.tailscale.ipn: logtail started
01-01 00:37:08.793  3356  3378 I com.tailscale.ipn: goSetupLogs: success
01-01 00:37:08.874  3356  3377 I com.tailscale.ipn: 4.2M/42.3M link state: interfaces.State{defaultRoute=wlan0 ifs={p2p0:[] wlan0:[192.168.1.19 2402:e280:3d1d:49a:3130:6da5:ed15:1e2c 2402:e280:3d1d:49a:212:36ff:fe8f:d119]} v4=true v6global=true}
01-01 00:37:09.073  3356  3379 I com.tailscale.ipn: 4.6M/43.9M Creating wireguard device...
01-01 00:37:09.193  3356  3377 I com.tailscale.ipn: 12.9M/46.4M Routine: event worker - started
01-01 00:37:09.197  3356  3378 I com.tailscale.ipn: 12.9M/46.4M Creating router...
01-01 00:37:09.199  3356  3378 I com.tailscale.ipn: 12.9M/46.4M Bringing wireguard device up...
01-01 00:37:09.200  3356  3378 I com.tailscale.ipn: 12.9M/46.4M UDP bind has been updated
01-01 00:37:09.201  3356  3378 I com.tailscale.ipn: 12.9M/46.4M Bringing router up...
01-01 00:37:09.201  3356  3378 I com.tailscale.ipn: 12.9M/46.4M Clearing router settings...
01-01 00:37:09.202  3356  3378 I com.tailscale.ipn: 12.9M/46.4M Starting link monitor...
01-01 00:37:09.205  3356  3378 I com.tailscale.ipn: 12.9M/46.5M Starting magicsock...
01-01 00:37:09.206  3356  3378 I com.tailscale.ipn: 12.9M/46.5M Starting resolver...
01-01 00:37:09.207  3356  3378 I com.tailscale.ipn: 13.0M/46.5M Engine created.
01-01 00:37:09.209  3356  3385 I com.tailscale.ipn: 13.0M/46.5M magicsock: starting endpoint update (initial)
01-01 00:37:09.218  3356  3385 I com.tailscale.ipn: 13.1M/46.8M magicsock: ignoring pre-DERP map, STUN-less endpoint update: [192.168.1.19:36891]
01-01 00:37:09.226  3356  3378 I com.tailscale.ipn: fatal error: no support for OpenGL ES 3 nor EXT_sRGB
01-01 00:37:09.229  3356  3385 I com.tailscale.ipn: 13.1M/47.1M Start
01-01 00:37:09.231  3356  3385 I com.tailscale.ipn: 13.1M/47.1M using backend prefs
01-01 00:37:09.354  3356  3375 I com.tailscale.ipn: 13.2M/48.1M LinkChange: minor
01-01 00:37:09.355  3356  3382 I com.tailscale.ipn: 13.2M/48.2M magicsock: starting endpoint update (link-change-minor)
01-01 00:37:09.359  3356  3382 I com.tailscale.ipn: 13.2M/48.2M magicsock: ignoring pre-DERP map, STUN-less endpoint update: [192.168.1.19:36891]
01-01 00:37:09.398  3356  3385 I com.tailscale.ipn: 13.2M/48.3M backend prefs for "ipn-android": Prefs{ra=true dns=true want=true Persist=nil}
01-01 00:37:09.494  3356  3385 I com.tailscale.ipn: 13.7M/49.2M netmap packet filter: (not ready yet)
01-01 00:37:09.495  3356  3385 I com.tailscale.ipn: 13.8M/49.2M got initial portlist info in 0s
01-01 00:37:09.511  3356  3378 I com.tailscale.ipn: 13.8M/49.2M magicsock: disco key = d:e08a5247f00d31e9
01-01 00:37:09.514  3356  3378 I com.tailscale.ipn: 13.9M/49.4M control: HostInfo: {"IPNVersion":"1.2.2-t76c2982d8-g97a826d11","BackendLogID":"44aecd5778e14b867dfa43915074cf0d291b97bafb59e4b2ebae6c329d545922","OS":"android","OSVersion":"10.1.2","DeviceModel":"samsung SM-T113NU","Hostname":"SM-T113NU","GoArch":"arm","Services":[{"Proto":"tcp","Port":16666}]}
01-01 00:37:09.517  3356  3375 I com.tailscale.ipn: 13.9M/49.4M control: authRoutine: state:new
01-01 00:37:09.518  3356  3375 I com.tailscale.ipn: 13.9M/49.4M control: mapRoutine: state:new
01-01 00:37:09.519  3356  3375 I com.tailscale.ipn: 13.9M/49.4M Backend: logs: be:44aecd5778e14b867dfa43915074cf0d291b97bafb59e4b2ebae6c329d545922 fe:
01-01 00:37:09.520  3356  3375 I com.tailscale.ipn: 13.9M/49.4M control: client.Login(false, 0)
01-01 00:37:09.539  3356  3379 I com.tailscale.ipn: 13.9M/49.4M control: authRoutine: context done.
01-01 00:37:09.547  3356  3379 I com.tailscale.ipn: 14.1M/49.6M control: authRoutine: state:new
01-01 00:37:09.548  3356  3379 I com.tailscale.ipn: 14.1M/49.6M control: direct.TryLogin(token=false, flags=0)
01-01 00:37:09.550  3356  3379 I com.tailscale.ipn: 14.1M/49.6M control: doLogin(regen=false, hasUrl=false)
01-01 00:37:09.775  3356  3375 I com.tailscale.ipn: 15.3M/51.4M SetPrefs: Prefs{ra=true dns=true want=true Persist=nil}
01-01 00:37:09.776  3356  3375 I com.tailscale.ipn: 15.3M/51.4M netmap packet filter: (not ready yet)
01-01 00:37:09.787  3356  3375 I com.tailscale.ipn: 15.3M/51.4M authReconfig: netmap not yet valid. Skipping.
01-01 00:37:10.370  3356  3375 I com.tailscale.ipn: 15.8M/52.8M control: Generating a new nodekey.
01-01 00:37:10.384  3356  3375 I com.tailscale.ipn: 15.8M/52.8M control: RegisterReq: onode=[AAAAA] node=[WK11R] fup=false
01-01 00:37:10.526  3356  3379 I com.tailscale.ipn: 16.4M/52.9M control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=false; authURL=true
01-01 00:37:10.527  3356  3379 I com.tailscale.ipn: 16.4M/52.9M control: AuthURL is https://login.tailscale.com/a/39b11b77ba63
01-01 00:37:10.527  3356  3379 I com.tailscale.ipn: 16.4M/52.9M control: sendStatus: authRoutine-url: state:url-visit-required
01-01 00:37:10.528  3356  3379 I com.tailscale.ipn: 16.4M/52.9M Received auth URL: https://login.tailsc...
01-01 00:37:10.528  3356  3379 I com.tailscale.ipn: 16.4M/52.9M Switching ipn state NoState -> NeedsLogin (WantRunning=true)
01-01 00:37:10.530  3356  3375 I com.tailscale.ipn: 16.4M/52.9M blockEngineUpdates(true)
01-01 00:37:10.533  3356  3375 I com.tailscale.ipn: 16.4M/52.9M wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
01-01 00:37:10.534  3356  3375 I com.tailscale.ipn: 16.4M/52.9M UDP bind update skipped
01-01 00:37:10.534  3356  3375 I com.tailscale.ipn: 16.4M/52.9M wgengine: Reconfig: configuring router
01-01 00:37:10.535  3356  3375 I com.tailscale.ipn: 16.4M/52.9M wgengine: Reconfig done
01-01 00:37:10.536  3356  3375 I com.tailscale.ipn: 16.4M/52.9M authReconfig: blocked, skipping.
01-01 00:37:10.536  3356  3375 I com.tailscale.ipn: 16.4M/52.9M control: authRoutine: state:url-visit-required
01-01 00:37:10.537  3356  3375 I com.tailscale.ipn: 16.4M/52.9M control: direct.WaitLoginURL
01-01 00:37:10.537  3356  3375 I com.tailscale.ipn: 16.4M/52.9M control: doLogin(regen=false, hasUrl=true)
01-01 00:37:10.542  3356  3375 I com.tailscale.ipn: 16.4M/52.9M control: RegisterReq: onode=[AAAAA] node=[WK11R] fup=true
`

**Comment by DentonGentry** [comment]
No solution but capturing notes from debugging. Working with an Amazon FireTV from 2018 and a locally compiled Gio.

The first problem is triggered in [queryState()](https://git.sr.ht/~eliasnaur/gio/tree/main/item/gpu/internal/opengl/opengl.go#L312). Merely retrieving UNPACK_ROW_LENGTH or PACK_ROW_LENGTH causes glGet to return the 0x501 error the next time it is called. If I set the pack and unpack lengths in glState to 0 without fetching them, it gets a little further:
```
	s := glState{
		...
		viewport:          b.funcs.GetInteger4(gl.VIEWPORT),
		unpack_row_length: 0,
		pack_row_length:   0,
	}
```

This moves the problem to [BeginFrame](https://git.sr.ht/~eliasnaur/gio/tree/main/item/gpu/internal/opengl/opengl.go#L250). Calling `GetFramebufferAttachmentParameteri(..., gl.FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING)` causes glGet to return the 0x501 error the next time it is called. I tried making it take the !b.gles path through https://git.sr.ht/~eliasnaur/gio/tree/main/item/gpu/internal/opengl/opengl.go#L271, but that results in a 0x500 error.

**Comment by DentonGentry** [comment]
The UNPACK_ROW_LENGTH issue was fixed by https://git.sr.ht/~eliasnaur/gio/commit/1a84517
The FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING issue was fixed by https://git.sr.ht/~eliasnaur/gio/commit/f8221bb

We get further now, the next failure occurs when it tries to create a texture in `newCompute()`:

```
null, err := ctx.NewTexture(driver.TextureFormatRGBA8, 1, 1, driver.FilterNearest, driver.FilterNearest, driver.BufferBindingShaderStorageRead)
```


We've tried a few things to try to narrow down what specifically the problem is:
- using `driver.BufferBindingUniforms` instead of `BufferBindingShaderStorageRead` (I believe Shader Storage was added in OpenGL 3.1)
- using `TextureFormatSRGBA` instead of RGBA8
- using `FilterLinear` instead of `FilterNearest`
- making the texture 2x2

Completely commenting out the NewTexture from newCompute just moves the error to the first texture it tries to allocate when it renders the first frame, so the problem doesn't appear to be specific to this one texture.

**Comment by happy1234567** [comment]
So I can install Tailscale via SSH on  linux.. ..  would there be a way to install and setup Tailscale from ADB and not have to use the GUI in the Tailscale app

**Comment by DentonGentry** [comment]
Unfortunately the CLI utility like `tailscale` on Linux doesn't exist in the Android app, and the Android equivalent of `tailscaled` doesn't listen on the interfaces it would need in order for a `tailscale` CLI to function (I'm not confident the Android security model even allows those interfaces between separate processes). I don't think that is a viable way to proceed.

**Comment by DentonGentry** [comment]
[af7afea](https://git.sr.ht/~eliasnaur/gio/commit/af7afea) removed the NewTexture from the CPU rendering path. After rebasing to main, the glErr 0x501 now occurs when NewTexture is called from `(*textureAtlas).resize`

We've tried varying the parameters, without discovering the root cause for OpenGL to complain that something is invalid:

- force driver.BufferBindingTexture
- force driver.TextureFormatSRGBA
- setting the height and width to a power of 2 (apparently [most ES2 devices can only handle power-of-2 textures](https://stackoverflow.com/questions/17996880/creating-texture-atlas-error-opengl-es-2-0-android))

```
panic: glGetError: 0x501

goroutine 17 [running, locked to thread]:
gioui.org/gpu/internal/opengl.glErr(0x8ad1b100)
        /home/dgentry/Documents/Code/tailscale/gio/gpu/internal/opengl/opengl.go:846 +0xc4
gioui.org/gpu/internal/opengl.(*Backend).NewTexture(0x8b410900, 0x2, 0x401, 0xcb, 0x0, 0x0, 0x18)
        /home/dgentry/Documents/Code/tailscale/gio/gpu/internal/opengl/opengl.go:797 +0x434
gioui.org/gpu.(*textureAtlas).resize(0x8b9946e0, {0xcf658334, 0x8b410900}, {0x401, 0xcb})
        /home/dgentry/Documents/Code/tailscale/gio/gpu/compute.go:1455 +0x60
gioui.org/gpu.(*compute).realizeAtlas(0x8bbae000, 0x8b9946e0, 0x0, {0x401, 0xcb})
        /home/dgentry/Documents/Code/tailscale/gio/gpu/compute.go:1446 +0xe0
gioui.org/gpu.(*compute).uploadImages(0x8bbae000)
        /home/dgentry/Documents/Code/tailscale/gio/gpu/compute.go:1088 +0x184
gioui.org/gpu.(*compute).frame(0x8bbae000, {0xcf6511f4, 0xcfaf8420})
        /home/dgentry/Documents/Code/tailscale/gio/gpu/compute.go:607 +0x250
gioui.org/gpu.(*compute).Frame(0x8bbae000, 0x8ad95724, {0xcf6511f4, 0xcfaf8420}, {0x780, 0x438})
        /home/dgentry/Documents/Code/tailscale/gio/gpu/compute.go:578 +0x5c
gioui.org/app.(*Window).frame(0x8ad95500, 0x8ad95724, {0x780, 0x438})
        /home/dgentry/Documents/Code/tailscale/gio/app/window.go:303 +0xb4
gioui.org/app.(*Window).validateAndProcess(0x8ad95500, {0xcf657870, 0x8add8380}, {0x780, 0x438}, 0x1, 0x8ad95724, 0x0)
        /home/dgentry/Documents/Code/tailscale/gio/app/window.go:264 +0x314
gioui.org/app.(*Window).processEvent(0x8ad95500, {0xcf657870, 0x8add8380}, {0xcf651168, 0x8ad4a0a0})
        /home/dgentry/Documents/Code/tailscale/gio/app/window.go:894 +0xdd8
gioui.org/app.(*callbacks).Event(0x8ad957ac, {0xcf651168, 0x8ad4a0a0})
        /home/dgentry/Documents/Code/tailscale/gio/app/window.go:487 +0x144
gioui.org/app.(*window).draw(0x8add8380, 0xeb5a32a0, 0x1)
        /home/dgentry/Documents/Code/tailscale/gio/app/os_android.go:844 +0x1f8
        /ho
gioui.org/app.(*window).setVisible(0x8add8380, 0xeb5a32a0)
 success
gioui.org/app.Java_org_gioui_GioView_onSurfaceChanged(0xeb5a32a0, 0xffc1014c, 0x1, 0xffc10150)
gioui.org
        /home/dgentry/Documents/Code/tailscale/gio/app/os_android.go:541 +0xa0
```

**Comment by DentonGentry** [comment]
No recent progress on https://todo.sr.ht/~eliasnaur/gio/469

**Comment by probonopd** [comment]
Also running into the black screen on a Mediatek tablet.

**Comment by axelov2** [comment]
Someone explain to me how the developers of Tailscale can have any credibility if they cannot get the software to work on devices that are not sooooo old. Truly disappointing !!!!

**Comment by DentonGentry** [comment]
The Android app uses https://gioui.org for its UI, which does not implement OpenGL ES2 support.
Devices whose graphics support uses OpenGL ES2 do not render.
The recent effort in this area is tracked in https://todo.sr.ht/~eliasnaur/gio/469

**Comment by probonopd** [comment]
Does a networking tool really need more fancy graphics than what, say, Android 4 already provided?

**Comment by bradfitz** [comment]
> Does a networking tool really need more fancy graphics than what, say, Android 4 already provided?

Absolutely not. But that UI library is what the original Tailscale Android app was built with, and in retrospect it was probably the wrong choice. It's caused too many problems.

We'll probably replace it with stock Android GUI components if/when we hire an Android person: https://boards.greenhouse.io/tailscale/jobs/4179821005

**Comment by LucasMZReal** [comment]
> > Does a networking tool really need more fancy graphics than what, say, Android 4 already provided?
> 
> Absolutely not. But that UI library is what the original Tailscale Android app was built with, and in retrospect it was probably the wrong choice. It's caused too many problems.
> 
> We'll probably replace it with stock Android GUI components if/when we hire an Android person: https://boards.greenhouse.io/tailscale/jobs/4179821005

I see the position's no longer open, are you guys working on it? 👀

**Comment by DentonGentry** [comment]
We understand the desire for a fix. We will post here when progress is made. Hiring, onboarding, and ramping up take longer than the turnaround time between GitHub comments.

**Comment by cgarciaq** [comment]
+1. Blank screen on a Mi Box S... I keep coming here from time to time to see if it gets solved but I understand this is not receiving much attention.

**Comment by ideasman69** [comment]
Just run into this while trying to run on a Vodafone TV android box for my elderly parents to access media from our place. 

If there was a workaround to at least allow the adding of the device to an account, via ADB for example- that would be great in the interim. 

Anyone know if that’s possible?

**Comment by geodic** [comment]
The only workaround that I currently know of is as follows:
1. Root the device using Magisk
2. Install the [Tailscale Magisk module](https://xdaforums.com/t/module-magisk-tailscaled-running-tailscale-on-android-with-root.4645949/)
3. Open a terminal (this is easier on custom ROMs) and run `tailscale login`
4. Navigate to the link and log in to your tailnet to add the device

This solution might be too complicated for most use cases, but worked for my old tablet that doesn't support OpenGL 3.

**Comment by mbarrin** [comment]
I was able to install Tailscale via the android webstore onto my Shield.

Haven't had any major issues, the UI can be a bit fiddly, but using the Shield app on my phone in cursor mode gets around a lot of that.

**Comment by kpcenti** [comment]
> I was able to install Tailscale via the android webstore onto my Shield.
> 
> Haven't had any major issues, the UI can be a bit fiddly, but using the Shield app on my phone in cursor mode gets around a lot of that.

Nvidia Shield is an exception that works on. It's still broken on other devices including other Android TV OS devices.

**Comment by agottardo** [comment]
This should now be resolved on [the new Android app](https://mastodon.social/@tailscale@hachyderm.io/112259739383441517), since it no longer uses Gio for the UI. Please test it out and let us know!

**Comment by jzazo** [comment]
Can you enable the beta for Android TV as well? Cannot be installed at the moment.

**Comment by Najihel** [comment]
> This should now be resolved on [the new Android app](https://mastodon.social/@tailscale@hachyderm.io/112259739383441517), since it no longer uses Gio for the UI. Please test it out and let us know!

Hello, TailScale app isn't available anymore on PlayStore for Xiaomi Mibox S device. Is it possible to reenable app beta publication for this device ? Thanks

**Comment by StevenDTX** [comment]
I still have this problem on an Nvidia Shield Pro 2017 (8.23).  I still cannot install via the Play Store. I sideloaded 1.62.0.

**Comment by duprees** [comment]
MiTV 55”, Android 9. Sideloaded 1.64. Wiem I start the app, I see white background, black ground and then app is closing on it’s own. On older versions the app never stopped.

**Comment by anarkia47** [comment]
Sideloaded latest version, but still not working on fire TV stick..

It loads white screen then black screen, then it closes...

**Comment by duprees** [comment]
Sideloaded  1.65.95 on android 9 tv, now it’s working correctly.

**Comment by hannayusuf97** [comment]
@duprees  I am still stuck on android 9 tv, how did you sideload it? I just installed the apk and opened it I got a black screen

**Comment by agottardo** [comment]
v1.66.3 is currently awaiting review from the Google Play Store and will reintroduce Android TV support to all users. Just need a bit of patience :)

**Comment by agottardo** [comment]
v1.66.3 is rolling out to all users. Android TV support should be re-enabled. Closing.

**Comment by drogers0** [comment]
Note for anyone landing here from a search: this was fixed for **Android 8.0+ only**.

The GLES 2.0 crash is genuinely fixed — the Compose rewrite has no GLES 3 requirement and runs fine on a Mali-450. But `minSdkVersion` went 22 → 26 one commit after that rewrite landed (`bf0e56469f`, 2024-03-13), so no release has ever paired the Compose UI with an API floor these devices can install.

I've backported it to API 22, built from upstream source: https://github.com/drogers0/tailscale-firetv-fireos5

It isn't Fire TV specific — anything on **API 22–25 (Android 5.1 through 7.1)** with an `armeabi-v7a` slot is in scope, which covers most of the hardware reported in this thread: Mali-400/450 TV boxes (Amlogic S805 / S812 / S905, Rockchip RK3128 / RK3229 / RK3328, Allwinner A33 / A64 / H3), MT6580 and Spreadtrum phones, and the older Fire tablets. Device-by-device table with model codes and verdicts: https://github.com/drogers0/tailscale-firetv-fireos5/blob/main/docs/DEVICES.md

Verified on 1.98.8 on a Fire TV Stick 2nd gen (Fire OS 5.2.9.5, Mali-450 / GLES 2.0) including exit-node routing. Everything else in that table is untested — `scripts/device-check.sh` reports where a given device lands. Unofficial and debug-signed; the README covers the caveats.

One thing worth saying explicitly, since a lot of reports here are Android 8+ devices (Mi Box S, most Android TV 9 boxes): if you're on API 26 or later the official client works and none of this applies. GLES 2.0 was never the blocker on its own.
