### ISSUE TITLE
Upgrade error on MacOS. Version mismatch

### ISSUE THREAD

**Issue by mdeeks** [tailscale/tailscale#4860]
### What is the issue?

We have seen this a few times now on MacOS when Tailscale upgrades. Previously it was assumed to be something related to installs via Jamf, but we're also seeing it for users who have installed the app via the Mac App Store. We're getting a lot of reports of it after rolling out Tailscale to more of our company.

![image](https://user-images.githubusercontent.com/2966467/173871006-1c83f092-cb56-47e2-bffc-adaad4e89e45.png)

### Steps to reproduce

Have a previous version installed. Wait for the app store to try to upgrade your app. (It's likely this happens with manual upgrades but I can't test that since the app store doesn't let you roll back)

### Are there any recent changes that introduced the issue?

No recent changes. We've been seeing this since at least version 1.22

### OS

macOS

### OS version

macOS Monterey

### Tailscale version

1.24.2

### Bug report

BUG-c35bb9b250988007140ea191bc301ba9c1f68432c499e63172e8993479c201d1-20220615161929Z-d2f7e50ca5a09e70

**Comment by DentonGentry** [comment]
This means:
- The Network Extension reloaded using the 1.26.0 release
- that the Network Extension loaded means /Applications/Tailscale.app must have been updated
- the running process for the menubar UI is still open from /Applications/Tailscale.app when it was 1.24.2.

**Comment by DentonGentry** [comment]
We used to see this happen occasionally, but thought we had resolved it in the 1.24 release by fixing an issue making the old version of the app sometimes not quit after upgrade. That might have been one problem, but apparently there is another since 1.24.x is still involved in this report.

**Comment by mdeeks** [comment]
Yeah it's happening again today with the 1.26.1 release as well. Getting multiple reports of it. Aside from the Bug ID, anything we can send that would help?
![image](https://user-images.githubusercontent.com/2966467/174847723-e0fb046c-f189-4b5c-8197-9dc571d5011e.png)

**Comment by mdeeks** [comment]
Okay, let me know when the proposed fix is in. I'm on the Testflight unstable build now (1.27.23). Happy to help debug if I can

**Comment by DentonGentry** [comment]
From the Eng team:
_Re: the bug where the app would get upgraded and the network extension would not when updating from the mac app store: Apple just responded to my radar suggesting this is fixed in macos13 b5 and requested we try and reproduce the issue there_

**Comment by mdeeks** [comment]
@DentonGentry Do you know if there is any way to install an old version of tailscale from the app store so I can test an upgrade?

**Comment by DentonGentry** [comment]
@mdeeks Not in the App Store itself, but if you sign up for TestFlight for the macOS Tailscale app at https://testflight.apple.com/join/7ExrFq00 you can choose any of the TestFlight releases from the last 90 days. We do routinely send the release builds to TestFlight, so for example one can find the 1.28 release there.

Apple rejected 1.30 for TestFlight but approved it for general release, which we haven't figured out yet.

**Comment by mdeeks** [comment]
The weird thing is, I haven't seen this error on TestFlight builds. I've been using TestFlight regularly for the past couple of months. The upgrade process is definitely different. I get prompted about three times for a password every time it updates.

**Comment by KTamas** [comment]
Still happens!
<img width="260" alt="Screenshot 2023-07-28 at 11 53 42 AM" src="https://github.com/tailscale/tailscale/assets/48946/629937ed-d182-40b9-9111-3012cf33ff3e">

**Comment by hazcod** [comment]
Also had a user with this issue.
