### ISSUE TITLE
Azure AD external guest Microsoft accounts fail to authenticate

### ISSUE THREAD

**Issue by sailorfrag** [tailscale/tailscale#5092]
### What is the issue?

When using an [external identity](https://docs.microsoft.com/en-ca/azure/active-directory/external-identities/identity-providers) with Azure AD, Microsoft Accounts (MSA) result in a server error from Tailscale. The other external identity types appear to work OK.

See also HS conversation 3259

### Steps to reproduce

1. Set up a tailnet using Azure AD for authentication
2. Invite an external user using a Microsoft Account
3. At the Tailscale login page, choose Microsoft, Sign-in options, Sign in to an organization, type the Azure AD domain name into the box, then log in as the external user

Expected: the user logs into the tailnet as something like `username_external.example.com#ext#@ad.example.com`
Actual: internal server error

### Are there any recent changes that introduced the issue?

No

**Comment by sailorfrag** [comment]
The original reporter also mentions that "FIDO login via Windows Hello" appears to trigger the same problem.

**Comment by 0x241** [comment]
I have exactly the same problem with Azure AD..

**Comment by DentonGentry** [comment]
I think we fixed this over the summer, accommodating external accounts in AzureAD.

**Comment by rmoesbergen** [comment]
I'm having the same issue. Logging in with an external identity always brings me to this error:

![image](https://user-images.githubusercontent.com/8319432/214315354-09c5ae6f-2be8-4773-81eb-844a907f42cf.png)

**Comment by DentonGentry** [comment]
@rmoesbergen I do not believe this is the same issue. As we'd need account details to followup, please submit this as a support request https://tailscale.com/contact/support/ so we won't be putting account information in a public bug.

I'm going to close this bug: I believe we fixed support for external accounts in the Microsoft login support a few months ago.

**Comment by sailorfrag** [comment]
Reopening because this issue is still occurring.

External guests that are from other Azure AD instances work fine (we have customers using this) and I believe the other external identity categories should work (as documented in the Microsoft link from the first post on this issue). MSA (personal Microsoft Accounts) does not work, this is a technical limitation imposed by Microsoft due to the way our authentication system connects to them:

We receive the following error from Microsoft:
> AADSTS500202: User account '{EmailHidden}' from external identity provider 'live.com' is not supported for API version '2.0'. Microsoft account pass-thru users and guests are not supported by the tenant-independent endpoint.


From what I understand, to resolve this will require per-AD configuration by an administrator, similar to the Okta setup process, and corresponding changes made on our end to support that flow. Until that is done, this will be an ongoing issue.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/issues/979 is likely to require per-AD configuration by an administrator as well.
