### ISSUE TITLE
Can't run or control Tailscale from multiple users simultaneously - "Tailscale: in use by other user"

### ISSUE THREAD

**Issue by conioh** [tailscale/tailscale#5219]
### What is the issue?

On Windows, when multiple users logging on to the same machine (using RDP or fast user switching), any user but the first one gets a disabled Tailscale tray icon saying "Tailscale: in use by other user".

The best case scenario would be for Tailscale connections to be user-local, but I don't know if that's possible.

(The wintun adapters would obviously be visible to all users, but perhaps on the WireGuard/Tailscale level you can drop all packets coming from all users but the one responsible for the connection or something else. I don't know enough about WireGuard/Tailscale at this point to say if that's possible. There also may be issues regarding system processes running in Session 0 trying to talk through these connections.)

Alternatively (if completely impossible) / additionally (until that is done, and for users who want a single machine-wide connectivity) the control program should work from other users too.

Tooltip:
![Screenshot 2022-07-29 005825](https://user-images.githubusercontent.com/10606081/181649676-3bc7220d-b9b3-4646-b4a4-2fa49199c216.png)

Right click:
![image](https://user-images.githubusercontent.com/10606081/181649903-2dac481f-ab8e-44e3-9561-911ef51744b1.png)

Left click:
![image](https://user-images.githubusercontent.com/10606081/181649961-b1fd0407-5ee0-4808-b7bd-18b3e7f97729.png)

### Steps to reproduce

1. Install Tailscale.
2. Run Tailscale.
3. Connect to a Tailscale account.
4. Press WinKey+L.
5. Log on to a different user from the one used in steps 1-4.

### OS

Windows

### OS version

Windows 11 Enterprise x64 build 22000.795 but that's not version-specific.

### Tailscale version

1.28.0 (t80313cdee-gd26dd4a68) but that's not version-specific.

### Bug report

BUG-dacb37b37f8ebddb8862a6e1b7ff009a593749671b6f0fdde01f9030e5d89615-20220728230855Z-d86ed4039c1ff4ec

**Comment by conioh** [comment]
@DentonGentry, how is this not a bug?

I'm getting an error message for no reason.
The connections are shared by all the users on the machine.
`tailscaled.exe` runs as `LOCAL_SYSTEM`, so not related to this or that user.
But only one user can use the UI to control the service? The one who happens to run first? How is this not a bug?

**Comment by DentonGentry** [comment]
The Windows app was designed to work with one user at a time. It prints a message to that effect.

I suspect it is correct that that the frontend may be able to cooperate across multiple users, or otherwise improve the experience. We label issues with a gauge of impact to aid in triage and prioritization across open issues.

**Comment by conioh** [comment]
> The Windows app was designed to work with one user at a time. It prints a message to that effect.

A bug doesn't have to be in the implementation. There can also be bugs in the specification.
Even assuming the specification is valid, at the very least there's a bug in the documentation.
Unlike odd behaviors regarding NAT or DNS which may be difficult to even discover let alone accurately define and document, since this was _designed_ as you say, this should have been documented. But it wasn't and was an unpleasant surprise to me.

> I suspect it is correct that that the frontend may be able to cooperate across multiple users, or otherwise improve the experience. We label issues with a gauge of impact to aid in triage and prioritization across open issues.

The labels you assigned seem appropriate to me. The thing that's missing in your label system is the estimated difficulty. I'm guessing this shouldn't be too difficulty to fix.

Just for comparison, the GUI client for ZeroTier (which you yourself consider equivalent enough to compare on your site) does work from multiple users simultaneously.

For the other thing I mentioned I'll open a separate issue to allow you to track it separately.

**Comment by jeryd** [comment]
Is the only way around this to sign out the other users and sign yourself back in?

**Comment by DentonGentry** [comment]
>Is the only way around this to sign out the other users and sign yourself back in?

Currently yes, only one user is active at a time.

**Comment by SurvivaLlama** [comment]
Sorry for the bump in this - but I'm currently on a trip with my wife, we both use tailscale, but we brought only 1 laptop. The lack of this feature is a big issue and is forcing me to use different options for connection. Having to log out and log back in with each profile and re-authenticate is super frustrating.

**Comment by DentonGentry** [comment]
Since this issue was filed, Fast User Switching has been introduced: https://tailscale.com/blog/fast-user-switching/
Once both accounts have logged in once, switching between them should be very quick.

**Comment by SurvivaLlama** [comment]
> Since this issue was filed, Fast User Switching has been introduced: https://tailscale.com/blog/fast-user-switching/ Once both accounts have logged in once, switching between them should be very quick.

That is extra work. Step in the right direction, but I would like a way to have both accounts work depending on what account is currently being used.

**Comment by conioh** [comment]
@SurvivaLlama, I agree, but this is an improvement.
I think #5368 is more relevant to this and to be fair to the Tailscale team this isn't trivial to solve.

**Comment by DocBlizz** [comment]
Having the same issue, I even deleted the other user and am Still having the same issue.

**Comment by SurvivaLlama** [comment]
When we switch users, why do we have to reconnect to tailscale?

**Comment by DentonGentry** [comment]
> When we switch users, why do we have to reconnect to tailscale?

Because each user has a unique node key.

**Comment by josedev-union** [comment]
@DentonGentry got it.
I have 2 users in my windows server, `developer` and `operator`.
I installed and ran Tailscale using the `developer` user.
Now I want to run it using the `operator` user.
How can I do that?

I uninstalled Tailscale in the `developer` user and reinstalled in the `operator` user. But Tailscale started automatically with the `developer` user. And when `operator` user tries to run tailscale, it shows 
```
tailscale running in server mode ("developer"); connection from "operator" not allowed.
```

**Comment by Trogvars** [comment]
> tailscale running in server mode ("developer"); connection from "operator" not allowed.

Same situation here. Can't figure out what to do.

**Comment by 4fd81048-Brian** [comment]
FWIW, Fast User Switching https://tailscale.com/blog/fast-user-switching/ has nothing to do with this issue, (FUS allows a single Windows user to switch between Tailscale accounts)  This issue is regarding multiple windows users control a single tailscale process.

If Tailscale is deployed through software management (installed, run-unattended, and authenticated with an auth-key), it may be installed under the "SYSTEM" account.  When that happens no windows user can control it at all, and there's no way to even allow anyone to control it, even if they are members of the local administrators group.

```
C:\>whoami
domain\bbuchanan

C:\>whoami /groups | find "Administrators"
BUILTIN\Administrators                      Alias            S-1-5-32-544                                   Mandatory group, Enabled by default, Enabled group, Group owner

C:\>REM Am I in an elevated cmd?  

C:\>net session >nul 2>&1 && echo Elevated session || echo This is not an elevated session
Elevated session

C:\>"C:\Program Files\Tailscale\tailscale.exe" status
failed to connect to local tailscaled (which appears to be running as tailscaled.exe, pid 3440). Got error: 401 Unauthorized: Tailscale running in server mode ("ADMIN01\\Administrator"); connection from "DOMAIN\\BBuchanan" not allowed
```

In the above example I still have the option of "runas" the Administrator account.  But if it was under "System" I'd have to resort to external tools such as "psexec -s -i" to get a system shell.

If there's documentation on authorizing other users to get around "401 Unauthorized" I haven't been able to find it.

**Comment by conioh** [comment]
> FWIW, Fast User Switching https://tailscale.com/blog/fast-user-switching/ has nothing to do with this issue, (FUS allows a single Windows user to switch between Tailscale accounts) This issue is regarding multiple windows users control a single tailscale process.

This is yet another instance of overloaded meanings for a single term. Long before Tailscale's "fast user switching", Fast User Switching meant a second or later user connecting to a multi-user operating system without logging out the first user.

https://en.wikipedia.org/wiki/Fast_user_switching
https://en.wikipedia.org/wiki/Fast_user_switching#In_Microsoft_Windows
https://learn.microsoft.com/en-us/windows/win32/shell/fast-user-switching
https://learn.microsoft.com/en-us/windows/win32/shell/fastuserswitching (This is a different page with completely different content than the one above)
https://learn.microsoft.com/en-us/windows-hardware/drivers/display/fast-user-switching
https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-windowslogon#hidefastuserswitching

And that is what I meant when I initially wrote:
> On Windows, when multiple users logging on to the same machine (_using RDP or fast user switching_), any user but the first one gets a disabled Tailscale tray icon saying "Tailscale: in use by other user".

(Evident from the association with RDP.)

So yeah, as you wrote, Tailscale's "fast user switching" is mostly unrelated to this.

**Comment by aodevellp** [comment]
Almost a year in and I'm facing the same issue. We recently adopted Tailscale in our company and I'm starting to think it wasn't the best idea. The fact that in 2024 a service can't be managed by other users in the same system is very limiting, especially in some ways Windows work. I would've expected an experience similar to how it is under Linux, but no.

Any ETA on this? FUS, as other users say, is unrelated to what we're expecting as end users.

**Comment by Bw00d21** [comment]
> Almost two years in and I'm facing the same issue (arrived through a Google search, first link, go figure).
> 
> We recently adopted Tailscale at our company and I'm starting to think it wasn't the best idea. The fact that in 2024 a service can't be managed by other users in the same system is very limiting, especially in some ways Windows work. I would've expected an experience similar to how it is under Linux, but no.
> 
> Any ETA on this? FUS, as other users say, is unrelated to what we're expecting as end users.

Also looking for an update in this. I have two user accounts on my PC, one for work and one for personal. Id like to use Tailscale from both Windows Accounts. "Run Unattended" doesn't help either

**Comment by dblohm7** [comment]
This is Tailscale's tech lead for our Windows clients. I assure you that our developers who speak Windows understand what you're looking for. Unfortunately we have some tech debt to pay off to make this happen, but it's definitely on our roadmap.

**Comment by aodevellp** [comment]
> I am Tailscale's tech lead for our Windows clients. I assure you that our developers who speak Windows understand what you're looking for. Unfortunately we have some tech debt to pay off to make this happen, but it's definitely on our roadmap.

Hey @dblohm7 ! Thanks a lot for your answer and interest in helping us with this. That's great to know! Tech debt is always something good to tackle, can't have it grow or creep too much! 🤣

Just curious, do you have any ETA, even if it's a rough estimate, of when can we expect this feature to be around in your roadmap? So we don't bother you until then and we can tell our employers to wait patiently 😅 thank you!

**Comment by Aeroverra** [comment]
For me its just annoying that it doesn't keep me signed in. I don't need it to work on multiple users but when the user that uses tailscale goes to use it. It should work.

**Comment by nickkhyl** [comment]
@Aeroverra: Could you please elaborate on your current experience and what exactly is not working for you?
What do you mean by "it doesn't keep me signed in"? If you could describe it in more detail with specific repro steps, that would be most appreciated.

In the meantime, while I don't fully understand how you'd like to use Tailscale and what issue you're experiencing, it seems you might want to always use it as the same user. If that's the case, enabling Unattended Mode as that user might be useful for your scenario.

**Comment by nyahbingi** [comment]
> @aodevellp fixing the underlying issues is one of our top priorities for the next 3 months.

Is this still happening? I'm having the same issue where there are two users with separate profiles sharing one windows PC and tailscale says the other user is connected when the profile is switched.

**Comment by nyahbingi** [comment]
> Is this still happening? I'm having the same issue where there are two users with separate profiles sharing one windows PC and tailscale says the other user is connected when the profile is switched.

Is this still happening? I'm having the same issue where there are two users with separate profiles sharing one windows PC and tailscale says the other user is connected when the profile is switched.

**Comment by nyahbingi** [comment]
> Almost two years in and I'm facing the same issue (arrived through a Google search, first link, go figure).
> 
> We recently adopted Tailscale at our company and I'm starting to think it wasn't the best idea. The fact that in 2024 a service can't be managed by other users in the same system is very limiting, especially in some ways Windows work. I would've expected an experience similar to how it is under Linux, but no.
> 
> Any ETA on this? FUS, as other users say, is unrelated to what we're expecting as end users.

Did you find a work around?

**Comment by owlteeth** [comment]
Also eagerly awaiting this fix.

**Comment by ericreiss** [comment]
Don't know if this is possible but when you fast user switch and another user is on a system, it asks the other user if they will allow the switch.  Maybe a combination of that and restarting the service but have tailscale not automatically login after a service restart (doesn't help running in server mode as a power loss/reboot might mess with this).  There may be conflicting settings with this approach.

**Comment by brmdias** [comment]
I also looking for this one. @dblohm7 any chance of getting a new ETA on this?

**Comment by aandersen2323** [comment]
> @aodevellp fixing the underlying issues is one of our top priorities for the next 3 months.

Any update? Its been over 3 months since last update and within your timeline

**Comment by vantech14** [comment]
Plus one for this to be fixed. Very annoying. We use RDP in azure to access remote systems. Whenever a user changes, tailscale is locked to the previous user who has to reauthenticate and this only works after a reboot.

**Comment by Eddie75CZE** [comment]
Hello, any update on this one? I'm sharing my PC with my wife, with different windows user profile. But when she logs in, tailscale is locked...
Thanks!

**Comment by ThenDev** [comment]
> I am Tailscale's tech lead for our Windows clients. I assure you that our developers who speak Windows understand what you're looking for. Unfortunately we have some tech debt to pay off to make this happen, but it's definitely on our roadmap.

It's exactly two years since this comment stating that it's definitely on the roadmap was posted. GUI is still locked for other users on the same Windows PC, making it unusable.

Use case: I switch between Windows user accounts for different roles. I need to be able to enable/disable exit nodes from any Windows account on the same PC.

If it's on the roadmap, please can we have an updated timescale - 6 months, 2 years? Or, if this issue is not going to be resolved, please let us know, so this issue can be closed and we can move on.

**Comment by vantech14** [comment]
> > I am Tailscale's tech lead for our Windows clients. I assure you that our developers who speak Windows understand what you're looking for. Unfortunately we have some tech debt to pay off to make this happen, but it's definitely on our roadmap.
> 
> It's exactly two years since this comment stating that it's definitely on the roadmap was posted. GUI is still locked for other users on the same Windows PC, making it unusable.
> 
> Use case: I switch between Windows user accounts for different roles. I need to be able to enable/disable exit nodes from any Windows account on the same PC.
> 
> If it's on the roadmap, please can we have an updated timescale - 6 months, 2 years? Or, if this issue is not going to be resolved, please let us know, so this issue can be closed and we can move on.

Hi @ThenDev i think this has been fixed. 

2 windows users, log into each profile individually using the users own email address. 

In the tailscale UI you should then see the machine name, and for each subsequent user, a "-" will appear after the machine name with their email shown as the user. 

Tagging of machines doesn't work in this instance. You can set rules via the ACL. 

I haven't tried exit nodes but the individual logins definitely works.

**Comment by owlteeth** [comment]
Hi vantech14, my use case is multiple purely local accounts (not involving Microsoft login or email addresses); does the solution work for this?

**Comment by vantech14** [comment]
> Hi vantech14, my use case is multiple purely local accounts (not involving Microsoft login or email addresses); does the solution work for this?

@owlteeth yes, I have local windows accounts (no Azure or Microsoft connectors). On each local account, I signed into Tailscale (I use google for logins). This creates the same machine in Tailscale with the machine name having a -1, -2, -3 etc against each user on that machine. 

You can then apply ACLs against users in Tailscale. 

Hope this helps.

**Comment by jeffrpowell** [comment]
I'm not seeing things resolved for me. Still getting this

<img width="408" height="165" alt="Image" src="https://github.com/user-attachments/assets/fab1133d-6784-4a53-b7d1-37f2235d29f6" />

I right-click on the icon in the drawer and select `Login...` and it doesn't do anything.

However, if I switch to the other account, exit Tailscale, then switch back over to the original account, I'm able to authenticate to Tailscale.

**Comment by ThenDev** [comment]
> Hi [@ThenDev](https://github.com/ThenDev) i think this has been fixed.
> 
> 2 windows users, log into each profile individually using the users own email address.
> 
> In the tailscale UI you should then see the machine name, and for each subsequent user, a "-" will appear after the machine name with their email shown as the user.
> 
> Tagging of machines doesn't work in this instance. You can set rules via the ACL.
> 
> I haven't tried exit nodes but the individual logins definitely works.

Hi, thanks for replying. I don't believe it has been fixed. To ensure we are not at cross-purposes, these are the steps to replicate:

1) Login to Windows as userA - Tailscale is active and user can make changes, select exit nodes, etc. using the icon in the system tray.

2) Switch users and login to Windows as userB - user can see the Tailscale icon in the taskbar (greyed) and when user clicks the icon, they see "Tailscale is already in use by [machine/user pid:[pid]". When logged in as userB, the only option that works is Exit - userB can't login to Tailscale.

When logged in as userB, Tailscale is operating with the current settings as applied by userA and the settings can't be changed. The only option is to switch back to userA and either make the changes or exit Tailscale, then switch back to userB.

When logged in as userB, there appears to be no way to terminate Tailscale - when using Task Manager to terminate all Tailscale processes, Tailscale restarts automatically - presumably the Tailscale service is doing this. In other words, userB cannot use Tailscale unless userA logs in (by switching Windows users) and either Exits or logs out.

Desired behaviour is that if userB has appropriate role, they make changes using the Tailscale icon.

The immediate problem for me is that if Windows userA has set an exit node, then Windows userB is stuck with that exit node.
