### ISSUE TITLE
mac: VPN doesn't reconnect when switching from user A to B, then back to A

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#594]
In 0.100.0-94, the Mac client is now much less aggressive about repolling & thus restarting the Network Extension backend. We did this so it doesn't keep bringing the VPN connection back to life, fighting you as you're trying to stop it via the system preferences.

Unfortunately, we're not aggressive enough:

If you switch from user A to user B, macOS stops the VPN (and tells us we're being stopped), but then if we switch back from user B to user A, we used to (somewhat accidentally) restart the backend because we were polling it regularly. Now that we don't do that, users report that they're logged out often.

We should pay attention to certain events more to resume the backend on user switch.

@steeve also reports a similar problem but unrelated to user switching. We've been unable to figure out exactly what it is though; I can't reproduce the logout issue with wifi changes (ethernet->wifi, wifi->wifi, etc).

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ap8x)

**Comment by bradfitz** [comment]
Looking at logs, the top `stopTunnel` reasons from macOS:

```
      2 stopTunnel: "configurationDisabled"
     10 stopTunnel: "userSwitch"
     48 stopTunnel: "userLogout"
    158 stopTunnel: "userInitiated"
```

**Comment by moderation** [comment]
Interestingly I've worked out that if I SSH normally into the MacOS account
while my daughter has her account logged in and use the following command
it will bump Tailscale to active. Ironically I can only do this on MacOS as
they make it almost impossible to modify the default SSH configs to lock
down access

/Applications/Tailscale.app/Contents/MacOS/Tailscale up

**Comment by steeve** [comment]
I feel that it happens when my mac stays in sleep for a long time. I was connected all day yesterday, and I just noticed I was disconnected today.

**Comment by steeve** [comment]
Confirmed, my macbook just woke up from sleep without being moved and it was disconnected.

**Comment by bradfitz** [comment]
@steeve, I see in your logs, the last stopTunnel event:

```
2020-07-28 18:31:08.19748 +0200 +0200: stopTunnel: "userLogout"
```

Is that when you slept the machine?

**Comment by steeve** [comment]
That's about it yes!

**Comment by steeve** [comment]
Confirmed! I can reproduce by locking my machine via the `Login Window` menu when clicking on my name in the upper right corner.

**Comment by DentonGentry** [comment]
I think this was likely resolved by IPN state machine updates in 1.8 and 1.10.

Barring further updates, we'll expect to close this during the next bug scrub.

**Comment by bradfitz** [comment]
@DentonGentry, this is unrelated to the general Go code. It's a message macOS sends us to Swift on user switch which we don't handle (or handle/pass on wrong) which ends up killing the tunnel. I haven't see anything go by in that area so I assume this is still an issue. Should be easy to repro still on a Mac.

**Comment by moderation** [comment]
Still and issue. Behavior a little different now. This is all on an M1 Mac Mini. When the user is switch now, the Tailscale network freezes but doesn't terminate. To work around this I keep a pane in tmux open below the Tailscale pane connected to the machine IP not using Tailscale. I switch into this pane and hit return a couple of times and the activity kicks starts the Tailscale connection into life. I can then switch there and work on the Tailscale connection

**Comment by ryuheechul** [comment]
This is how I worked around it, https://github.com/ryuheechul/provision/tree/main/lima/tailscale

**Comment by Baschdl** [comment]
Is there any way to circumvent this? I'm still seeing it with version 1.22.1 on MacOS 12.3 and it makes using Tailscale pretty inconvenient when using two accounts.

**Comment by DentonGentry** [comment]
I'm not sure the stopTunnel problem this issue was originally filed to address still exists.

**Comment by ay18** [comment]
@Baschdl thanks for the tip, this also worked for me. Instead of compiling, I installed through homebrew, installed the daemon, and added the listed IP to my DNS settings.

**Comment by DentonGentry** [comment]
I think this bug is obsolete, it concerned an issue in `stopTunnel`. We have other bugs tracking recently issues with fast user switching.

Barring further comment, we'll expect to close this during the next regular bug scrub.
