### ISSUE TITLE
DNS stops working periodically, fixes itself with manual restart

### ISSUE THREAD

**Issue by SebastianZaha** [tailscale/tailscale#6850]
### What is the issue?

Tailscale on my raspberry pi starts logging errors with DNS resolution and DNS only starts working again after a manual restart. The machine is used to rsync some backups, which works if the host accessed is on the tailnet, but then any request to internet domains that need to be resolved fails. 

Possibly related to #3301 ?

### Steps to reproduce

It happened twice in 2 days, but I am not sure how exactly to reproduce. The logs have a lot of errors and "dns udp query: request queue full" messages.

I can provide the logfile too, I am not sure if the bugreport went through, as I see the daemon has issues connecting to log.tailscale.io
```
Dec 26 12:42:45 raspberrypi tailscaled[10299]: logtail: dial "log.tailscale.io:443" failed: dial tcp: lookup log.tailscale.io on 100.100.100.100:53: read udp 100.66.146.68:42064->100.100.100.100:53: i/o timeout (in 20.009s), trying bootstrap...
Dec 26 12:42:45 raspberrypi tailscaled[10299]: [RATELIMIT] format("dns udp query: %v") (258 dropped)
Dec 26 12:42:45 raspberrypi tailscaled[10299]: dns udp query: context deadline exceeded
Dec 26 12:42:45 raspberrypi tailscaled[10299]: dns udp query: context deadline exceeded
Dec 26 12:42:45 raspberrypi tailscaled[10299]: [RATELIMIT] format("dns udp query: %v")
Dec 26 12:42:55 raspberrypi tailscaled[10299]: [RATELIMIT] format("dns udp query: %v") (258 dropped)
```

### Are there any recent changes that introduced the issue?

There is more traffic from this machine on the tailnet that before, but I do not see that the crash and errors happen after a large amount of traffic. (the mentioned rsync job, which syncs about 5GB. Today it crashed before the job even started.)

### OS

Linux

### OS version

Raspbian GNU/Linux 11 (bullseye)

### Tailscale version

1.34.1

### Bug report

BUG-3a0aa9aaf40439368e79eeb64fb34b717f79c5b1968cc17c79536da689a7d716-20221226123930Z-69e12ec2f1464323

**Comment by bradfitz** [comment]
Thanks for the `tailscale bugreport`.

Looks like this might be a problem with our `openresolv` support? I see that's what you're using:

```
2022-12-21 13:47:13.956763327 +0000 UTC: dns: using "openresolv" mode
2022-12-21 13:47:13.95720666 +0000 UTC: dns: using dns.openresolvManager
```

Seems like overtime we accumulate dups, despite only setting two search domains:

> 2022-12-20 16:53:12.90183667 +0000 UTC: dns: Set: {DefaultResolvers:[] Routes:{beta.tailscale.net.:[] tail6a30c.ts.net.:[] ts.net.:[199.247.155.53 2620:111:8007::53]}+65arpa SearchDomains:[tail6a30c.ts.net. sebastian-zaha.xxx.com.beta.tailscale.net.] Hosts:14}
> 2022-12-20 16:53:12.932692322 +0000 UTC: health("dns-os"): error: parsing search domains "search tail6a30c.ts.net sebastian-zaha.xxx.com.beta.tailscale.net tail6a30c.ts.net sebastian-zaha.xxx.com.beta.tailscale.net tail6a30c.ts.net sebastian-zaha.xxx.com.beta.tailscale.net tail6a30c.ts.net sebastian-zaha.xxx.com.beta.tailscale.net tail6a30c.ts.net sebastian-zaha.xxx.com.beta.tailscale.net upc.at": "tail6a30c.ts.net sebastian-zaha.xxx.com.beta.tailscale.net tail6a30c.ts.net sebastian-zaha.xxx.com.beta.tailscale.net tail6a30c.ts.net sebastian-zaha.xxx.com.beta.tailscale.net tail6a30c.ts.net sebastian-zaha.xxx.com.beta.tailscale.net tail6a30c.ts.net sebastian-zaha.xxx.com.beta.tailscale.net xxx.at" is too long to be a DNS name

I wonder if the `openresolv` code on our side does a read-modify-write and isn't accounting for duplicates.

If you're able to, switching to `systemd-resolved` should fix things. That's the much more popular DNS path on Linux and Tailscale has good support for it.

/cc @danderson @maisem @DentonGentry

**Comment by ChrisSmith** [comment]
Saw the same thing on my raspberry pi today. openresolv is the default on Raspbian, so this may affect all pi users. 


Tailscale 1.34.1

Bug report (taken after I restarted tailscale) 
BUG-76135f7a77a1e675c52efa0ca70970f8375cdea5632900b8b8d202d08e71cb87-20230101044852Z-1d87a4d952fa2da4

**Comment by bradfitz** [comment]
I think this is likely a dup of #6875 (which was filed after this bug) and fixed by https://github.com/tailscale/tailscale/commit/ea70aa3d980db1c7bd1912298167e545249c08fa

**Comment by bradfitz** [comment]
We'll be cherry-pick the fix into the upcoming 1.34.2.

/cc @DentonGentry

**Comment by ztmr** [comment]
@bradfitz @DentonGentry I am seeing the same issue even after upgrading to 1.36.1. Anything I can do to help you debugging this? Exactly as the OP says: only restarting the systemd service helps.

```console
$ tailscale version
1.36.1
  go version: go1.19.5
```

**Comment by ztmr** [comment]
FYI, I have just noticed that in my case, the DNS issues are very much related to whether the machine supports IPv6 or not. `tailscale netcheck` indicates that IPv6 is not supported on that machine/network yet MagicDNS keeps attempting to use IPv6 DNS server.

The only reliable solution is to disable Tailscale-provided DNS entirely by setting `--accept-dns=false` on these problematic nodes.

The machine where it is enough to restart tailscaled does have OS support for IPv6 but the network does not support it. The other machine has no OS support for IPv6 at all, and the restart does not help there at all.

There were no issues as long as I have used PiHole via IPv4 Tailscale address, but I am now testing NextDNS, where IPv6 seems to be the default option and that's roughly when I started having these problems.

**Comment by SebastianZaha** [comment]
This is still happening, only perhaps quite rarely. @bradfitz 

Still only way to get dns to work on the affected machine is to ssh to it and restart the daemon.

```
1.40.0
  tailscale commit: 105be684dd04727a58ed213ec9499d071a377ece
  other commit: 4c70014a47f1816e1573a8cef58cdaf96f78a264
  go version: go1.20.3-tsddff070
```

```
May 17 06:23:28 raspberrypi tailscaled[658]: logtail: dial "log.tailscale.io:443" failed: dial tcp: lookup log.tailscale.io on 100.100.100.100:53: read udp 100.66.146.68:54586->100.100.100.100:53: i/o timeout (in 20.01s), trying bootstrap...
May 17 06:23:28 raspberrypi tailscaled[658]: [RATELIMIT] format("dns udp query: %v") (257 dropped)
May 17 06:23:28 raspberrypi tailscaled[658]: dns udp query: context deadline exceeded
May 17 06:23:28 raspberrypi tailscaled[658]: dns udp query: context deadline exceeded
May 17 06:23:28 raspberrypi tailscaled[658]: [RATELIMIT] format("dns udp query: %v")
May 17 06:23:38 raspberrypi tailscaled[658]: trying bootstrapDNS("derp4f.tailscale.com", "185.40.234.219") for "log.tailscale.io" ...
May 17 06:23:38 raspberrypi tailscaled[658]: [RATELIMIT] format("dns udp query: %v") (258 dropped)
May 17 06:23:38 raspberrypi tailscaled[658]: dns udp query: context deadline exceeded
May 17 06:23:38 raspberrypi tailscaled[658]: dns udp query: context deadline exceeded
May 17 06:23:38 raspberrypi tailscaled[658]: [RATELIMIT] format("dns udp query: %v")
May 17 06:23:38 raspberrypi tailscaled[658]: bootstrapDNS("derp4f.tailscale.com", "185.40.234.219") for "log.tailscale.io" = [34.229.201.48 2600:1f18:429f:9305:4043:217b:512c:f8d4]
May 17 06:23:39 raspberrypi tailscaled[658]: logtail: bootstrap dial succeeded
May 17 08:26:41 raspberrypi tailscaled[658]: [RATELIMIT] format("dns udp query: %v") (254 dropped)
May 17 08:26:41 raspberrypi tailscaled[658]: dns udp query: request queue full
May 17 08:26:41 raspberrypi tailscaled[658]: dns udp query: request queue full
May 17 08:26:46 raspberrypi tailscaled[658]: dns udp query: request queue full
May 17 08:26:46 raspberrypi tailscaled[658]: dns udp query: request queue full
May 17 08:26:51 raspberrypi tailscaled[658]: dns udp query: context deadline exceeded
May 17 08:26:51 raspberrypi tailscaled[658]: dns udp query: context deadline exceeded
May 17 08:26:51 raspberrypi tailscaled[658]: dns udp query: context deadline exceeded
May 17 08:26:51 raspberrypi tailscaled[658]: [RATELIMIT] format("dns udp query: %v")
May 17 08:27:01 raspberrypi tailscaled[658]: [RATELIMIT] format("dns udp query: %v") (257 dropped)
```

**Comment by hadican** [comment]
This is still happening on 1.40.1 too. If I restart the daemon, it starts working.

**Comment by AlexChesters** [comment]
I realise this issue is closed, but is there any chance it can be reopened? Like many people in this thread I'm still experiencing this issue and the workarounds of `--accept-dns=false` or restarting the daemon regularly are less than ideal.

**Comment by DentonGentry** [comment]
Please open a new issue, describe the symptoms as clearly as you can, and include a bug report around the time that a problem is occurring.

This issue is resolved. Opening it again to handle another DNS symptom just mixes old symptoms with new.
