### ISSUE TITLE
Tailscale seemingly interferes with internet connectivity

### ISSUE THREAD

**Issue by skarra** [tailscale/tailscale#6891]
### What is the issue?

Occasionally when Tailscale is enabled I lose the ability to reach the internet. It gets fixed after turning Tailscale off, so my first guess is something to do with the Tailscale config. This has happened to me on Android as well as MacOS Monterey. It is not clear what the trigger is because it does not happen all the time. For e.g. right now as I file this  Tailscale is enabled:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/633395/210512850-40d7a60a-d94a-4084-af55-c1ff0a64cbcb.png">

Is there anything I can do to debug this a little more?

### OS

macOS, Android

### OS version

Monterey; Android 12

### Tailscale version

1.34.1 (app store)

### Bug report

BUG-d62ca7b2223acaa6f8def36043fc4ec13f9f2e0e0548594fc9727a72d78676dd-20230104081918Z-53c6c8975c5f5abb

**Comment by matan7890** [comment]
If you disable "Use Tailscale Subnets" does the connection works as intended? If so, could it be that you have an advertised network in your tailscale network with the same network subnet as your current network?

**Comment by alex-robbins** [comment]
Even with no tailscale subnets configured and when not using an exit node, I've had this issue on Android recently (e.g. browser can't reach the internet until I turn off tailscale). It seems like it only happens when I'm not on Wi-Fi, and my cellular IP address is in the 10.x.x.x range, so these two comments make me wonder if this is due to CGNAT. [[1]] [[2]]

[1]: https://github.com/tailscale/tailscale/issues/4584#issuecomment-1113886505
[2]: https://github.com/tailscale/tailscale/issues/6739#issuecomment-1352539501

@skarra does that sound like it could be the case for you too?

**Comment by skarra** [comment]
Matan, I can check toggling that switch next time it happens; but other than that I could not follow what you are saying. Tailscale is installed on all the nodes I am interested in, and I have not done anything to actually set up one of the nodes as a tailscale subnet router.

Alex, 

Issue #6739 seems similar enough, but FWIW I am seeing the problem on both Android and Mac.

On Android it has happened only when on cellular data (not on Wi-Fi). I have not checked the IP addr when it happened then. But on MacOS this happens on Wi-Fi (there is no cellular data).  ifconfig on the mac showed this when I could not ping google.com:
```
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 98:01:a7:99:b5:6f 
	inet6 fe80::18f0:a725:fa9e:7cc9%en0 prefixlen 64 secured scopeid 0x4 
	inet 192.168.86.29 netmask 0xffffff00 broadcast 192.168.86.255
	inet6 fd7c:facb:3f51:0:cee:b9f5:1225:9cbb prefixlen 64 autoconf secured 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
```

**Comment by matan7890** [comment]
I would check the routing table when this happen again, maybe it's a routing problem?

**Comment by daavidb** [comment]
I have exactly this problem, and it always* happens when connected over 4G. It doesn't happen when my phone is connected through WIFI. On 4G my phone's ip is
10.22.xxx.xxx 
and on my tailscale network I have addresses
100.120.xxx.xxx,
100.116.xxx.xxx,
100.98.xxx.xxx.

I have no exit node on my tailscale network. On my windows and linux nodes connecting to the outside internet work fine.

* At least always so far. I just stated using tailscale today and have yet get it to work without this problem on 4G.

**Comment by southernfm** [comment]
I have this issue as well and only with recent versions of tailscale. 

Internal network: 10.0.0.0/24 (does not overlap with any subnets we have on tailnet)
- Internet service independantly checked - no ping timeouts occurring when a device is directly attached to the internet service
- Other PCs that are connected to the same network hardware, that are not using tailscale are unaffected and don't have internet drop outs when ping is attempted against the same internet host that I test on my tailscale connected PC
- See 4 x 'Destination net unreachable' ping replies and then the ping responses resume working again
- Have tested two separate NICs in my PC, behaviour is present in both NICs
- The behaviour does not occur at all when the tailscale service is shut off on my PC
- We use magic DNS but only for an internal subnet which I don't believe is being used when I ping an internet service

Specs:
Windows 10 Pro 64-Bit 19045
NIC: Realtek Gaming 2.5GbE Family Controller and Realtek PCIe GbE Family Controller (two separate NICs, only one used at a time)
Tailscale version: 1.34.1 - I have seen this in the last couple of versions. 
It seems to be periodical - I have updated to version 1.34.2 and it isn't happening at the moment but I'll report back if it returns.

**Comment by daavidb** [comment]
Two updates:

1. It's a DNS issue. If I put ip addresses in the phone browser I can connect to various websites. Maybe related to https://github.com/tailscale/tailscale/issues/4252.
2. I can't reproduce the issue in a Pixel 4 emulated in Android Studio :(

**Comment by skarra** [comment]
This keeps happening on my Android phone and quite annoying as it prevents me from keeping Tailscale running all the time in the background. Is there anything I can do to help debug the issue?

**Comment by chanux** [comment]
I have the same issue on Android and I have figured that private DNS is involved in this behaviour.

**Comment by DentonGentry** [comment]
The issue with Android Private DNS is described in https://github.com/tailscale/tailscale/issues/915.

**Comment by Terramoto** [comment]
I have a similar issue which i'm not sure if it's related. I use Tailscale to relay 4g traffic through my house internet connection, all apps stop being able to connect to the internet, Firefox seems to be the only app able to connect to the internet with Tailscale enabled. Sometimes the connections work on Brave but intermittently(possibly displaying cached content) .

**Comment by southernfm** [comment]
The issue persists for me too. Logging in to other profiles usually causes it to stop working when I log back in to my main profile. If I shut down tailscale for awhile and start it again sometimes it comes back up.
________________________________

**Comment by captain-boom** [comment]
I'm having this issue.  Turn on Tailscale and I can reach the remote device through the tailnet, but I lose the ability to load a browser page on my local machine immediately.  I am able to access the internet via browser on the remote machine.

Turn off Tailscale locally, and the browser connects immediately.  Same issue on my LAN or directly to a Verizon hotspot.

MacOS Ventura 13.3
Tailscale 1.38.2 App Store

I'm a fairly new user to Tailscale.  I thought it was working okay when I first installed it, but broke recently.

**Comment by Terramoto** [comment]
> @Terramoto seeing that you have issues on android too: Did you try to re-enable tailscale after switching network? Do you see the same behaviour as me?

The behaviour i'm getting even after re-enabling Tailscale is that the DNS fails to resolve or ERR_CONNECTION_CLOSED. However, while this is true for all the majority of the apps, the only app that seems to be working fine is Firefox.

**Comment by DentonGentry** [comment]
I think this might be a symptom of [#4845](https://github.com/tailscale/tailscale/issues/4845) and [#6110](https://github.com/tailscale/tailscale/issues/6110)

Tailscale 1.42.0 contains [#8008](https://github.com/tailscale/tailscale/pull/8008), which is believed to resolve it.
Please post if you see further occurrences using Tailscale 1.42.0 or later.

**Comment by southernfm** [comment]
> Tailscale 1.42.0 contains [#8008](https://github.com/tailscale/tailscale/pull/8008), which is believed to resolve it. Please post if you see further occurrences using Tailscale 1.42.0 or later.

For my particular issue (Windows PC changing between two user profiles) the issue still occurs on 1.42.0

- Main Windows profile is the one I actually connect to Tailscale with, the secondary profile I don't use tailscale. It comes in with a login screen in the second profile when I login to it. I don't mind that as it is expected behaviour
- Swapping from the secondary profile back to the primary one, Tailscale service does not re-connect to the network. The icon in the system tray stays dark (not the black/white squares). This remains indefinitely until I restart the Tailscale service and restart the Tailscale application. Once both are restarted, it returns to normal.

My issue may be slightly different than the originally reported one in this thread but it is still present

**Comment by skarra** [comment]
Is 1.42 being rolled out for the Android app? My app currently says 1.40
and I can't see an update on the play store.

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/pull/8008 concerns macOS and Windows, it doesn't really impact Android.

**Comment by siegerhansma** [comment]
I'm running 1.42.0 on MacOS from the App Store. I'm still experiencing issues after update. 

I can connect to devices in my network with the 100.x.x.x address, but connecting to the internet with a browser doesn't work. When I disable TailScale, I can use the browser again. Tried every combination of Tailscale subnets enabled/disabled and Tailscale DNS settings enabled/disabled. 

Is there anything I can provide to help debug this?

**Comment by DentonGentry** [comment]
> Is there anything I can provide to help debug this?

@siegerhansma The most useful thing would be a bugreport. Hold option while clicking on the Tailscale icon in the menubar, then select Debug > Bug report.

**Comment by siegerhansma** [comment]
@DentonGentry: Done! ID: BUG-54349febf05fa75f8105e7fabd1c6c8d0f6703deb08808f76dd6e86a5aeec379-20230608065744Z-22bf915c5e4a8bb0

**Comment by southernfm** [comment]
BUG-cf58f913364c22c8f7d4bc2d63751fea6929416c92f622585b2c38d64b11704c-20230608071836Z-4e337effd1412889 for my issue

**Comment by lukevp** [comment]
same problem here.  macOS and Windows devices.  Tailscale causes issues with DNS resolution on both machines.  Disabling Tailscale makes it immediately work on macOS, and re-enabling causes Safari to fail to load anything.  Makes it so I can't use Tailscale currently.  Disabling the "Use Tailscale Subnets" seemed to have fixed it, but I've only been testing it for about 5 mins.  I'll leave Tailscale enabled with that option turned off for a while and see if that keeps working.  Re-enabling that setting didn't cause it to stop working though, it's pretty unreliable in when it does and doesn't work.

**Comment by lukevp** [comment]
one thing that may be relevant is that I use local DNS on my LAN via a Synology NAS running AdGuard, not a remote DNS or the gateway as DNS.

**Comment by codecat** [comment]
I also am seeing this on MacOS and iOS (Windows is fine). This workaround is to turn "Use Tailscale DNS settings" off. Same as @lukevp, I am also using Adguard on an OPNsense server.

DNS requests using `dig example.com` show up in Adguard's log, the response just never seems to arrive back.

My bug ID from MacOS:
BUG-a73712baca13cb42199d09de9ecffe45c7c9035e789dd3575ba838e67e1cfc17-20230621204726Z-d60f5db0a52da5c8

**Comment by siegerhansma** [comment]
Managed to fix it on my end. For my WiFi I had 1.1.1.1 set as my DNS. When I removed this and used my ISP default DNS, things magically started working.

**Comment by southernfm** [comment]
> 

I updated DNS as well. It still isn't quite 100% but it is a little better switching between two user accounts without requiring a restart.

**Comment by aayushrautela** [comment]
Turning of magicdns fixed issue for me.

**Comment by tombajzek** [comment]
Recently, I am seeing something similar to this, but I can't be sure it's exactly the same. Intermittently, I can't reach certain websites, and pinging these domains fails. If I turn off Tailscale, I can ping them and access them. If I turn on Tailscale again, they continue to work - at least for a while. I upgraded to 1.48 today, and it still happens. This has been happening for a few weeks, but I'm not sure which version I was running when it started. I know it did this in v1.46, but I don't know for sure about earlier releases because I didn't know it was gong to be an ongoing issues when I first saw it, and I didn't makes notes about it.

I can't make it fail right now, but when next does this, I'll post more information. It's tricky because it is intermittent or inconsistent.

Ironically, it just happened when I tried to open a Tailscale web page. Turning Tailscale off fixed it. I turned Tailscale on again, and in continued working.

It turns out that turning Tailscale off and then on again fixes the problem. It is not necessary to access the site in question while Tailscale is off in order to have success.

**Comment by tombajzek** [comment]
I should add that I'm now running  v1.48 on macOS Monterey on an M1 MacBook Air, although I suspect that doesn't matter in this case.

**Comment by MnemoBRMC** [comment]
I have the same problem in my mobile when I am not using WIFI. At home with my WiFi everything works well.
But when I am not at home, my mobile loses connection and I have seen that is in fixed areas. When I am entering or exiting my town it loses connection in that area. In other cities or at home it works well. It is weird, but if I disable Tailscale all works well in any place

**Comment by tombajzek** [comment]
I'm now running 1.48.2 and this problem is more consistent than before. The most irritating thing is that I have to turn off Tailscale when I send email to allow my copy to be saved on my computer. I just turned off Use Tailscale Subnets, and the email failure seems not to happen, but I still can't reach parts of the Internet (ironically, including the Tailscale web server) unless I turn off Tailscale. Now, whenever I have any of these problems, I just turn off Tailscale for a moment, and turn it back on. This doesn't seem to bother any SMB connections I have open at the time, probably because I don't access those servers while Tailscale is disconnected. I'm now running macOS Ventura (13.5.1) on my M1 MacBook Air.

**Comment by thirtythreeforty** [comment]
This is extremely reproducible for me on Android as well. It appears that if I try to resolve a DNS name, the first 3 or 4 attempts fail, and then it suddenly starts working for that particular name. Other names repeat the same pattern. Feels like an initial failure, then a successful fallback which gets cached.

My LAN's DHCP-provided DNS servers are:
```
fd9b:274:8c9c::1
2605:a601:a0ec:a201::1
192.168.1.1
```

BUG-da385993a7b4ead121814518ba74e7e7e07d072f091763a8eb820f3afc2e06e9-20231007002454Z-eb16d5cd32fd34bc

**Comment by hlegendre** [comment]
Same here. As soon as I activate Tailscale, I get access to my remotes but loose access to internet (with ou without exit node, with custom DNS [1.1.1.1] or default).

BUG-66387a589acb13e36537bd8f8431b954dd8b741119f0c0f0b8c7d3ac1bca65c5-20231013083031Z-e13acd099344614b

**Comment by skarra** [comment]
I'm convinced that if any Tailscale engineer ran into this issue on their
own personal phones they'd know how utterly annoying it is, and we'd have a
fix by now. So the real question is - why aren't these awesome folks
actually running into it? Does no one use Android up there?

**Comment by aayushrautela** [comment]
> I'm convinced that if any Tailscale engineer ran into this issue on their own personal phones they'd know how utterly annoying it is, and we'd have a fix by now. So the real question is - why aren't these awesome folks actually running into it? Does no one use Android up there?
 

Android client needs a lot of work, atleast a dark theme, it's 2023

**Comment by hulous** [comment]
Hello everybody,

I just got a similar issue. 
I can access to Tailscale network but have no internet connection while then. 
Your post helps me to try differents options about configuration. In my case, I just uncheck the option about using Tailscale DNS to be able to go on the internet.

<img width="206" alt="Screenshot 2023-11-10 at 10 36 21" src="https://github.com/tailscale/tailscale/assets/1019537/8864fa97-ce49-436c-aa32-bbf27056a9b3">



I hope this can help some until this is fixed.
Take care ;)

**Comment by hlegendre** [comment]
This does fix it for me since 1.52.0 *if and only if I remove any custom DNS on my network config after tailscale is activated*. If I do it the other way around, it does not work...

**Comment by tombajzek** [comment]
I have confirmed by testing just now that there are many sites I cannot reach when I **Use Tailscale DNS settings** that are accessible if I turn off **Use Tailscale DNS settings**. Unfortunately, one of those sites is that of my SMTP server.

I had suspected **Use Tailscale Subnets** of being a problem, too, but today, at least, that is not the case.

**Comment by tombajzek** [comment]
I forgot to add that I only lose access to some sites, not all, when this happens. I had been originally been suspecting routing problems in the Internet, but I've determined that the use of Tailscale DNS settings is the true culprit in most cases I experience.

**Comment by chocolate42** [comment]
Just a plus one I guess to having to turn off magic DNS to get my android phone able to access wan and tailscale simultaneously. (grapheneOS pixel 6a, android 14, tailscale 1.57.72)

**Comment by vidtech200** [comment]
Just to throw another "Doh!" possible solution in there...   haven't had this problem at all until the last 3 days.  Today the frustration of not having internet and access to my tailscale network got too high and I began googling for potential solutions and ending up here as one of the threads looking into.

This thread gave me some good thoughts (thanks guys), so in trying some of the suggestions (none working), I got to the "turn off magic dns" option.  Turned off  tailscale so that I'd have internet, and logged into (web) tailscale via internet.   Before I even switched to the settings page, I noted something odd.

It said it hadn't seen my exit node machine in the last 3 days...   what????

Doh!   3 days ago I had taken that server down for maintenance, and now realize I don't think I brought it back up.    As a proper geek, I have quite a few servers in my home lab that I'll spin up, and I've setup 2 of them as exit nodes (1 for primarily use, and 1 as a backup), both servers that I usually leave up 24/7.

Sooooo, I quickly loaded back up tailscale (killing the internet connection), right clicked the tool-bar tailscale icon, and switched my exit node to my backup server (which was on).... and the skies parted and the sun shone   (errr I now have internet and tailscale simultaneously).

So for those who typically laugh at folks with the "is it plugged in" first tech support question...  double check you're not being the daily idiot.    (Hopefully my stint as today's idiot might help someone else, thus my admitting to all of this.  :)

**Comment by aviadhaham** [comment]
> Turning of magicdns fixed issue for me.

Yeah, same issue for me as described here, and the same resolution as @aayushrautela :\

**Comment by ellnic** [comment]
In my case, I see this because I route all my DNS traffic through Adguardhome on my tailnet. Even when devices do not have TS installed I still have occasional connectivity issues on iOS and macOS when on home WiFi. 

I don't have TS on my phone right now because of the ongoing battery drain issues. Windows doesn't seem to have an issue that I have noticed. 

One thing I have been wondering - and a question for other iOS users here - have you found this issue is causing the iPhone to kick you off WiFi? I thought it was a tuning issue with my UniFi network to start, but I don't see the issue on Android or Windows. I can only assume iOS and macOS are pinging an apple server periodically then ditching the connection to save battery because they believe it's gone down. 

In any case, I hope this one gets resolved soon because it's _really_ annoying.

**Comment by tombajzek** [comment]
Sometime since I last posted to this forum, 11/10/23, I've been running Tailscale with **Use Tailscale DNS Settings** turned off. At some point not too long after that the problem accessing my email server stopped happening, so I've been running that was ever since without having that difficulty. I have no I deal what changed to make this work.

**Comment by TurkeyTradeMarket** [comment]
This bug needs to be fixed. Tailscale is unusable for me if I can't access the internet/a great many websites

**Comment by joeynguyen** [comment]
Thanks everyone for the suggestions.  I was having the same Internet issues.  After reading these comments, I tried one other thing which resolved it for me on several of my devices, including an Apple TV.  Btw, I didn't need to disable MagicDNS to make my devices work.

While I was able to disable "Use Tailscale DNS settings" on my Mac through the app's settings, the Apple TV's app doesn't expose that same option in its settings UI, which led me to searching for another solution.  Thankfully, the Tailscale web portal/dashboard does allow for the ability to disable the Tailscale DNS.

1. Go to https://login.tailscale.com/admin/dns
2. Scroll down to "Global nameservers".
3. You'll see a toggle to the right with a tooltip and text that says, "Override local DNS".  Disable that.
4. Done.

<img width="713" alt="image" src="https://github.com/tailscale/tailscale/assets/776016/589f3fba-a74c-460a-9f6d-85a5f693e147">

Hopefully your devices won't have issues connecting to the Internet anymore.  Good luck!

Btw, not sure if it's related to the cause of this issue, but I do use Pi-hole on my local network too.

**Comment by codecat** [comment]
I would still love to have a solution other than "disable Tailscale's DNS features". Have we been able to troubleshoot where exactly this is going wrong? I'm tempted to dig in and get to the actual root cause of this.

**Comment by lukevp** [comment]
@codecat I think tailscale is basically MITMing the DNS traffic machine-wide when it's set to use tailscale DNS, right?  So perhaps the underlying issue is that tailscale is not upstreaming all requests properly to the origin server.  I wonder if we could MITM the MITM by setting up some kind of DNS logging server on a machine and then set tailscale to use MagicDNS and then have it look up a bunch of nonexistent domains (that way it's not cached and must go upstream).  do it every second in a loop and see if there's some pattern to it or something.  I totally removed tailscale from my network a while back because of this issue, so I don't have it set up to investigate, but really interested in seeing this resolved so I could go back to using it.

**Comment by maphew** [comment]
Pixel 6 Pro here. Whenever I have tailscale app activated and I'm on cell network instead of wifi only tailscale destinations can be browsed to. All others timeout. 

I tried to use the suggestion from https://github.com/tailscale/tailscale/issues/6891#issuecomment-2041947449 of disabling overriding global DNS but the setting is already off, and disabled so I can't turn it on anyway.

**Comment by agottardo** [comment]
Reproduced on 1.65.0 with a Google Pixel 7a running Android 14. When the Private DNS setting is set to a custom DoT server and Tailscale is running, no DNS queries are going through in Chrome or other apps.
```
19.9M/323.9M wgengine: Reconfig: configuring DNS
19.9M/323.9M dns: Set: {DefaultResolvers:[] Routes:{tailnet-name.ts.net.:[] ts.net.:[199.247.155.53 2620:111:8007::53]}+65arpa SearchDomains:[tailnet-name.ts.net.] Hosts:445}
19.9M/323.9M dns: Resolvercfg: {Routes:{.:[192.168.1.1] ts.net.:[199.247.155.53 2620:111:8007::53]} Hosts:445 LocalDomains:[tailnet-name.ts.net.]+65arpa}
19.9M/323.9M dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[tailnet-name.ts.net. home.] }
```

Resolvercfg indicates `192.168.1.1` is being used for all queries which is the local network forwarder as expected. A system notification appears, indicating the Private DNS server cannot be reached anymore.

**Comment by stark1tty** [comment]
Same problem here on Windows 11.

**Comment by AlienatedCargo** [comment]
Came across this issue today and discovered that the solution above from chocolate42 to disable MagicDNS from within Tailscale web portal DNS settings has resolved my issue. Override local DNS was already disabled and I added google DNS servers for good measure (not sure if adding google DNS made a difference or not). 
Hope this helps others. 
Thanks

**Comment by agottardo** [comment]
This is an extremely generic issue that could be caused by a variety of reasons. In most of the cases here DNS seems involved, along with exit node misconfiguration, routes, bad interface switch detection, etc.

The comments here for the past 1.5 years have all been pointing at different causes, on different platforms, with different root causes. Most likely, some of the problems have probably been fixed in the meantime. All of this makes it hard to understand what this issue is actually tracking, so I'll be closing this.

If you experience a connectivity issue, please file a new issue **with a bug report identifier**. Or even better, please contact support. They can look at telemetry from your clients to understand what is actually going on.

**Comment by ryanovas** [comment]
The issue is definitely not resolved, at least on Android. When magic DNS is enabled sometimes websites simply won't load which requires us to have to selectively turn tailscale on and off when we need it. The only common solution I've seen in this thread is to disable magic DNS completely, which doesn't seem like it should be the final accepted solution here.

**Comment by agottardo** [comment]
@ryanovas as I already mentioned above, please open a new bug report **with a bug report identifier**, noting your app and Android versions, and specifying that it only occurs on Android when MagicDNS is enabled. Provide as many steps as possible to reproduce. If you have multiple devices affected as you mentioned, please attach multiple bug report IDs from each device.

I do want to fix the issue you're experiencing, but the team cannot make sense of what problems users are **_currently_** experiencing when a bug report originally mentioning macOS that is almost two years old gets resurfaced without any recent diagnostic information available. There have been dozens of different MagicDNS fixes since this issue was open, affecting different platforms. For instance, I'm quite sure the issue reported by OP originally was fixed by a change that went into Tailscale 1.58.0. The issue you're seeing on Android has most likely a different root cause, and is likely caused by a custom configuration since the majority of our users are not hitting it. Hence the need for a bug report identifier, so that our team can look at your config too.

We just cannot keep track of _which change fixed which issue_ when very old bug reports keep getting used years later to track issues with different root causes on different platforms. Hope you'll understand.

**Comment by Explosion-Scratch** [comment]
This was happening to me on linux, I fixed it with : `sudo ip route add default via 192.168.12.1`

**Comment by nallak** [comment]
For me problem got solved -> comment of joeynguyen

**Comment by joemarkey6** [comment]
Im having this issue now, the above fix doesnt work for me.
If I exit tailscale I have internet, if I enable it I have RDS but no internet

**Comment by armanrozika** [comment]
i am having this issue as well, but only with Brave browser, other browsers seem to work just fine
