### ISSUE TITLE
Taildrop silently fails when sending from Overcast

### ISSUE THREAD

**Issue by avidrissman** [tailscale/tailscale#7399]
### What is the issue?

On my iPhone, if I try to send an audio file from Overcast (2023.2), with Share > Export Audio File, the progress bar goes across, I get a blue checkbox, but nothing shows up on my other machine. I’ve tried to send to two different Macs, so it’s not that.

This used to work.

I can send a photo from Google Photos and it successfully is received, so it’s not a general problem, just maybe with a specific file type?

### Steps to reproduce

Open Overcast, Share > Export Audio File, Taildrop it to a Mac

### Are there any recent changes that introduced the issue?

I don’t know. All involved devices are on 1.36.2, but I do know that this used to work a few months ago when I taildropped a different audio file from Overcast.

### OS

macOS, iOS

### OS version

macOS 13.2.1, iOS 16.3.1

### Tailscale version

1.36.2

### Bug report

BUG-4811f8435f9df4a7b8b8aa3e1567719728f859686c19a217855eaef6a8ef33e5-20230228195823Z-32f9d1807b674830

**Comment by quartermarsh** [comment]
https://github.com/avidrissman Without going into great detail, taildrop is very inconsistent between Macs (all using the latest version of tailscale). I have four - one on 10.13.6, two on 10.15.7 and one on 13.2.1. I’m still trying to figure out how best to proceed with filing bug reports because some combinations work for taildrop and others don’t. I thought I’d mention that here for reference. I hope to file proper bug reports soon.

**Comment by quartermarsh** [comment]
@avidrissman > I get a blue checkbox, but nothing shows up on my other machine

I justtried sending a voice memo from my iPhone to my M1 Mac and had the same result.

**Comment by quartermarsh** [comment]
BUG-264a88fce5018bd21cead3d840d6399d91ca5da8da08ef2527f27bb6e0bfc347-20230228222528Z-480810c46c77e352

**Comment by quartermarsh** [comment]
Conversely, sending _to_ the phone does work, from 3 different OSes, with .pdf, .jpg and.png (although the documentation about taildrop notifications on the phone could be made clearer - it appears in the tailscale app, not as a system notification)

**Comment by quartermarsh** [comment]
Huh. Sucessful taildrop of a pdf to a mac - the only mac running the app store version of tailscale (because 10.13.6 can only run the app store version).

**Comment by quartermarsh** [comment]
I’ve just deleted the mac-sys version of tailscale from the M1 mac and installed the app store version. Taidrop now works as expected.

@avidrissman Sorry for jumping your issue :/ I’ll see myself out...

**Comment by avidrissman** [comment]
@quartermarsh That’s super interesting because I’m using the mac-sys version of tailscale.

Is this issue only with the mac-sys version!?

**Comment by quartermarsh** [comment]
Sure looks like it.

**Comment by quartermarsh** [comment]
@avidrissman Tip: if your going to switch to the app store version, don’t forget to remove the old machine from your tailnet once your done. And run ⌘F - system files are included - on ’tailscale’ to make sure you get all of the mac-sys version outta there. The extension files can’t be removed manually but will disappear after a restart.

**Comment by mihaip** [comment]
@avidrissman as far as I can tell the Mac did indeed receive the files

```
19:54:53 | peerapi: got put of ~26MB in 1.7s from 100.109.99.32/iphone
19:54:53 | notifyFunc: num files: 1
...
20:05:08 | peerapi: got put of ~43MB in 9.7s from 100.109.99.32/iphone
20:05:08 | notifyFunc: num files: 1
```

Do you see any permission-related errors in Console.app?

**Comment by avidrissman** [comment]
I don’t think I see anything permissionwise.

In any case, I started capturing in Console, did a drop of a file, then stopped capturing. I filtered by “tailscale” and this is the log:

[log.txt](https://github.com/tailscale/tailscale/files/10866740/log.txt)

If that helps.

**Comment by DentonGentry** [comment]
From log.txt, the `Invalidating assertion 424-947-182546` seems odd:
```
default	20:22:17.570034-0500	io.tailscale.ipn.macsys.network-extension	notifyFunc called
default	20:22:17.570791-0500	io.tailscale.ipn.macsys.network-extension	notifyFunc: num files: 1
default	20:22:17.918759-0500	io.tailscale.ipn.macsys.network-extension	notifyFunc called
default	20:22:17.919696-0500	Tailscale	NOGO-LOG: BackendClient: Notify: Version=1.36.2-t9450812f7-g622a25149 FilesWaiting LocalTCPPort=49225 IncomingFiles=1
default	20:22:17.919769-0500	Tailscale	NOGO-LOG: BackendNotify: files waiting
default	20:22:17.920097-0500	Tailscale	NOGO-LOG: BackendNotify: files waiting
default	20:22:17.921331-0500	Tailscale	Task <404B9F4E-1DA1-4F23-BEBC-71604D8B4905>.<102873> resuming, timeouts(60.0, 604800.0) QOS(0x21) Voucher <private>
default	20:22:17.921653-0500	Tailscale	[Telemetry]: Activity <nw_activity 12:2[690331C8-ACD6-4E04-9D8E-55D46AA6DF3C] (reporting strategy default)> on Task <404B9F4E-1DA1-4F23-BEBC-71604D8B4905>.<102873> was not selected for reporting
default	20:22:17.922113-0500	runningboardd	Invalidating assertion 424-947-182546 (target:[app<application.io.tailscale.ipn.macsys.73481762.73481768(501)>:947]) from originator [app<application.io.tailscale.ipn.macsys.73481762.73481768(501)>:947]
default	20:22:17.922714-0500	Tailscale	Task <404B9F4E-1DA1-4F23-BEBC-71604D8B4905>.<102873> now using Connection 1457
default	20:22:17.922794-0500	Tailscale	[C1457] event: client:connection_reused @539.230s
```

From our test matrix results we did test Taildrop send and receive using the macSys 1.36.0 app, however we install it from https://pkgs.tailscale.com/stable/ not using `brew`

If you download and decompress https://pkgs.tailscale.com/stable/#macos, does it notify when it receives the file?

**Comment by avidrissman** [comment]
I’m sorry, I don’t understand. I installed macsys a few versions ago (maybe in the 1.33-ish timeframe) from pkgs.tailscale.com and used Sparkle a few times when it was out of date. I have done no installation from `brew`.

**Comment by avidrissman** [comment]
I replaced the app with a new copy from pkgs.tailscale.com to no effect.

In an experiment, a PDF file Taildropped failed to work, but a PNG file did. I then started logging on my console and trying to replicate it, but then the PNG file failed as well.

The non-reproducibility of the PNG file case is odd.

**Comment by mihaip** [comment]
We've added some extra diagnostic logging in the latest unstable build (1.39.19 or later, can be downloaded from https://pkgs.tailscale.com/unstable/#macos). Could you try to reproduce the problem with that version, and if it does, generate a bug report ID and attach it to this bug?

**Comment by avidrissman** [comment]
I switched to Version 1.39.199 (macsys). I sent a file via Taildrop, it failed to show up in the downloads folder, and so I bugreported:

BUG-4811f8435f9df4a7b8b8aa3e1567719728f859686c19a217855eaef6a8ef33e5-20230425031557Z-1c10d2f4ae789e27

**Comment by mihaip** [comment]
@avidrissman thanks for trying again. I added some code to slurp in `os_log` entries from the app into bug reports, but it doesn't appear to be working (at least, they were not in your report). Could you try again and also include anything that Console.app reports as coming from the Tailscale process?

**Comment by mihaip** [comment]
We also have an updated unstable build (1.39.202 or later, can be downloaded from https://pkgs.tailscale.com/unstable/#macos) that fixes one possible cause of this bug, if you'd like to try that.

**Comment by avidrissman** [comment]
I updated to Version 1.39.202 (macsys) and alas it still occurs. 

BUG-4811f8435f9df4a7b8b8aa3e1567719728f859686c19a217855eaef6a8ef33e5-20230426023944Z-a378424bc46b6d7f

Here’s all the “process:tailscale” entries from the oslog.

[log.txt](https://github.com/tailscale/tailscale/files/11328444/log.txt)

**Comment by avidrissman** [comment]
@djweber noted in #7511 that he found files in `/Library/Tailscale/files/<<account>>` that were transferred but that failed to make it to the downloads folder. I just checked and that’s where the files are ending up for me too.

Your bug seems to be at the point where you try to move the files to the downloads folder and are failing.

**Comment by mihaip** [comment]
I'm no longer at Tailscale so I can't make further progress on the bug, but the error message from the oslog that stands out is:

```
error getting a waiting file: localAPIStatusError(status: 500, body: "open redacted.621d2771: no such file or directory\n")
```

That means that the app tried to move the file from the temporary location to the final one, but it was not ready yet (e.g. had not been fully received). There may be a race condition in how the notifications are sent (I fixed one before I left, but clearly it was not the only one). @nickoneill may be able to look more.

**Comment by avidrissman** [comment]
Still broken in 1.42.0, despite the changelog item mentioning taildrop.

**Comment by avidrissman** [comment]
A weird note is that jpegs transfer fine, but .mp3 files get caught and fail.

**Comment by avidrissman** [comment]
At some point in the past few releases this started working again.
