### ISSUE TITLE
[SOLVED] Tailscale iOS App 1.46 not Working - Initially Laoding Log in

### ISSUE THREAD

**Issue by MarvinMynx** [tailscale/tailscale#8673]
### What is the issue?

Log-in into the Tailscale iOS App Version 1.46.0 is not possible.
I, therefore, Removed the Device from the Admin Portal, force quit the App, Uninstalled the App, Updated the App on My Exit node Server, Rebooted it, Reinstalled the App on my Phone, and got Stuck at the same point without ever being even prompted for Login Credentials.
This is Happening since yesterday directly after the Update. Before it was working just fine and I changed nothing.

Oh, and I don't know how to create a Bug Report on my iOS Device. Because the Bug Report Menu isn't loading either. I just get a wired Formated Blank Page that says "Internal error" in Red Text.

### Steps to reproduce

IDK

### Are there any recent changes that introduced the issue?

App Store Tailscale App Update.

### OS

iOS

### OS version

16.5.1 (c)

### Tailscale version

1.46.0

### Other software

No.

**Comment by agottardo** [comment]
@MarvinMynx Sorry you had to go through all these steps. Just to confirm: did you try rebooting your iPhone? There is an issue in iOS that causes our network extension to not launch for a small number of users after the App Store performs an automatic update (reported to Apple as FB12691478). A reboot should fix it.

If a reboot doesn't fix it, can you please share a sysdiagnose from your device? We need data to diagnose the issue. You can email me at andrea (at) tailscale (dot) com.

**Comment by MarvinMynx** [comment]
It is working again after a reboot. Thanks for the tip.

**Comment by YinglunMao** [comment]
The same issue occurs to me, and I have tried rebooting, but it is still not working. My OS version is iOS 16.2 (20C65), and I have a Bug Report showing up: BUG-3331806e76becf0d38c85411ff4a8da303a94ebe015b064fe77a9d60e0ba9767-20230721143951Z-1cf73489fd44510a

**Comment by YinglunMao** [comment]
Follow up: I changed my login method, problem solved.

> The same issue occurs to me, and I have tried rebooting, but it is still not working. My OS version is iOS 16.2 (20C65), and I have a Bug Report showing up: BUG-3331806e76becf0d38c85411ff4a8da303a94ebe015b064fe77a9d60e0ba9767-20230721143951Z-1cf73489fd44510a

**Comment by MarvinMynx** [comment]
Issue is Solved.

**Comment by GeorgesAlkhouri** [comment]
I am also experiencing the same issue via the GitHub login, @YinglunMao how did you change the login method ?
